### ISSUE TITLE
MostCited / MostViews Empty Box Spurious Error

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#100]
The error here is in the server, but I think the solution is in the client, so I'm posting here.  There's nothing wrong with the Solr call, but the call returns an error (via Solrpy) fairly often when done through the end-user interface, but never when called directly.  

I've tried lots of things to the parameters, just in case solrpy/solr was triggering on anything real, but so far nothing works.  

I think it's a call timing issue.

If you watch the interface, sometimes it works, sometimes the problem is Mostcited, sometimes MostViewed.  I had seen that before early in PEPEasy, and the way I solved it is add a delay between so they are not refreshed at the same time.  I think I had it at a meager .5 seconds, but if we can try that here, it would be better to try a longer one and then shorten it to a consistent number.

Can you please try that -- say a generous 5 seconds to start -- and let me know when it's up?  I presume that won't hold up the refresh, that it's an event in the background.  All it would mean is the user would have a blank MostCited box in the beginning, and then 5 seconds later it would populate.

Note that when I get the error from Solr, I now produce an HTTP Exception for the client.

Thanks.

**Comment by nrshapiro** [comment]
This is **significantly** better now, with the delay...however, I am occasionally seeing one box left blank during a refresh.  Needs watching.

**Comment by adistasio** [comment]
@nrshapiro I assigned this to you as I believe you are converting the API to use a new solr connector.

**Comment by nrshapiro** [comment]
@adistasio 

The version of the API/Server on Stage uses the "new" PySolr middleware.  I would still leave the delays in anyway, they don't harm the look and it avoids a potential traffic jam on the server.  We had a similar problem with the Browse mode which was also solved by adding a delay (at least, again, with the old SolrPy middleware.)

I guess the question, before we close this: Does the spurious empty box still occur?  I haven't seen it, so it may be resolved.  But we should watch for a bit more.

**Comment by nrshapiro** [comment]
This appears to be resolved by Pysolr with the current delays in place.
