### ISSUE TITLE
Login Issue - Need more info

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#109]
Today's problems with PaDS Login point to an issue.  When I try to login, with a valid account, it just tells me it can't login.  Really, the user needs to know to stop trying, that login's aren't available at that time, to try again later.

Not the best news for the user, but not sure what else we can do at this point.  But what we don't want is the user to be trying other things, calling support, etc., to know why his login isn't working...when in fact, we already know that it's a problem elsewhere.

**Comment by jwoosnam** [comment]
@nrshapiro 
Basically this is because the website has fallen over, therefore it is going to be difficult for me to give you any better information, I think? I agree that the user should get a better message but this sort of problem is not something that generally happens.

**Comment by nrshapiro** [comment]
@jwoosnam
Agree if the site isn't "there" can't be done from PaDS, but perhaps from the client app.
