### ISSUE TITLE
Glossary Dialog - Links don't work

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#113]
Reference links don't work--they produce an error in the main window.  (Links to other glossary terms do work.)

**Comment by bakerac4** [comment]
Looks like a 404 from the API when requesting 

```
https://stage-api.pep-web.rocks/v2/Documents/Document/PSC.037.0245/?return_format=XML&search=%27%3Ffacetfields%3Dart_year_int%252Cart_views_last12mos%252Cart_cited_5%252Cart_authors%252Cart_lang%252Cart_type%252Cart_sourcetype%252Cart_sourcetitleabbr%252Cglossary_group_terms%252Cart_kwds_str%26facetlimit%3D15%26facetmincount%3D1%26highlightlimit%3D1%26synonyms%3Dfalse%26fulltext1%3D%27```

**Comment by nrshapiro** [comment]
You sent a bad document id.  It's PSC.037.0245A

Most, if not all, document IDs end in a letter.  (If they don't, it's abnormal and probably an error.)

[https://stage-api.pep-web.rocks/v2/Documents/Document/PSC.037.0245A/?return_format=XML&search=%27%3Ffacetfields%3Dart_year_int%252Cart_views_last12mos%252Cart_cited_5%252Cart_authors%252Cart_lang%252Cart_type%252Cart_sourcetype%252Cart_sourcetitleabbr%252Cglossary_group_terms%252Cart_kwds_str%26facetlimit%3D15%26facetmincount%3D1%26highlightlimit%3D1%26synonyms%3Dfalse%26fulltext1%3D%27](https://stage-api.pep-web.rocks/v2/Documents/Document/PSC.037.0245A/?return_format=XML&search=%27%3Ffacetfields%3Dart_year_int%252Cart_views_last12mos%252Cart_cited_5%252Cart_authors%252Cart_lang%252Cart_type%252Cart_sourcetype%252Cart_sourcetitleabbr%252Cglossary_group_terms%252Cart_kwds_str%26facetlimit%3D15%26facetmincount%3D1%26highlightlimit%3D1%26synonyms%3Dfalse%26fulltext1%3D%27)

**Comment by bakerac4** [comment]
I believe this is fixed - closing for now - please re-open if there are still issues!
