### ISSUE TITLE
Refresh abstract/document after login

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#114]
After a user does a search, if not logged in, they hopefully respond to the "you are not logged in" message, e.g., at the top of the read middle pane, by logging in.  When they do, as I just tested, the client needs to requery the server to get the full-document (or abstract) they were trying to look at.  Currently, there's no refresh, unless you force it.

Note that I've changed the return abstract to 

1) be restricted, if the server parameter says they must be logged in to see abstracts,
2) All be "complete".  The XML abstract return is now the same as for the document, minus the body, so your XSLT/CSS now works to display a much nicer abstract.  Likewise, HTML abstract return is now based on that XML, converted to HTML, rather than a converted abstract with "generated" front-matter (title, authors, etc.).  Same for TEXTONLY return.

This works very well in the current client, as stage now shows.

**Comment by bakerac4** [comment]
It seems like the client can't do a search while logged out anymore (all endpoints are returning 424's). Is that correct? @nrshapiro
