### ISSUE TITLE
Glossary Infocard Links - Dialog while not logged in

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#119]
I am not logged in.  Using client 2020.11.13-5010.
1. I clicked on one of the most cited documents
2. I then clicked on one of the terms in the glossary infocard.
3. I got this:

![image](https://user-images.githubusercontent.com/4837554/99327210-6d82a680-2847-11eb-85c7-44e44186cf9b.png)

While not logged in, the glossary dialog should appear similar to the content we show users when trying to view any other document while not logged in.

4. I logged in under test3.  I am a registered user now.  No subscription.
5. The article I was viewing remained the same, without an abstract.  It should have refreshed with my new rights--at least to view the abstract.  
6. I pressed F5, refresh.  Now I can see the abstract.  (See https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/114)
7. I clicked on a glossary entry.  I still got the error shown in the screen capture above. 
8. I logged out.
9. I wasn't able to log back in under any legal ID.
10. I could still see abstracts, though I was logged out.  (Not a big deal.)
11. I cleared all the cookies
12. I refreshed, and now abstracts were gone.
13. I was able to login again.  This time as test4 (with subscription)
14. Documents (full-text) and the Glossary were working now

**Comment by bakerac4** [comment]
@nrshapiro Im seeing an issue with the return format for the following endpoint.

https://stage-api.pep-web.rocks/v2/Documents/Glossary/desire/?return_format=XML&termidtype=Group

Even though Im passing in `return_format` of XML, its still returning html

**Comment by nrshapiro** [comment]
I just tested the online Stage version in the interactive docs interface, and it returned XML correctly when requested.

Here's a partial from that....the first document record retrieved, the "document" member.  

        "document": "<dictentrygrp id=\"YP0019131450970\"><term>DESIRE OF THE ANALYST</term><dictentry><src>Skelton, R. (Ed.). (2006). The Edinburgh International Encyclopaedia of Psychoanalysis.</src><def><p>Lacan's concept of the <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0019131450970\" grpname=\"DESIRE OF THE ANALYST\">desire of the analyst</impx> concerns the function of <impx type=\"TERM2\" rx=\"ZBK.069.0001u.YP0013420666620\" grpname=\"Unconscious\">unconscious</impx> <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0004718997320\" grpname=\"DESIRE\">desire</impx> as an enigma. It is considered the driving force of the analytic treatment, for the analyst. This <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0004718997320\" grpname=\"DESIRE\">desire</impx> (of the analyst) has as its <impx type=\"TERM2\" rx=\"ZBK.069.0001o.YN0004676559070\" grpname=\"Object\">object</impx> <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0004718997320\" grpname=\"DESIRE\">desire</impx> itself. The <impx type=\"TERM2\" rx=\"ZBK.069.0001a.YN0007688340420\" grpname=\"Analytic process; Psychoanalytic Process\">analytic process</impx> is directed towards a <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YN0004234282370\" grpname=\"DESTITUTION\">destitution</impx> of the <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YN0015186348230\" grpname=\"SUBJECT\">subject</impx>, in the form of the analysand's acceptance of the fundamental *lack. As such analysis not only touches upon the <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YN0015186348230\" grpname=\"SUBJECT\">subject</impx> as <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YN0015186348230\" grpname=\"SUBJECT\">subject</impx> of <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0004718997320\" grpname=\"DESIRE\">desire</impx> &#8212; the acceptance of <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0004718997320\" grpname=\"DESIRE\">desire</impx> <impx type=\"TERM2\" rx=\"ZBK.069.0001b.YN0015659043440\" grpname=\"BEING\">being</impx> fundamentally alienated &#8212; but also its <impx type=\"TERM2\" rx=\"ZBK.069.0001r.YN0013074626040\" grpname=\"RELATION\">relation</impx> to the <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0005442939990\" grpname=\"DRIVE\">drive</impx> (and its objects). The latter is situated &#8216;beyond&#8217; the process of <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YP0017378833180\" grpname=\"SEPARATION\">separation</impx>, for the <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0005442939990\" grpname=\"DRIVE\">drive</impx> only needs the <impx type=\"TERM2\" rx=\"ZBK.069.0001o.YN0004676559070\" grpname=\"Object\">object</impx> (and not the other) to run its course. Hence, the <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0019131450970\" grpname=\"DESIRE OF THE ANALYST\">desire of the analyst</impx> is to install and maintain the <impx type=\"TERM2\" rx=\"ZBK.069.0001p.YP0000489824390\" grpname=\"Position\">position</impx> of the <impx type=\"TERM2\" rx=\"ZBK.069.0001c.YN0004867612400\" grpname=\"CAUSE\">cause</impx> of <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0004718997320\" grpname=\"DESIRE\">desire</impx>, and as such &#8216;enable&#8217; the analysand to work through the <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YP0013831327350\" grpname=\"SCHIZOID PERSONALITY; PROCESSES\">processes</impx> of <impx type=\"TERM2\" rx=\"ZBK.069.0001a.YP0002242991700\" grpname=\"ALIENATION\">alienation</impx> and of <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YP0017378833180\" grpname=\"SEPARATION\">separation</impx>, as well as <impx type=\"TERM2\" rx=\"ZBK.069.0001a.YP0005740675060\" grpname=\"AFFECT; AFFECTS\">affect</impx> the <impx type=\"TERM2\" rx=\"ZBK.069.0001s.YN0015186348230\" grpname=\"SUBJECT\">subject</impx> of the <impx type=\"TERM2\" rx=\"ZBK.069.0001d.YP0005442939990\" grpname=\"DRIVE\">drive</impx>.</p><p>K. Lib.</p></def></dictentry></dictentrygrp>",

I'm about to load the new PySolr version, and test it, and that behaves the same.

**Comment by nrshapiro** [comment]
@bakerac4 
Ok, I see a problem -- I was being tricked by a non-logged in path.  Will fix....

**Comment by nrshapiro** [comment]
@bakerac4 

I take it back :)  missed a not.  It should be working fine as is.  The none conversion side of the coin was "_not_ accesslimited

So the bug was It was only returning HTML **when "not logged in"**, but the data should have been limited then anyway...when logged in, it wasn't calling the HTML conversion routine.
