### ISSUE TITLE
Word Wheel speed impacted by calls to Search with each keypress

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#133]
Currently, when you type in the fields, it sends both a word wheel search, and a fulltext search to the server.  

Calling the server to get facets with fewer than 4 or 5 characters typed is not really a good use of resources, and it slows down the performance of the word wheel, making it less useful unless you are a hunt and peck typist.

The facets aren't really needed until you either press Search, enter a "space" to start a second word, or pause typing for 1 or 2 seconds.  It's very nice to have the facets once you enter a real word, even if you plan to enter a second or third, but not much use with a partial word.

To experiment with this, I've set the server to return a 422 error if you send a search with less than 5 characters.  I don't think we have **important** words of 4 characters, but really, that's not the right way to implement the restriction anyway.

Thus, I would like you to implement this in the client.  That way, you can send word wheel but not full-text searches for the first 3 or 4 characters, and then if, for whatever reason, the user does enter a three letter word and presses "Search", it will be executed (after I remove the restriction.)  But I wanted to try it to check whether the word wheel works better, and I think it does.

**Comment by nrshapiro** [comment]
Unfortunately, I can't leave this restriction in the server, as it does impact what searches work.  It needs to be in the client.

**Comment by adistasio** [comment]
We are making this call to update the refine. Instead only do the refine when the user hits search.

**Comment by nrshapiro** [comment]
@adistasio @billdami  @bakerac4 

The fix breaks the refine mode behavior.  Once the search has been executted, Refine doesn't work as it should.  As opposed to typing the search criteria, clicking on an entry in refine should always refresh the search, or else we need to reintroduct the "Refine" button, because it's counter-intuitive to press Search in the search area above, when you set something in the Refine area.

Given that the events of typing a search and clicking on a button in Refine are completely and easily separable, the ideal would be to treat these events differently.  Clicking on an button in Refine should update the results.  Just like it does on Amazon and other sites.
