### ISSUE TITLE
XML Doctype Leaks into hit list in search results

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#142]
I've seen this before, not likely to be high incidence, but here's an example:

![image](https://user-images.githubusercontent.com/4837554/100794949-405bf980-33ec-11eb-988e-0daf1d4b0785.png)

**Comment by nrshapiro** [comment]
Likewise for document revision metadata.  I can remove that from the XML when it's loaded into Solr.  But I can't do that for the required XML header info.

![image](https://user-images.githubusercontent.com/4837554/101060920-eed37c00-355d-11eb-8e4d-37d2c56114c5.png)

**Comment by bakerac4** [comment]
@nrshapiro even if we are suppose to remove this from the `kwicList`, its not valid XML due to the first element missing its opening character

```
"DOCTYPE pepkbd3 SYSTEM "http://peparchive.org/pepa1dtd/pepkbd3.dtd">

    2013
    12
    4
    First Cases: Beginning Therapists Write about the Process and Content of Their Earliest Work
    Articles260-270
    Becoming Real Together: The <span class='searchhit'>Parallel Discovery</span> of Authenticity in a Traumatized Child and First-Time Therapist
    KiraBoesch
 
 Kira Boesch is a doctoral student in the clinical psychology program at the City University of New York at City College.
```

**Comment by nrshapiro** [comment]
I've fixed this by scanning for and removing any partial elements/tags/doctypes from the beginning of a hit entry in the hit list in the server in Server 2021.0405.2.Beta
