### ISSUE TITLE
Clearing Refine Settings

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#15]
Perhaps it's just not in yet, but Clear Search doesn't clear the refine settings.  Perhaps it shouldn't, so you can leave a choice of English, for example, in your search criteria, but then there needs to be an easy way to clear all the refine settings in case you have multiple selections made, and want to start over. 

Perhaps you could do this in like manner to the way the search buttons are laid out.
   `Clear  [REFINE]'

**Comment by billdami** [comment]
@nrshapiro yeah, not clearing the refine settings on Clear was just a mistake on my part, I'll be adding that in in my next pass, as well as fixing the "sticky refine options" issue you detailed in #19.

If we feel this isn't a good enough UX though and it should have a separate clear action for the Refine settings like you suggested, we can definitely look at adding that later though.

**Comment by billdami** [comment]
Resolved via #20 (minus potential future "clear refine" functionality)
