### ISSUE TITLE
(Re)Entering Site from Read URL Fails (logged in) - White Screen

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#155]
This morning I went to load stage, and I tried to go to a URL based on a previous session.  It came up with a white screen.

I entered the base URL (stage.pep-web.rocks) and that showed up fine.  Later, while trying to get a good view of the site for a screen capture, Opera itself crashed.  I'll assume it's not the app that crashed it, since I had a lot of tabs open (no more than usual though!).  But then Opera automatically recovered all my tabs, and the URL I was at came up with a white screen.

https://stage.pep-web.rocks/read/IJP.084.0387A?q=%22Eitingon%20Model%22

Looking at the what inspect shows:

![image](https://user-images.githubusercontent.com/4837554/101246074-eb1b3300-36de-11eb-92ad-0c32d965bbee.png)

I pasted this URL over to Chrome and it comes up blank as well.

Consistently blank.

I tried without the query parameter, still comes up empty, back in Opera.  (I went back to Opera because on chrome I am not logged in to stage.  

Seems like there's a problem with Read starting from a URL.

**Comment by bakerac4** [comment]
Fixed in master
