### ISSUE TITLE
PEP Email Notifications of Updates (Subscriptions in the interface)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#168]
@adistasio @jwoosnam 

This enhancement/clarification is per our tech meeting of this week.  

**Part 1.** Question raised: Should only registered users be able to subscribe to notifications?
After discussing with D/N, the answer: Yes, only registered users.  That will serve as an encouragement to register, and means that we will know who is getting notifications, per the PaDS user database.  And if a user is removed from that database, so will the notification.

**Part 2.** Update Subscriptions.  This was how it was referred to in the spec.  I realize now that's confusing.  In PEP-Web it was simply referred to as "email alerts".  That may be a bit confusing too, but perhaps not, if you add "Content" to it, i.e., 

**On the old pep-web**
"New Content Alerts"
![image](https://user-images.githubusercontent.com/4837554/101914675-94a46d80-3b92-11eb-8042-73bf78591373.png)

Current new dialog:
![image](https://user-images.githubusercontent.com/4837554/101915368-89057680-3b93-11eb-881e-e5d3b2589d32.png)

Changes: 

1.  Textual
- Hover text on Whats New envelope: "New content alerts"
- Button on dialog: chg from "Update subscriptions" to "Update Content Alerts"
- We should probably add" New Content Alerts to the top of the dialog, perhaps right after the What's New? e.g.,
- What's New - New Content Alerts
2.  Add you must be logged in message to dialog, with login link and disable "update" button if not.

**Comment by jwoosnam** [comment]
A few observations/questions:
1) If the user is logged on, they shouldn't have to enter their email.  If they are allowed to enter an email that opens it up to abuse, however unlikely!!
2) I didn't think the new system had IJP Open?
3) Please could you clarify where the settings are going to be stored?  Will it be in the client settings object? This might be neat as the user wouldn't then have to go through the retrieval and save functions, they would just be there.
4) Does PEP need a log of who has been sent the emails?

**Comment by nrshapiro** [comment]
1.  That makes sense.  Though if they are logged in, I don't know what kind of abuse you mean.

2.  It doesn't.   (Though that could change in the future, since IJP Open's future is undefined as far as PEP is concerned

3.  We don't have requirements currently beyond what our old system did. That data was not stored in SecureCenter.  
But the idea to store them for registered users only sort of implies it would be tied to the user's data.  While it could be done transparently to PaDS using the client settings object, that would preclude (or make more difficult) ever doing anything with the data, such as producing a report like you asked for in #4.  So I would think it might be a good idea to store it along with the user's profile data.  That way, you don't have to worry about #4...you could always produce the necessary report, if one becomes desirable.

**Comment by jwoosnam** [comment]
1) This is very theoretical and pretty unlikely, but if you could just put in an email address and update the notification settings, then anybody could put in somebody else's email address and update their settings.
2) Good
3) I agree pads is the logical place to store them. I am concerned about the level of change in the notification options.  Is it just the 2, or will there be more/less in the future? If the notification options are stored in pads then we will need a new API to allow the information to be made available to the process that sends the emails, or should that also be in pads?

**Comment by adistasio** [comment]
I believe we can just use the user settings endpoint that already exists to save json. It would also let the user add more than 1 email address and we can adjust the UI to show them the emails they have alerts for. 

We would also want an endpoint that can be queried to get emails by alert. This way when we deploy changes to the articles we can email the correct people. Either that or an endpoint should exist within pads that will take a list of article changes for an alert that will trigger the sending of the emails.

**Comment by nrshapiro** [comment]
@adistasio Is this issue resolved?  I think the subscription interface is implemented, right, but Leyla @lhorne-gavant  just has to turn it on for all (rather than just me?)

**Comment by nrshapiro** [comment]
@adistasio It should be on, I would think now, for beta.  Please confirm so we can close.

**Comment by adistasio** [comment]
It's on for stage but the beta site still limits. We didn't want to duplicate email from the beta and current production. We could turn it on for beta if you'd like it's just a config change. @nrshapiro

**Comment by nrshapiro** [comment]
@lhorne-gavant  

1) Before we go live on Thursday or Friday, can you confirm that users will get notices from Production?
2) What's the criteria for inclusion in the notice when we push stage to production?

Thanks in advance.

**Comment by lhorne-gavant** [comment]
@nrshapiro 
1. Yes, users should get notifications.
2. PADS users will get a notification if they've subscribed to either journal and/or video updates. Does this answer your question? Based on logs, it looks like you've been getting staging notifications for both journal and video updates. Have these looked the way you want them to?

**Comment by nrshapiro** [comment]
@lhorne-gavant 

2a) Specifically I mean: when we push to production, what is the basis of deciding what the new articles are in the notice?  Obviously, when we load on stage, they're new, but when we push to production, the entire database goes over.  And we've not done updates on production since October!  That could be a very long email!

2b) Yes, they are fine.  I notice the ones from stage say "Test" in the subject.  I presume that's the only way to tell the difference between production and stage, correct?

**Comment by lhorne-gavant** [comment]
@nrshapiro 
2a. The data update logs that the opas data loader generates for a particular load contains the articles that will be sent. It ends up being the same file for staging as production. It occurs to me that that's probably not what we want. We probably actually want all changes since the last deployment. If that's correct, I'll need to think on how to determine this. 
2b. Good and yes, stage should say "Test"

**Comment by nrshapiro** [comment]
This has been fixed.
