### ISSUE TITLE
Most Cited / Most Viewed

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#17]
Both info cards are labeled Most Viewed.

(Minor bonus issue report: the favicon for the browser tab isn't working)

**Comment by bakerac4** [comment]
Labels are fixed in #16 - once that gets merged in I'll close this out.

**Comment by bakerac4** [comment]
@billdami will pull in the favicon from the old site with his next merge

**Comment by nrshapiro** [comment]
> @billdami will pull in the favicon from the old site with his next merge

If you want, you can use these, to make this look different than our current site
Just temporary...we'll have a graphic designer do better with logos etc for the final.

![PEPTemp2021Favicon 128](https://user-images.githubusercontent.com/4837554/92023217-770d6f80-ed2a-11ea-9611-3cd5d16eeb6c.png)
![PEPTemp2021Favicon 192](https://user-images.githubusercontent.com/4837554/92023219-770d6f80-ed2a-11ea-87f4-a187798a4e2f.png)
![PEPTemp2021Favicon 256](https://user-images.githubusercontent.com/4837554/92023220-77a60600-ed2a-11ea-9455-2adaebccdfc5.png)

**Comment by billdami** [comment]
@nrshapiro the card titles should be fixed in the current stage build. (for the favicon, i just duplicated what you have on the current site, as it had all the other sizes already. So we can just wait on the new final designs if that works for you.)
