### ISSUE TITLE
Read Mode Article Title -> Linked to Browse TOC

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#171]
There's a link, correctly, in the read mode article title that takes you to the TOC for the issue, and presumably the location of the article in the TOC.  

However, when you click on it, as demonstrated in this article example, it doesn't do anything.

Sample: https://stage.pep-web.rocks/read/RFP.037.0517A

Interestingly, if you right click on it and say open in new tab, it works and takes you to the TOC, though not to the article's position in that toc.  So I wonder why a click doesn't work directly?

**Comment by bakerac4** [comment]
@nrshapiro I believe this is fixed on stage
