### ISSUE TITLE
Not Logged In - Download links of documents/pdfs/epubs should be disabled 

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#173]
@adistasio RE: the new Client: 2020.12.14-5431

If I'm not logged in, the new download link on the Read Page should be disabled or it should lead to a dialog for the user to log in to download.  This is not a problem on the Abstract preview page because it's not shown unless you are logged in.

Currently, selecting a download just shows the rejection json message from the server, not meant for end-users.

The print button, on the other hand, should print the abstract (with title area etc.) for them if they are not logged in, and of course, the article being viewed, if they are logged in.

**Comment by adistasio** [comment]
this was resolved. we hide the buttons if you don't have access to the article.
