### ISSUE TITLE
Banner Issues (as a running list of instances)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#176]
I'll treat this as I will treat link issues going forward, as a running list rather than bugging any issues separately.  (I presume there will be more than one).  Thus, this issue should not be closed (if it turns out there are multiple issues as I presume).

First issue: https://stage.pep-web.rocks/read/GW.004.0000A

Note 
 1) the banner error only happens if you are not logged in
 2) the other GW articles in the read list are ok.

**Comment by bakerac4** [comment]
I believe this can be closed now - please reopen if needed
