### ISSUE TITLE
Text Anomalies (as a running list of instances)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#178]
I'll treat this as I will treat other instance issues going forward, as a running list rather than bugging any issues separately. (I presume there will be more than one). Thus, this issue should not be closed (if it turns out there are multiple issues as I presume).

**Comment by nrshapiro** [comment]
First Issue: https://stage.pep-web.rocks/read/IPL.118.0001A

See text: T001TOCcenterfalse which should not be there.

![image](https://user-images.githubusercontent.com/4837554/102263580-7fa54280-3ee2-11eb-943d-c8dbd74b7c36.png)

**Comment by bakerac4** [comment]
Seems like this is fixed. Closing for now
