### ISSUE TITLE
Dead Links (as a running list of classes and instances)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#181]
I'll treat this as I will treat other instance issues going forward, as a running list rather than bugging any issues separately. Thus, this issue should not be closed (if it turns out there are multiple issues as I presume).

**Comment by nrshapiro** [comment]
#1.  https://stage.pep-web.rocks/read/PAQ.085.0695A

The journal banners are linked to a listing of all articles, but this doesn't work.  It might be nice to do just the current article volume instead, otherwise, that might be something we'd want to do from the vol/issue number underneath the banner.

![image](https://user-images.githubusercontent.com/4837554/102267735-55568380-3ee8-11eb-90cd-41485a1bdab7.png)

**Comment by bakerac4** [comment]
@nrshapiro I believe this is fixed on stage

**Comment by bakerac4** [comment]
@nrshapiro I know you mention not to close this, but its becoming hard to keep track of what I have done and what I haven't. Thoughts about closing this for now?

**Comment by nrshapiro** [comment]
@bakerac4 

I will close as long as you don't mind getting individual reports for dead links.  I actually prefer that anyway.  (This is just what Alan and I came up with at a meeting...he thought it would be less distracting.  We can also close the other running thread.
