### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#185]
On Stage, logging in as Test3.  All worked fine, but there's no access, so I logged out, and was about to login.

Click Logout...
Click Login... (I didn't get a chance to enter any data, this happened immediately:)

Result: Internal server error

![image](https://user-images.githubusercontent.com/4837554/102506626-4fc87d00-4051-11eb-841b-c93a1f85c6b0.png)

Clearing app cookies fixes the problem.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio @billdami 

Like the previous release, the new client release on January 19th has crashed during normal use.

I was actually just finding a search example, then making my window smaller to take a screen shot, and ended up here:

![image](https://user-images.githubusercontent.com/4837554/105090134-07471980-5a6c-11eb-933d-8fc1a2fc06b3.png)

I've added the diagnostic pane to let you see the cookies.

We are at the point where such crashes are now elevated in important to High Priority.  We won't go to our public "Beta" with it happening, and although it's only happened once today, I've used the new site code very little, so I'll have to watch it before I decide it can go to the board.

**Comment by bakerac4** [comment]
@nrshapiro do you know exactly when this happened? 

The only time I have ever seen this is I _believe_ when we do a push to stage and everything is down.

**Comment by bakerac4** [comment]
@nrshapiro bump - see above

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 @jwoosnam 

I just tried to replicate this, thinking I could close it, and an interesting thing happened.  

1. I logged in as Test3.  
2. Then I went to the Home view/tab
3. Then I logged out so I could log in as someone else, per the test.  I didn't get a chance to do that.

It's now showing me as Logged In Via IP:

![image](https://user-images.githubusercontent.com/4837554/105909630-c9ab3900-5ff5-11eb-826a-fbe57630ab6d.png)

Here's the session info from the pep_session cookie:
{"authenticated":{"authenticator":"authenticator:ip","SessionId":"3a44454b-7dcb-46d4-85f0-eff9b47db501","SessionExpires":602796,"IsValidUserName":true,"IsValidLogon":true,"HasSubscription":true,"ReasonId":200,"ReasonStr":"","SessionType":"ip","expiresAt":1612300116526}}

**Comment by jwoosnam** [comment]
@nrshapiro @bakerac4 From the log I can see Neil logged on as test3, I can then see the successful logout returning a new session, the client then seems to continue using the original session id:
<img width="1269" alt="Screenshot 2021-01-27 at 07 54 59" src="https://user-images.githubusercontent.com/70103034/105960488-31ed2f80-6075-11eb-8499-52e508eb08ac.png">

 Once logged out the session returns "blank" user details:
{
    "UserId": 0,
    "UserName": null,
    "UserFullName": null,
    "UserType": null,
    "SubscriptionEndDate": "0001-01-01T00:00:00",
    "IsSubscriptionRenewalDue": false,
    "PaDSHomeURL": null,
    "PaDSRenewalURL": null,
    "Branding": null,
    "ClientSettings": null,
    "HasCurrentAccess": false,
    "HasArchiveAccess": false,
    "ReasonDescription": "SessionId has not been successfully logged on, so user details can't be retrieved.",
    "EmailAddress": null,
    "LoggedInMethod": null,
    "ActiveSubscriptions": null
}

**Comment by jwoosnam** [comment]
@bakerac4 @nrshapiro I tried but failed to re-produce the error that Neil got.  Previously, using a logged out session would have produced the Internal Server Error that triggered this issue.

**Comment by jwoosnam** [comment]
I am closing this as "Internal Error Issue" is resolved.  I have raised the "Logged On via IP" as Issue: #257
