### ISSUE TITLE
Text Formatting Issues (as a running list of instances) 

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#188]
This issue "thread" is to document general formatting issues in the presentation of data.

I'll treat this as I will treat other instance issues going forward, as a running list rather than bugging any issues separately. (I presume there will be more than one). Thus, this issue should not be closed (if it turns out there are multiple issues as I presume).

**Comment by nrshapiro** [comment]
Format Subissue #1 (#188.1):  Bibliography entries should be formatting with hanging indent.

Example from PEP-Web:

![image](https://user-images.githubusercontent.com/4837554/102696179-6958f880-41fa-11eb-96a5-98b95a39bf66.png)

**Comment by bakerac4** [comment]
#188.1 fixed by 016eda2..8c9cf87
