### ISSUE TITLE
Two video browse issues

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#198]
1) When you click on items in browse, the left pane is supposed to fill with articles from the same issue.  This works for many of the entries (e.g., IJPVS.001A.0003A), but not for some:
   a)  PEPGRANTVS - does not work, [should show this list](https://stage.pep-web.rocks/search?q=art_id:PEPGRANTVS.*.*)
   b)  PEPTOPAUTHVS - does not work, [should show this list](https://stage.pep-web.rocks/search?q=art_id:PEPTOPAUTHVS.*.*)
   c)  AFCVS doesn't work, [should show this list](https://stage.pep-web.rocks/search?q=art_id:AFCVS.*.*) 
   d) IPSAVS doesn't work, [should show this list](https://stage.pep-web.rocks/search?q=art_id%3AIPSAVS.*.*)
   e) NYPSIVS doesn't work, though there's one article, but it [should show this list](https://stage.pep-web.rocks/search?)q=art_id%3ANYPSIVS.*.*
...there may be more...

**Comment by bakerac4** [comment]
@nrshapiro Im probably missing something, but these seem to be working. 

The steps Im following are 

1. Go to /browse/PEPGRANTVS/volumes/1
2. Click on the first item in the list
3. Check the sidebar for those items. I see all 14 items in the sidebar

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

Maybe some are working now, I had filled in the bug report form a few days ago...(Friday maybe), but found the tab with the bug this morning as yet unsubmitted, so I submitted it.  BUT...

I just randomly tried a few and found this/these not showing the others:

PEPTOPAUTHVS doesn't work...e.g.,

   https://stage.pep-web.rocks/read/PEPTOPAUTHVS.001.0003A
   https://stage.pep-web.rocks/read/PEPTOPAUTHVS.001.0015A

This one doesn't work:
https://stage.pep-web.rocks/read/PEPGRANTVS.001.0012A

NYPSI (only one article), but I note there's no banner logo

![image](https://user-images.githubusercontent.com/4837554/102925992-429cfb00-4462-11eb-8416-6cec8d9533a3.png)

ALSO: How do users get to /browse/PEPGRANTVS/volumes/1?  It might be nice to be able to, but now we are listing individual videos rather than publishers, so how does a user get there?  I got there by URL manip, not clicking.

(And I think I already  bugged this separately--I'll check--but the full video list in the Videos tab is not in useful sort order.  The API returns them sorted by title, which jibes with journals display.)

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

Updating this in case you think this is just hanging around and is actually working, per this note.

I just replicated your steps exactly (which I didn't do last time):

> @nrshapiro Im probably missing something, but these seem to be working.
> 
> The steps Im following are
> 
> 1. Go to /browse/PEPGRANTVS/volumes/1
> 2. Click on the first item in the list
> 3. Check the sidebar for those items. I see all 14 items in the sidebar

Doesn't work for me!  

https://user-images.githubusercontent.com/4837554/105907138-9f0bb100-5ff2-11eb-93e3-b4e228bd7a9a.mp4

Other IMPORTANT consistency of operation notes about these listings:

1) unlike other browse listings, note there's no graphic banner showing, even though there is one for pepgrantvs.  
   compare 
          https://stage.pep-web.rocks/browse/PEPGRANTVS/volumes/1
   and 
          https://stage.pep-web.rocks/browse/AIM/volumes/20
  and 
         https://stage.pep-web.rocks/browse/NLP/volumes/14

Although the first and last examples here are not (currently) directly tied in to the interface buttons, they are nonetheless useful URL paths that could be linked by us in a document, help file, or other http link.  They are presented beautifully by the interface, just not consistently.

2) Note that when you go to these two examples using the URL, the left Browse navigation pane shows Journals in both cases.  

This may be a problem with our URL paths not holding enough information.  I haven't thought through this to know if there are negative implications, but if the path were 
    /browse/ {journals|books|videos} / {pepcode} / {volnbr}

Then it would be easy for the interface to know to restore the browse column to journals, books, videos when following this path.

**Comment by bakerac4** [comment]
@nrshapiro There is no graphic banner showing for those because nothing is returned for this call.

https://stage-api.pep-web.rocks/v2/Metadata/Journals/?sourcecode=PEPGRANTVS

That call is how we get the bannerURL from the server.

Regarding the items not showing up in the sidebar, I was using the way to load the results you mentioned before which was 
https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&limit=20&offset=0&smarttext=ADPSA.011.*&sort=bibliographic&synonyms=false

But that loads 0 items for those video items. So when should I be loading ADPSA.011.* and when should I be loading art_id:ADPSA.*.*

**Comment by nrshapiro** [comment]
@bakerac4 

1)

You are calling Metadata/Journals for a video.  The correct call for videos is:

https://stage-api.pep-web.rocks/v2/Metadata/Videos/?sourcecode=PEPGRANTVS

That's why it's not returning anything.

2) When I click your link:

https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&limit=20&offset=0&smarttext=ADPSA.011.*&sort=bibliographic&synonyms=false

I get 20 results, not 0.

**Comment by bakerac4** [comment]
@nrshapiro regarding item 2 - that is a working link (for a journal). But if you check out a video that doesn't work 

Request URL: https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&limit=20&offset=0&smarttext=PEPGRANTVS.001.*&sort=bibliographic&synonyms=false

You will get 0 items.

**Comment by nrshapiro** [comment]
@bakerac4 

Well that's an issue with smarttext not recognizing that PEPGRANTVS is a video source.  I'll look into that.

But it occurs to me that's not the best way to ask for this data.  Smarttext is really meant as an early AI engine to parse user input and decide what to display.  That will be changing as we progress the system, and there are sure to be tweaks to what it can (and should recognize).  While I don't see why we would change that, there is a better, more direct way.  I'm sorry if I didn't direct you to it before.  

When the parameters support specific queries, you should use those over smarttext, given the same interpretation.  There are both sourcecode and volume parameters for search...you can just use them directly, and there should not ever be a parsing or recognition issue.

https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&limit=20&offset=0&sourcecode=PEPGRANTVS&sort=bibliographic&synonyms=false

Note, you can add the volume to get just that specific volume.

https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&limit=20&offset=0&sourcecode=PEPGRANTVS&volume=1&sort=bibliographic&synonyms=false

BTW, you should not be requesting abstracts for "sets" like these since it affects the statistics that PaDS collects.  I think we agreed the client would only ask for abstracts when each article was requested.

**Comment by bakerac4** [comment]
@nrshapiro I fixed the calls that I was making to use the other params. Everything is showing up well now. I did _not_ fix the banners because thats a larger issue and normal users wont even get to those pages. If you want to create a separate feature request for that your more than welcome to
