### ISSUE TITLE
Facet (Refine) order

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#21]
In the final we will get to rearrange the Refine section order and inclusion per the admin interface, but if you would please, I'd like to rearrange it by default here to make it the most useful/impressive for the preliminary reviews of search for this alpha release.

Obviously, only the ones with matches should show, but of the set, please show them in this order:

  Decade
  View Periods (another rename suggestion: View Count)
  Citation Periods (another rename suggestion: Citation Count)
  Article Type
  Source Type
  Source
  Glossary Groups
  Keywords

These are listed in an order which maps to our old search priority...from the most likely to be searched specifically to more experimental ones like Glossary Groups and Keywords.  Note I've left out Glossary Terms here because of the similarity (Glossary Groups is a level up, when our consolidated multiple glossaries use variations of a term...in a sense its a category, but most often it's the main term)

Also, be sure you are using the `art_kwds_str` version of keywords, so you get full strings instead of words as facets (only string fields facet with the full value).  You may have done that already, but I haven't seen any examples yet of multiword strings coming back, so I'm mentioning it.  Could be right though.
  
Thanks in advance.

**Comment by billdami** [comment]
@nrshapiro i noticed you left out "Language" (art_lang) from that list, was that intentional, or do you still want it to be part of this default list?

**Comment by billdami** [comment]
I just left in (as the first facet) for now, but let me know if you want to move/remove it.

Resolved via #20

**Comment by nrshapiro** [comment]
@billdami 

Thanks...that was inadvertent.

Decade
View Periods (another rename suggestion: View Count)
Citation Periods (another rename suggestion: Citation Count)
Language
Article Type
Source Type
Source
Glossary Groups
Keywords

**Comment by nrshapiro** [comment]
@billdami 

The order you have it is now is fine too
