### ISSUE TITLE
Reset and Logged Out for no reason

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#219]
This seems almost random, but it has happened to me several times already over the past two days as I've clicked around.

Suddenly, I am taken back to the home screen.  And as I click back to get back to where I was, I realize, I've been logged out!  This is literally 5 minutes or less after I successfully log in, and start testing by searching, reading, and following links.

Need to keep a close eye on this.  Happening to anyone else?

Client: 2021.01.06-5647
Server: 8.6.2/2021.0104.2.Alpha
DataSource: OPAS.AWSProd.2021-01-05
Browser: Chrome

**Comment by bakerac4** [comment]
Next time it happens, if you can look and see if any 401's have come back from the server recently that might do it. When we see a 401 we log you out and you will need to log in again

**Comment by bakerac4** [comment]
Most likely a dup of #232

**Comment by bakerac4** [comment]
Closing as a duplicate for now
