### ISSUE TITLE
Help Popups for Links in the Data Itself - with delay

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#226]
There are built in links in PEP-Web in the data itself, where it's not possible (or in good design) to put a (i) box next to the item, since it may be misleading.

Perhaps these could be done with a popup after delay when hovering.  In other words, when I hover over for 3 seconds, a popup shows the function of the link.

**Probably:**
Article Title - Click on the title to view the article in the source Table of Contents
Article Author - Click on the author name to view other articles by this author
Journal Banner (in article)- Click on the journal banner to see other volumes for this source

**Maybe:**
->  - after references 
![image](https://user-images.githubusercontent.com/4837554/104194068-d8d39980-53ee-11eb-9405-210c9c5a3013.png) - (could consider 3 second rule here instead of the extra (i) icon which already explains it.

**Probably Not (should not do these, but up for discussion):**
Glossary Link

**Comment by bakerac4** [comment]
@nrshapiro my concern with this is how do people know to hover over these items? And its even harder to accidentally find this behaviour on mobile, where we don't have hover capability.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

This is not something we need right away.  And it wasn't in the spec, so let's leave it for last in Beta 1, or even Release 1.  Just good to record the idea for now.  I will discuss it with the D & N, and see how keen they are on the idea, and if they want it included earlier.  They may feel help covers it sufficiently or will.  Though I'm a believer that very few people use help, especially to learn the intricacies of an app.

But Some thoughts: 

1) Think of these as tooltips, with a significant delay
2) Since this is meant as a learning and a "help" function, it should be able to be turned off in the help preferences.  Tooltips can be annoying once you know the functions.

Almost all of them highlight or underline when you cross them, indicating they are a link.  The only thing they don't do is tell you where the link goes!  So they don't know, but they get the idea when they cross them.

Probably:
- Article Title - Underlined when you cross it with the cursor
- Article Author - Underlined when you cross it with the cursor
- Journal Banner (in article)- Doesn't do anything when you cross it

Maybe:
- Glossary Entries (in articles) - Underlined when you cross it with the cursor
- Links after references (can explain the Related link, and even the regular link, though I think the latter is obvious.

**Comment by bakerac4** [comment]
I did the ones listed in `Probably `
