### ISSUE TITLE
Requirement 2.6.3.2.11 - text-alignment

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#228]
The requirement: _[Core] The user shall be able to select whether the text is left-right justified or ragged._

This did not mean right-aligned, it meant "justified" like the images below.  The spec did not call for a user selected Centered or Right aligned text option.  I have no idea why anyone would want that applied to their journal articles (other than if the author forrmats part of the article that way, e.g., poems etc.)  

PEP-Easy:
![image](https://user-images.githubusercontent.com/4837554/104204494-58676580-53fb-11eb-9a54-2b80085543fe.png)

PEP-Web Release 7
![image](https://user-images.githubusercontent.com/4837554/104203700-71234b80-53fa-11eb-9535-e6d4aa48e876.png)

Note that I have set the alignment of the paragraphs in R7 easily by setting text-align of paragraphs to justify (just after the fact to demonstrate).  This is how PEP-Easy does it, so I'm not sure why the query last week said this would be too time-consuming to implement?

![image](https://user-images.githubusercontent.com/4837554/104205064-f65b3000-53fb-11eb-9c6f-cc2f8466ec02.png)

If it can be done like this, as PEP-Easy does, please do implement that option.  We don't need the other options (right and centered),

**Comment by billdami** [comment]
@nrshapiro this would not be time-consuming to implement, there was just some confusion on what options you actually wanted, so we were looking to confirm that in the initial implementation:

https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/pull/213#discussion_r553402360

**Comment by bakerac4** [comment]
To Bill's point - I don't think it would take long to do. We were just trying to clarify exactly what you wanted 😄 . But this issue did that for us. I'll try to have this in the next 007 deploy
