### ISSUE TITLE
Dead End on Logout

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#23]
I'm sure it's related to Oauth not being finished, but thought I should report this:

1.  Searching...working fine.  Speed seems good.
2.  I looked at the user menu...it said I was logged in (well because it offered me to log out, that was implied)
3.  So I logged out.  

Just sitting there spinning on forever.  Perhaps a failed call to PaDS without a timeout?  

Maybe, after a timeout,  you just go back to not logged in?  The server works without being logged in of course, so those right hand fields should be there.

![2020-09-03_14h42_38](https://user-images.githubusercontent.com/4837554/92154743-46920800-edf4-11ea-9c9e-9b48c2702f6a.png)

Also now unresponsive to me:  Typing in the SmartSearch box looks like this: 

![2020-09-03_14h51_46](https://user-images.githubusercontent.com/4837554/92155223-054e2800-edf5-11ea-9948-b75fdaf43124.png)

I was trying to refresh....and when I used Ctrl-F5, or maybe just for because of the time out, the screen cleared and it came back ["message":internal server error"]

Otherwise, looking very good.  I have more changes upcoming to the _Your search starts here_, but the only one for tomorrow that would be good is to fix the spelling error: taskes -> takes.  Not important though, just an easy fix.

**Comment by billdami** [comment]
@nrshapiro yeah we are aware of this issue, it is related to the build/deploy problems I mentioned in #24

**Comment by billdami** [comment]
@nrshapiro this issue with the broken homepage/search should now be fixed on the currently deployed stage build
