### ISSUE TITLE
Author Roles

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#237]
The author roles need to be implemented and separate the authors (this is primarily a books/videos thing, but plays a role in some articles).

Here's an article on GVPi PEP-Web:

![image](https://user-images.githubusercontent.com/4837554/104664987-9801ac00-569e-11eb-904e-455e855b125f.png)

Here's the XML:

![image](https://user-images.githubusercontent.com/4837554/104665251-eadb6380-569e-11eb-9648-82fe545a169e.png)

Here it is on the new PEP-Web:

![image](https://user-images.githubusercontent.com/4837554/104665168-ba93c500-569e-11eb-8ea4-c5f9c1309339.png)

Also as a side note: The ridiculous looking Table of Contents line below that is normally linked to the TOC which is on roman numeral Page 10.  I think this is just a manifestation of another reported bug where "r" and rx attributes are not always being honored as links, though this is a pgx link, so it should be obvious.

I note the error here on Forward by Wallerstein and have corrected the XML sources.  The role for that should have been "other" so the hard coded label "Forward by" was on it's own.

**Comment by nrshapiro** [comment]
@bakerac4 

Moving email discussion here so we have better documentation.  Here's some rules for the author presentation and popups.

1) In the author area, group like roles together, as done in PEP Web.
2) One popup per group, if you like, OR you present all in the same popup...group all the name/address/bio info neatly in the popup,  (The GVPi site isn't too "neat" in this, some better formatting would be welcomed.
3) If there are not affids for the authors, then there should be exactly zero or one set of affiliation data.  It effectively applies to all if done that way.  Or in the zero case, there is no affiliation data.
4) Section authors, via hauth, aren't defaulted to the aff data, unless it includes a matched affid.  
5) For books, like the example above, I am happy to fix the main or  TOC instance if it's not clear, as I have done today for the above book example.  That of course depends on having proper data, as we do for many but not all books.  I can't make such a blanket statement for journal articles--there are too many and we often don't get proper data for them.

![image](https://user-images.githubusercontent.com/4837554/105088727-4aa08880-5a6a-11eb-9ff2-436c7bc6810d.png)

**Comment by bakerac4** [comment]
@nrshapiro thank you for the clarification. Could I also get a list of all possible author roles?

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

From the PEPKBD3.DTD, the attributes being "code" are not "presentation ready", they are meant to be close to the presentable label though.  Note that we added Other as an option, and an attribute called other for the value.  Other is often used as well to cover "labels" of roles without requiring us to add each as an attribute (which was our initial idea/goal).   There are 91 cases of other currently used in the database.  With the Other choice, the label in attribute is often just what you should display as the role.

<!-- aut = Author - individual author name

     Used for article authors, and section authors.

     As of 2011, this is now also used underneath namex to allow coding of names of contributors
      on journal front matter pages.

     Attributes:

     role    =  Author Roles (attr of aut).  Most of these are intended for display.
                See rules in artauth comments.

                author                  - author, not default for attribute "technically",
                                          but semantically the default.  We will assume this.

                Other roles we've seen to indicate when they are listed as such.  This is expanding
                    as we use aut for other purposes, like the contributors lists.

                assisted-by             - listed as assisted by (e.g., in SE)
                coordinator             - not an author role, but you see this listed
                chaired-by              - typically used in panel discussion articles
                compiled-by             - as seen
                commentary-by           - For films, commentary
                director                - Added for video
                director-assistant      - Added for video
                deputy-editor
                editorial-assistant     - Editorial Assistant (e.g., in SE)
                editor-in-chief
                edited-by               - editor of book (typically).

                                        This used to be "editor", changed because it was being used incorrectly
                                            instead of nti to indicate when an author was also the editor of
                                            the journal

                                        A1v6 Common Error Problem:
                                          DO NOT USE AS EDITOR TITLE for ARTICLES, e.g., not
                                          for Editorials!  The nti tag can be used with content Editor for that.

                executive-producer      - for films
                intro                   - wrote intro to article or book
                in-collaboration        - in collaboration with (e.g., in SE)
                interviewer             - If the article or video is an interview
                interviewee             - If the article or video is an interview
                issue-editor            - author of the article, but also the issue editor
                moderator               - a moderator of a session, not considered an author
                narrated-by             - For films, narrator
                panelist                - member of a panel from a session (usually from an article that's
                                            been "divided" by speaker.
                preface                 - wrote preface to article or book
                presenter               - For films, similar to panelist, but when there isn't a "panel" per se.
                produced-by             - The video producer, used for videos only
                published-by            - The publisher, used for videos only (though if needed, can be used otherwise)
                reporter                - the role for an author of a panel or meeting report
                series-editor           - For a book, the series editor can be listed (and set to display=false)
                translator              - did the translation for the book
                transcribed-by          - if it says transcribed by
                under-supervision-of    - not a real author, but sometimes you see this listed

     alias   =  The nlast name is a group or role name rather than an individual, e.g.,
                     Editor, Boston Change Process Study Group)
                First name is then optional (leave blank)

     listed  =  "true" if the author is formally an author of the article, that is, they are listed
                 as an author in the bibliographic form of the artinfo.  Even if listed is false, they
                 will be listed on the front of the article.  Just not included as a formal author
                 in the bibliographic form.  For example, a translator might be on the front of the
                 article, but not supposed to be an author of the article when cited, so listed for
                 the translator would be false.

     style   =   This is a flag that suggests the style by which the authors are listed, in groups by
                 function (block1 and block2) or in a simple list, "inline"

     asis    =   For PEP Use only.  If the role is unusual, we
                  check it.  If we decision to leave it "as is" we mark attribute asis = "true"


    NOTES:
        The role "editor" was removed a few years back because it was confusing.

        The author of an editorial, even though she's the editor, is
           the "author".  That's why "editor" was changed to "edited-by", to indicate this
           person edited the book or article, which was the original intent of the role.

<!ATTLIST aut
               role         (author
                            | additional-cinematography-by
                            | assisted-by
                            | coordinator
                            | chaired-by
                            | cinematography-by
                            | compiled-by
                            | commentary-by
                            | director
                            | director-and-producer
                            | director-assistant
                            | deputy-editor
                            | editorial-assistant
                            | editor-in-chief
                            | edited-by
                            | excerpted-by
                            | executive-producer
                            | assistant-producer
                            | associate-producer
                            | in-collaboration
                            | interviewer
                            | interviewee
                            | intro
                            | issue-editor
                            | line-producer
                            | moderator
                            | narrated-by
                            | panelist
                            | preface
                            | presenter
                            | published-by
                            | produced-by
                            | reporter
                            | reviewer
                            | series-editor
                            | translator
                            | transcribed-by
                            | under-supervision-of
                            | other
                            )                                           "author"
               other        CDATA                                       #IMPLIED
               alias        (true | false)                              "false"
               listed       (true | false)                              "true"
               style        ( block1
                            | block2
                            | inline)                                   #IMPLIED
               asis         (true | false)                              "false"
               authindexid  CDATA                                       #IMPLIED
               affid        IDREF                                       #IMPLIED
               lang         %langs;                                     #IMPLIED

                                                                                                >


Here are the roles currently in the database:

      "art_author_role":[
        "author",100132,
        "reviewer",33480,
        "edited-by",1792,
        "translator",1506,
        "in-collaboration",278,
        "reporter",183,
        "interviewee",141,
        "moderator",111,
        "panelist",109,
        "other",91,
        "assisted-by",69,
        "produced-by",56,
        "issue-editor",47,
        "interviewer",32,
        "compiled-by",26,
        "director",18,
        "published-by",16,
        "presenter",14,
        "chaired-by",13,
        "intro",13,
        "commentary-by",9,
        "editorial-assistant",7,
        "executive-producer",7,
        "director-assistant",6,
        "series-editor",6,
        "additional-cinematography-by",5,
        "transcribed-by",5,
        "preface",3,
        "cinematography-by",2,
        "coordinator",2,
        "director-and-producer",2,
        "associate-producer",1,
        "line-producer",1,
        "narrated-by",1,
        "under-supervision-of",1]},

Videos have the most variability in roles, so they are good choices to look at to see examples.  I'll try to get a list of samples in a subsequent post.
