### ISSUE TITLE
Banner Graphic Refresh Needed

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#238]
I noticed in your repository you have an assets folder with a copy of the banner and gui graphical elements. That's fine (in fact I had suggested it.) However, I've adjusted some of the names in the main storage location (S3) to handle where there were inconsistencies and your code was not referencing them as they were defined.  For example LU-AM:

![image](https://user-images.githubusercontent.com/4837554/104677639-c2139800-56b7-11eb-9b67-eae2440cb822.png)

Some of the original names had initial caps (B rather than b) or other case inconsistencies, and I've gone through and fixed these in the S3 repository.  But they have not been refreshed in yours, so they don't show up.

LU-AM
OPUS
REVAPA
GW
SE

Perhaps as part of the data build, the S3 pattern banner.*.gif should be copied to your assets folder?  That way, in the future, as we add journals, or on the rare occaision we need to adjust a banner, we get these copied over to the assets folder.  I am still in favor of keeping a copy that doesn't have to be loaded from S3 with each article as you've done, we just need a way to do an update without rebuilding the app.  Or please tell me the best way for me to do this, as we move forward in the future.

**Comment by bakerac4** [comment]
@nrshapiro I have fixed the first three, what did you change with GW and SE?

This is the unfortunate downside of keeping these client side (and I would still like to move them back to the API), however I understand your argument against that. If these truly don't change often (which is what I think we decided before) then I'm not sure I would worry about it and just make the manual adjustments when needed. If we _really_ want to automate the process - then I think I would talk to @lhorne-gavant about trying to load it from s3 and just throwing them into the public folder before the build happens as we are not doing fingerprinting on them anyways.

**Comment by nrshapiro** [comment]
@bakerac4 
The GIF for SE itself changed due to an error leaving the word Psychological out.

Other than that, the missing banners online had to do with inconsistent case in my GIFS, either "B" in banner instead of "b" or another letter.  Case doesn't matter in Windows, but they do in Unix based filesystems, of course.

**Comment by nrshapiro** [comment]
@bakerac4 

I am double checking these with a local copy of R7.

On the instance page, you are calling for the wrong name of GW logo:

https://stage-api.pep-web.rocks/v2/Documents/Image/bannerGWGWLogo.gif?client-id=2&client-session=

Note the duplicated GW.

Still checking the rest against R7.  Then I can send you an update.

**Comment by nrshapiro** [comment]
@bakerac4 

On the GW volume page you are referencing the GW logo in the wrong folder:
   http://localhost:4200/assets/images/bannerGWLogo.gif?client-id=2

Compared to a working banner in the subfolder publisher-logos:
   http://development.org:4200/assets/images/publisher-logos/bannerBAPLogo.gif?client-id=2

**Comment by nrshapiro** [comment]
@bakerac4 

Same for SE...

On the volume page, you aren't using the subfolder reference.

In the instance pages, you have SE doubled up, like GW:

https://stage-api.pep-web.rocks/v2/Documents/Image/bannerSESELogo.gif?client-id=2&client-session=

**Comment by nrshapiro** [comment]
@bakerac4 

Note the above is true for the glossary as well.

BUT BUT: the doubled up identifier ONLY OCCURS if you are not logged in in all of the above cases.  Otherwise, it is correct.

The folder issue is in place whether logged in or not, of course.
