### ISSUE TITLE
PEP Current Misleading Message

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#239]
I am logged in, and looking at a PEPCurrent document (embargoed because it's too new).  I see the following:

![image](https://user-images.githubusercontent.com/4837554/104742801-e6539100-5718-11eb-9c78-fbe5f1d872ad.png)

1) I am already logged in, so logging in won't do me any good.
2) In these cases, the second line about logging in should not be shown.

**Comment by bakerac4** [comment]
@nrshapiro are you sure you were logged in? This is what I see when Im logged in

![Screen Shot 2021-01-27 at 9 31 44 AM](https://user-images.githubusercontent.com/9952936/106005787-8ea31700-6082-11eb-9cb5-0bf83dbaa2a5.png)

**Comment by nrshapiro** [comment]
@bakerac4 

Are you logged in as test4?  That has access to current.  The ID I was logged in as does not.  Try one without PEPCurrent access.  2018 and above for that journal.
