### ISSUE TITLE
Facets Issue and enhancement...

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#24]
1) Are you sure you are using field `art_kwds_str `for the facets?  I searched for projective identification "everywhere".  I don't see it in the keywords list.  That suggests you are faceting the text field  `art_kwds `instead of `art_kwds_str`.  When I do the search in Solr, the facet list includes a number of multi-word keywords (including one ugly one with spaces and a \n in it I'll have to fix.)

   Searching "loving memory"~25 in solr

   ```
     facet art_kwds_str:
        "conflict",2,
        "countertransference",2,
        "implicit relational\n                        knowing",2,
        "interpretation",2,
        "intuition",2,
        "loving self",2,
        "mutual parental love",2,
        "neuroscience",2,
        "absence",1,
        "addictive pleasure",1,
        "adult attachment interview",1,
        "affect regulation",1,
   ```

2) Add field `authors` to the facet list.  This is not a rush, but if easy to add, I think it would be great to have soon.  This was not included in the specified list for facets...but part of my trying to make refine as useful as possible.  

   So the list, in order

   1) Decade
   2) View Periods (another rename suggestion: View Count)
   3) Citation Periods (another rename suggestion: Citation Count)
   4) Author (field `authors`)
   5) Language
   6) Article Type
   7) Source Type
   8) Source
   9) Glossary Groups
   10) Keywords (field `art_kwds_str`)

Top 15 results for  facet authors in Solr for search loving memory"~25:

```
    "Stolorow, Robert D.",5,
        "Auerhahn, Nanette C.",3,
        "Frosh, Stephen",3,
        "Natterson, Joseph",3,
        "Caruth, Elaine G.",2,
        "Freud, Sigmund",2,
        "Harris, Martha",2,
        "Krystal, Henry",2,
        "Laub, Dori",2,
        "Levine, Howard B.",2,
        "Abbass, Allan",1,
        "Alston, Edwin F.",1,
        "Alvarez, Anne",1,
        "Astor, James",1,
        "Bach, Sheldon",1,
```

**Comment by billdami** [comment]
@nrshapiro I did switch the Keywords facet to use `art_kwds_str` in one of the most recent pushes, that I believe that might not be deployed atm (we've been having some deploy/build issues today). 

However, the best way you can test/verify this stuff that I would recommend, is when running searches from the app, have Chrome's Dev Tools open on the Network tab, filtered to "XHR". In there, you'll see all search query requests as you interact with the form, and can expand the requests to see all the individual query params and values we are sending.

**Comment by billdami** [comment]
@nrshapiro Can confirm that the search is now correctly using the `art_kwds_str` facet on the currently deployed stage build. Doing a search on "loving memory" appears to return the same art_kwds_str values/counts that you have above.

**Comment by nrshapiro** [comment]
confirmed in 4208...(sorry for the delay in closing).
