### ISSUE TITLE
Open with SessionId

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#245]
@adistasio I can can't the  client to open with the session id I pass in the query string.  I thought this has been working a few days ago but now I am not so sure. For example this URL:
https://stage.pep-web.rocks/?SessionId=a17381bd-fdf4-417c-96f6-818a4d353e2b 
The client appears to just do an IP call to get a new session, or if there is a session in a cookie it uses that.

**Comment by bakerac4** [comment]
@jwoosnam while its impossible for me to check on stage, I can confirm that for dev (which still uses stage API endpoints) we are making an IP request with the passed in session. Just confirm that is what your expecting still?

**Comment by jwoosnam** [comment]
@bakerac4  Yes that could work, but I see no evidence of an IP call with the passed in session.
https://stage.pep-web.rocks/?SessionId=4e92418b-44c5-4a38-959f-b62b5f240bb5
When I try the link above it just opens your client in the normal way. In my logs I see the IP call, but either for no session or a session that was in a cookie.

**Comment by bakerac4** [comment]
@jwoosnam can you try it with a lower case `s` - we are looking for `sessionId`

**Comment by jwoosnam** [comment]
@bakerac4 Thanks that has worked!!
