### ISSUE TITLE
Favorites and Read Later Buttons Interacting

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#249]
On stage Client: 2021.01.18-5793

1) Do a search...
2) Select some favorites
3) Select a read later

Favorites go away.  Read later goes away when you select the next favorite.

Happens in document mode as well.

https://user-images.githubusercontent.com/4837554/105528118-904f9200-5cb2-11eb-9e09-5fe1027a0216.mp4

**Comment by bakerac4** [comment]
@nrshapiro this seems to be from an API/pads issue. 

Im sending a `ClientSettings` payload with favorites attached after the button is clicked. And its returning me an empty array. So it looks like the users endpoint is not correctly saving the favorites/readlater items

**Comment by jwoosnam** [comment]
@adistasio @nrshapiro Settings were not being saved in PaDS.  This has now been resolved.
