### ISSUE TITLE
Incorrectly Labeled as Logged In Via IP

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#257]
@billdami @adistasio 
For Info: @nrshapiro 
Sometimes the client is marking the session as logged in via IP when it isn't. It is hard to pin down what is causing this as it seems to happen in different circumstances. One instance I have just experienced is is opening with a logged on session for user:Test7:
https://stage.pep-web.rocks/?sessionId=43cfd03f-5dde-4428-9d99-42d15e6b6a52

The client opens with the correct user but it is saying logged in via IP which means you can't logoff, without clearing cookies.  The info returned by the PaDS endpoints for user and IP is correct and does not mention Logged on via IP.
<img width="302" alt="Screenshot 2021-01-27 at 16 50 00" src="https://user-images.githubusercontent.com/70103034/106025093-58848800-60c0-11eb-8840-64dc7222f596.png">
<img width="507" alt="Screenshot 2021-01-27 at 16 50 28" src="https://user-images.githubusercontent.com/70103034/106025124-5cb0a580-60c0-11eb-8209-da6e765fe77e.png">

**Comment by bakerac4** [comment]
The specific instance in this bug will be fixed when we do the revamp of the IP auth to handle log in and log out

**Comment by jwoosnam** [comment]
@adistasio 
Hi Alan, Do you have a timescale for this as it is effectively stopping the auto integration between PaDS and the client?
(@nrshapiro For info.)

**Comment by adistasio** [comment]
@jwoosnam This is currently in development.
