### ISSUE TITLE
Conjoined Words in the Glossary Cloud list

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#259]
@adistasio @bakerac4 

The glossary infocard cloud often shows conjoined words, which are not in the glossary.

The problem was traced back to a [solr bug](https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server/issues/83).  Not sure we can do anything about it.  Open for now. 

Note that the client does not currently do anything with the document get glossary endpoint returns an error.  Not sure if that's better or providing an error dialog, which requires the user to act.  It might be best if the client showed it in one of those transitory messages you see when you log in, so the error is acknowledged, but it requires no effort on the user to dismiss.

Thoughts?

**Comment by bakerac4** [comment]
@nrshapiro I would agree, we should show feedback if there is an error. I can take care of that

**Comment by nrshapiro** [comment]
@bakerac4 

I found a bug in the loading code for the glossary_term_groups.   It's fixed, but requires the database to be reloaded, which I'm working on but having build problems on AWS.  Anyway, there should not be any more conjoined words not already in the glossary (yes, there are times where they conjoin words).  

In any case, there should be an error message for any glossary entry that doesn't work.  Close this whenever you've done that.
