### ISSUE TITLE
Documents not returned when logged in...

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#27]
If I log in, and I have a legit server-based login, the front-end is not letting me read.

I just tested login and read on stage-api.pep-web.rocks, and that works fine.  I can see the full document at the endpoint:

https://stage-api.pep-web.rocks/docs#/Documents/documents_document_fetch_v2_Documents_Document__documentID___get

But while it lets me login on https://stage.pep-web.rocks

I can't read at: https://stage.pep-web.rocks/read/IMAGO.018.0042A?q=imago.018.0042a

**Comment by bakerac4** [comment]
Fixed by #9
