### ISSUE TITLE
Hits in Context not highlighting full match in some cases

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#273]
This is likely to be a Solr issue, but I wanted to record it here in case it's a markup/xml/xslt issue.  And also I wanted to make sure the UI issue is recorded where people would look.

I searched for the phrase "death in the family", in quotes (smartsearch).

What was interesting, was that the hit list within the bibliographical result listings were perfect, but when you went to a document, the phrase was not marked up, just the first word, "death".  **BUT** the entire phrase was marked as a hit for ANY DOCUMENT which had multiple hits.  Only the ones with a single match (and it was matching the phrase), had only the first word, death, highlighted.

Document sample with one hit:

![image](https://user-images.githubusercontent.com/4837554/107064618-b80e2200-67a9-11eb-8853-9f50a805a2bf.png)

Document with multiple hits:

![image](https://user-images.githubusercontent.com/4837554/107064533-9c0a8080-67a9-11eb-8bdb-34e189899276.png)

**Comment by bakerac4** [comment]
@nrshapiro this is not a SOLR issue.

It seems to be an issue when there is a glossary term inside a search hit. You can see the issue with multiple search terms in the document by going here /search/document/PSC.034.0547A?preview=PSC.034.0547A&q="death%20in%20the%20family"

**Comment by bakerac4** [comment]
@nrshapiro is it possible for you to adjust the xml you send back to fix this?
```
<impx type="TERM2" rx="ZBK.069.0001d.YN0013300865870" grpname="DEATH">#@@@death</impx> in the family@@@#```

Thats what I currently get back. Would it be possible for you to wrap the search term around the tag like so?

```#@@@<impx type="TERM2" rx="ZBK.069.0001d.YN0013300865870" grpname="DEATH">death</impx> in the family@@@#```

**Comment by nrshapiro** [comment]
@bakerac4 - There's no easy fix for this.  Remember, the XML is stored in Solr.  Solr is marking hits without having any rules regarding the content or markup of the field.  

Its a Solr problem because Solr doesn't care about the markup and where it's placing the hit boundaries.

The only real solution I see to this is not to change the hit boundaries to HTML or XML tags at all (which is the same reason I tell Solr to use #@@@, and @@@#) and somehow use them to trigger the bold/highlighting in the display.  What if you, instead of changing them to HTML tags, changed them to similar type MARKERS in the text, but more user friendly graphics?  Then it wouldn't interfere with the XML/HTML parsing at all?  You couldn't format the text using HTML, but it would still clearly show them.  E.g., something graphical along the lines of 

blah blah blah [[death in the family]] blah blah blah 

but something graphical (and SALIENT).  Technically, you could easily use a graphical version of 

<<< hit phrase >>>

And use the arrows to go between the hits as well, where the final right one just isn't hyperlinked (and the first left one also).
