### ISSUE TITLE
Missing Keyboard Accelerators / Shortcuts Options for Accessibility Standards (and expert users)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#277]
Two categories of keyboard shortcuts we should avoid: 
- native browser and operation system shortcuts that affect the browser behavior (not the contents of the web page), like Ctrl+N, Ctrl+O, Ctrl+S, Ctrl+P, Ctrl+W, etc.
- native browser shortcuts for the page content, like Ctrl+C, Ctrl+Z, Ctrl+F, spacebar etc.
- Standard keys, Tab, Esc, etc.

Per the accessibility issue, this is a worksheet/starting list for what keyboard accelerators/shortcuts are needed.  

Combo-key shortcuts (mainly power users):

| Function  | Keyboard shortcut |
| ------------- | ------------- |
| Deselect / Dismiss / Etc  | Esc  |
| Next Below in list  | Down arrow  |
| Next Above in list    |          Up arrow    |
| Read                        |          Ctrl-R   |
| Search                     |          Ctrl-E   |
| Browse                    |          Ctrl-B   |
| Home                     |          Ctrl-H   |

Deselect above is particularly important.  We use the Esc key for that, it's pretty much standard for that (e.g., dismiss dialog).
After pressing _Deselect_, two key sequence (not combo) shortcuts should work,  e.g., to search type Esc then Q then S  This is easiest for people with disabilities who can't easily push key combinations, and easy to program a keyboard app to automate these operations for other purposes.  And this gives us a lot of great mnemonic choices for keys.

The specific keys should also be customizable in the interactive admin module or an easy to edit settings file.  At some point, we can add similar customization to user preferences, but that can be done down the road.

**Quick Access Group, Q followed by:**

| Function                 | Q followed by  |
| --------------------- | ------------- |
| Read                        |    R           | 
| Search                     |      S           | 
| Clear Search            |    C           | 
| Browse                    |     B           | 
| Home                      |    H           | 
| User Menu              |    U           | 
| Preferences dialog  |    P           | 
| Login                      |    L           | 
| Logout                   |    L O         | 

**Navigation Group, N followed by:**

| Navigation               | N followed by  |
| --------------------- | ------------- |
| Next Article              |        N      | 
| Previous Article          |      P        | 
| Next Hit                  |         H N    | 
| Previous Hit              |       H P      | 
| Next Article, First Hit   |    A N        | 
| Prev Article, First Hit   |    A P        | 

**UI Hide Group, H followed by**

| Hide /Show Toggle                 | H followed by  |
| --------------------- | ------------- |
| Sidebars (both)    | B               | 
| Left Sidebar       | L              | 
| Right Sidebar      |  R              | 
| Hits in context          |  H  |
| Glossary Highlighting     |  G  |

Of course, this is a starting list.  With the two key method, it's easy to extend as we have quite a few shortcut choices!

**Comment by adistasio** [comment]
@nrshapiro To clarify, for items in quick access, navigation and ui hide it's expected the user would hit "esc - q - s" sequentially to trigger the action correct? Not have to hold down "esc" and then hit q then s. Or is Esc only needed when you need to deselect something first, e.g. an active modal or input. If it's the latter here I wouldn't recommend have "q - s" be the trigger as that can lead to a lot of confusing situations.

**Comment by nrshapiro** [comment]
The last three groups are all sequential keystrokes, not combinations.
   e.g., as it says: UI Hide Group, H **followed by** (not **at the same time as**)

The first group "Combo-key shortcuts (mainly power users):" is different.  We already have browser "combinations" (at the same time), and I just added a few more.  Down arrow, up-arrow are already built in.  But for those of us who can use two fingers, I took the most common ops and added power user multi-key shortcuts:

Tested in Opera and Edge:
Read | Ctrl-R - not available, refreshes.
Search | Ctrl-E - Not available, takes you to the url bar
Browse | Ctrl-B - seems to be available
Home | Ctrl-H  - this one won't work--it's history 

So bag those all multi-key combos...not worth it (unless you know some that are both mnemonic and will work)

Now for the bottom three lists, I didn't mean to **have to** press Esc first, if nothing is already selected.  But pressing Esc first makes sure nothing is.  So you could use Esc followed by the sequences of keys in the last tables and it would work fine.  **It would be a good habit.**

The question is should they have to?  If you know nothing where you can actually type is selected, you should be able to get away with just pressing the keys.  For example, if the sidebars are missing, why not let them just press H, B to show them again?  Yes, they can still press Esc,H,B.  

On Youtube:

Esc-J goes back 10 seconds
Esc-L goes forward
Esc-K starts and stops (pauses) video
Esc-T hides the sidebar list (toggles actually)

But Esc gets you out of the search field, if you're in it.  If you're not:

J goes back 10 seconds
L goes forward
K starts and stops (pauses) video
T hides the sidebar list (toggles actually)

And those are only one key commands.

But if it's easier to implement looking for Escape first, I don't have a "real" problem with "requiring" escape first (shades of Emacs).  I just would prefer to not have to force users when it's not necessary.  but what harm could they do on PEP-Web if they forget they are in a field?  I personally think the benefits outweigh the risks.

**Comment by bakerac4** [comment]
@nrshapiro this is complete with the exception of `next article/previous article`.  Im not sure if I have the information to do that. Right now I set it up to use the `sourceNext` and `sourcePrevious` but that doesn't seem to follow the search results.

**Comment by bakerac4** [comment]
Other thing to note is that I changed `UI Hide Group, H followed by` to be `t` for toggle

**Comment by nrshapiro** [comment]
I found the keys from the quick access group, but the keys from the last two groups didn't work for me.  I tried with Esc first and without,  Unfortunately, to me the one that hides or shows the sidebars was one of the most important.

**Comment by bakerac4** [comment]
@nrshapiro Just wanted to make sure you saw the comment directly above yours. https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/277#issuecomment-809558739

I changed it to T for toggle

**Comment by nrshapiro** [comment]
@bakerac4 

Yes, I saw that and tried it but it didn't work.

Esc  H  T in sequence does nothing, at least in Opera (just retested) and I also tried Chrome when I originally tested, both on PC

**Comment by bakerac4** [comment]
@nrshapiro H is not used. So it would be `T B` and `T L` etc

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

> I changed it to T for toggle

LOL, changed what...as I'm sure you guessed, I assumed you changed "B" to "T" not the prefix for the whole sequence.  No problem, and it's fine for a choice, but next time, save me some time and be a bit more specific as to "it"?  No worries.  Especially after read below--I did the same thing!

I tried it and it works.  In fact it's great.  I like the use of T rather than H.

I also got the middle set to work, not sure why it didn't before.  But I may not have been testing it much since I couldn't get the H group to work.

Now here's something where I wasn't very clear and thus isn't implemented as I expected--since my design context is our existing system: after a search next and previous article means the next article in the results list, not the next article in the issue.  Basically, it should be the next article you see in the list on your left, which will be the list of hits for searching, or the list of articles in the book or journal issue as appropriate for browse mode.  In our old system, next and previous articles are buttons around the next and previous hit.  But in this system, we opted to hold off on those (maybe permanently) because we have a results list to the left of the article you're reading.

**Comment by bakerac4** [comment]
@nrshapiro yea I mentioned that above https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/277#issuecomment-809305072

I don't think I have the data to do that currently. I think you would need to send down the next/previous item in the list. This is due to the infinite scroll (we might not have the next item in the web app because the user has not scrolled far enough)

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

If they are about to scroll the set beyond what you've already requested, why wouldn't you trigger the same event via the next button?

**Comment by bakerac4** [comment]
@nrshapiro I just wanted to point out the following.

Lets say you search for `test`. You will get 12,594 results. Now you decide to scroll down to item 350 (or 250 or 129 etc). You grab that link and save it or send it to someone else. 

If you refresh the page, or the person you sent it to loads that page you will be looking at document 350 in the list, but we only have loaded the first 20 in the left sidebar. Not only are document 351 and 349 NOT in the list, we would need to make 18 calls to find them at 20 items per piece. 

So you don't really have the correct information to do this unless you are the one that did the search and you do not refresh your page at all.

**Comment by nrshapiro** [comment]
> @nrshapiro I just wanted to point out the following.
> 
> Lets say you search for `test`. You will get 12,594 results. Now you decide to scroll down to item 350 (or 250 or 129 etc). You grab that link and save it or send it to someone else.
> 
> If you refresh the page, or the person you sent it to loads that page you will be looking at document 350 in the list, but we only have loaded the first 20 in the left sidebar. Not only are document 351 and 349 NOT in the list, we would need to make 18 calls to find them at 20 items per piece.
> 
> So you don't really have the correct information to do this unless you are the one that did the search and you do not refresh your page at all.

@bakerac4 @adistasio 

Well the second paragraph basically says there's a bug to begin with which has nothing to do with the keyboard operation.  To fix that, the URL the user sends just needs to have enough information to repeat the query.  Now of course, the target document may not be in the same position in the set, if you're not doing the exact same query, which would be in a particular sort order, and bringing back that portion of the search results.  Technically speaking, that's what it should do when you send someone the URL based on a search.  

If instead you are sending only a document to view, then of course, the set on the left will be different.  That's ok.

Next document still works correctly, since it's defined as the next document in the list (set) on the left.

Said another way, as long as Next Document takes you to the next item in the list, it's working as prescribed.  Whether the list is the same, correct or not, is a different issue.

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 

Also, regarding the middle paragraph discussion that it's just loading the first 20 results: don't forget the server lets you jump anywhere in a results list, using offset.  So why would you only load the first 20 from the list if the document is #350.  Why not load 20 documents beginning at 340?

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 

FYI You may have already realized this, but I just loaded  release/beta2  882fcf76 to stage, and it's no longer populating the left pane with the issue if you browse to an issue.  I'm going to try an earlier version again.

**Comment by bakerac4** [comment]
@nrshapiro can you provide steps as to which one specifically is not working?

**Comment by nrshapiro** [comment]
I've put that build (Client: 2021.04.09-7226)  back on Stage so you can see for yourself.

Here's a sequence that shows it.  Browse

<img width="921" alt="2021-04-12_09h53_43" src="https://user-images.githubusercontent.com/4837554/114405878-158d6900-9b75-11eb-8371-2b1b678486ef.png">

<img width="921" alt="2021-04-12_09h53_49" src="https://user-images.githubusercontent.com/4837554/114405886-17efc300-9b75-11eb-96e6-0a14e752ddb3.png">

<img width="921" alt="2021-04-12_09h53_55" src="https://user-images.githubusercontent.com/4837554/114405910-1c1be080-9b75-11eb-9583-f9127591d834.png">

In previous versions, you would see the issue's contents on the left pane.  Here I went to the exact same URL on production, which is running Client: 2021.04.07-7195

![image](https://user-images.githubusercontent.com/4837554/114406315-6f8e2e80-9b75-11eb-8a44-9456173cea3f.png)

**Comment by bakerac4** [comment]
@nrshapiro looking at the different between a working and nonworking environment it seems to be the paranthesis that were added in another story.

```
abstract: false
formatrequested: XML
limit: 20
offset: 0
sort: bibliographic
sourcecode: (CPS)
synonyms: false
volume: (28)
```

https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/410

> If you do that, then I may also find a query if they enter a boolean OR in the authors field: (Tuckett OR Fonagy) AND (fonagy, peter OR tuckett, david) produces 140 matches vs Tuckett OR Fonagy AND (fonagy, peter OR tuckett, david) produces 200 matches.

So I just added parenthesis to any query fields. 

Shouldn't the server allow that?

**Comment by nrshapiro** [comment]
@bakerac4 Can you give me an example of what you are submitting to the server, and in which fields?

**Comment by bakerac4** [comment]
@nrshapiro I did above. 

https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=false&formatrequested=XML&limit=20&offset=0&sort=bibliographic&sourcecode=(CPS)&synonyms=false&volume=(28)

vs 

https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=false&formatrequested=XML&limit=20&offset=0&sort=bibliographic&sourcecode=CPS&synonyms=false&volume=28

**Comment by nrshapiro** [comment]
@bakerac4 

The parens need to be encoded.  If you submit that same query from the interactive server documentation interface, the URL it generates is 

https://api.pep-web.rocks/v2/Database/Search/?synonyms=false&volume=%2828%29&viewperiod=4&abstract=false&formatrequested=HTML&similarcount=0&highlightlimit=5&facetmincount=1&facetlimit=15&facetoffset=0&sort=score%20desc&limit=15&offset=0

which works fine.

**Comment by bakerac4** [comment]
@nrshapiro when originally working on that feature I did NOT have to encode the parens? 

i.e. https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&author=(Tuckett+OR+Fonagy)&facetfields=art_year_int%2Cart_views_last12mos%2Cart_cited_5%2Cart_authors%2Cart_lang%2Cart_type%2Cart_sourcetype%2Cart_sourcetitleabbr%2Cglossary_group_terms%2Cart_kwds_str&facetlimit=15&facetmincount=1&formatrequested=XML&highlightlimit=1&limit=20&offset=20&sort=bibliographic&synonyms=false

Works. I'd prefer to keep that consistent if possible

**Comment by nrshapiro** [comment]
@bakerac4 

> @nrshapiro when originally working on that feature I did NOT have to encode the parens?
> 
> i.e. https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&author=(Tuckett+OR+Fonagy)&facetfields=art_year_int%2Cart_views_last12mos%2Cart_cited_5%2Cart_authors%2Cart_lang%2Cart_type%2Cart_sourcetype%2Cart_sourcetitleabbr%2Cglossary_group_terms%2Cart_kwds_str&facetlimit=15&facetmincount=1&formatrequested=XML&highlightlimit=1&limit=20&offset=20&sort=bibliographic&synonyms=false
> 
> Works. I'd prefer to keep that consistent if possible

Yes, the problem was the (CPS), not the (28).  I missed that there was a source code there when I was interpreting your examples.  
If you take the parens off of the CPS it works.

I'm looking into the source field.  It's not a simple boolean field right now, it's somewhat rigidly interpreted since it accepts a source code, a list of source codes, or even a partial journal name and wildcard.  Perhaps in trying to allow more it is trying to be too flexible, making it harder to parse.  I'm looking into that.

**Comment by bakerac4** [comment]
@nrshapiro I believe we just send it booleans. `(CPS OR IJP)`. I don't think we send it lists like that

**Comment by nrshapiro** [comment]
@bakerac4  Ok, a few false leads in testing this morning, sorry.  

The actual problem stemmed from the fact that that field tried to be flexible and allow source_names as well, with wildcards.  It was not expecting a paren without a boolean OR, and so when (CPS) didn't match any PEP source_codes, it tried to search for it as a  source_name, in a different Solr field.  

As of today's build, I've removed that "corrective" functionality completely.  Now it only accepts a boolean string, like CPS OR IJP, or a list like CPS, IJP etc.  

A side note: While you can surround it with parens, individual parameters like that which map to a single Solr field are always already surrounded by parens when converted to solr syntax.  For example, those fields are already converted to:

art_sourcecode:(CPS) && art_vol:(28)

Adding a paren around the complete parameter you submit simply doubles the parens unnecessarily:

art_sourcecode:((CPS)) && art_vol:((28))

That works though anyway, so I guess there's no harm in those cases

This does not apply exactly as stated to the fulltext1 and smartext parameters, which have a lot of processing done to them because they accept multiple syntaxes.  I'll have to go back to the original bug report that lead to you doing that to see where I wasn't clear about the need for certain parentheses.  But I can't do that today.

With the API update on stage, the functionality is working again.  LOL I was going to close this issue, but we were on a complete tangent, and the last set of communications has nothing to do with the issue itself.  My fault for bringing it up here.

**Comment by bakerac4** [comment]
No problem. I believe I just fixed this also so Im going to close this as well.
