### ISSUE TITLE
Cookie used in preference to query string

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#279]
@adistasio 
If the client is opened with the session ID passed in the query string, the client will use any session stored in a cookie instead of using the past in session.
The session ID in the query string must take priority.

**Comment by bakerac4** [comment]
@jwoosnam could I get a working sessionId to use so I can try it out?

**Comment by jwoosnam** [comment]
@bakerac4 
This session is logged on as test7:
0bf22734-37c8-4ed2-95a9-793c3a8c3c9f

**Comment by bakerac4** [comment]
@jwoosnam Im seeing an issue with pads.

Im making this call - https://stage-pads.pep-web.rocks/PEPSecure/api/v1/Authenticate/ip?SessionId=0bf22734-37c8-4ed2-95a9-793c3a8c3c9f

and getting this response from IP auth 
```{"SessionId":"26e94e6a-c12d-4572-9929-b9b47c13525a","SessionExpires":604799,"IsValidUserName":false,"IsValidLogon":false,"HasSubscription":false,"ReasonId":200,"ReasonStr":""}```

**Comment by jwoosnam** [comment]
@bakerac4 
This is not an issue on PaDS, the session being passed is logged off so PaDS returns a new session.

This issue I am getting is that if the client is using a session, ending bb77, as in the example below, but it is opened with a new valid session in the query string, ending 20ed, then the client does not switch to the passed in session:
<img width="797" alt="Screenshot 2021-02-10 at 10 48 49" src="https://user-images.githubusercontent.com/70103034/107501932-f0d63e80-6b8f-11eb-9430-9f4217efe34a.png">

We need to resolve this so if there is still confusion perhaps we could set up a call before 11:30EST.

Thanks

James

**Comment by bakerac4** [comment]
@jwoosnam Sorry, I was not very clear. There is an issue on my side as you described - however I can't fix it/test it without the ip auth call working and I was using the sessionId you gave me above and it was failing. Is there a new sessionId I can use if that one expired or something?

**Comment by jwoosnam** [comment]
@bakerac4  I thought you had the details for the test users. You should be able to logon as one of the test users to create the session. You can then get the session ID from your about box, and then use that to open your client in a different browser.

I will email you the password in case you don't have it.

**Comment by bakerac4** [comment]
@jwoosnam I see. I thought that these session url params were special sessions that you would be creating manually to give to users. If thats the case, I can create my own. Thanks!
