### ISSUE TITLE
2.3.1.2. #5k. Fielded search controls help tooltip content

### ISSUE THREAD

**Issue by billdami** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#28]
@nrshapiro we need some initial content for this requirement:
> k. [Core]​ More descriptive help shall be available via hover over an icon next to the field

For the following fields:
1. Everywhere
2. Author
3. Title
4. Dreams
5. Quotes
6. References
7. Dialogs
8. Article
9. Year

Note that this content will be displayed in a simple tooltip, so it should be as short and concise as possible. For example, I currently have this for the "Year" field tooltip:
> Find documents published on or before/after a year, or within a range of years (e.g, "1999", "1999-2010", ">1999", "<1999")

(Note also that we are storing this content in the admin configs, so that we can later expose it for easy editing via the Admin UI, if needed.)

**Comment by nrshapiro** [comment]
@billdami 

0. SmartSearch - This field performs a SmartsSearch, a search based on the semantics of what you enter.  It can recognize an article citation (author and year) or a reference in APA standard form, a DOI, a year or volume and page number, or a PEP Article ID (Locator).  Or if you enter words or phrases, it performs a words within paragraph or phrase search anywhere in the document, other than in abstracts and references (equivalent to an Article search).
1. Everywhere - Search for words in the same paragraph, or phrases (surround words by quotes) of anywhere in the document, including abstracts and references. Surround phrases with quotes.
2. Author - Search author names (e.g., Lastname, or Lastname, Firstname).  Use * to search partial names
3. Title - Search for words or phrases within document titles.   Surround phrases with quotes.
4. Dreams - Search for words in the same paragraph, or phrases, in areas of documents which are descriptions of dreams.  Surround phrases with quotes.
5. Quotes - Search for words in the same paragraph, or phrases, in areas of documents which are quoted passages.  Surround phrases with quotes.
6. References - Search for words in the same reference, or phrases, in the reference section (bibliographies) of documents.  Surround phrases with quotes.
7. Dialogs - Search for words in the same paragraph, or phrases, in areas of documents which are dialogs between people.  Surround phrases with quotes.
8. Article - Search for words in the same paragraph, or phrases, anywhere in the document EXCEPT in abstracts and references.  Surround phrases with quotes.
9. Year - Find documents published on or before/after a year, or within a range of years (e.g, "1999", "1999-2010", ">1999", "<1999")


> (Note also that we are storing this content in the admin configs, so that we can later expose it for easy editing via the Admin UI, if needed.)

Note that these should be localization-ready, if someone chooses a different APP language.

**Comment by billdami** [comment]
Thanks @nrshapiro. 

> Note that these should be localization-ready, if someone chooses a different APP language.
Yeah, these are being stored in admin configs, which we currently have structured so that any user-visible text put in them will automatically be localization-ready once the Admin UI is in place.

And all other hardcoded user-visible strings in the app itself are localization-ready by default.
