### ISSUE TITLE
SessionId in "User" Authenticate call

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#285]
@billdami @adistasio 
If I log in via IP and then trigger a secondary logon, by trying to change a preference, and then clicking "Sign In".  If I fill in a valid username and password (non subscribed user) and click login, the call to pads does not have the session ID in the query string therefore pads logs in the user as a non-authenticated user.

If I try and log in from a non-IP authenticated session then the session ID is correctly passed to pads.
FYI: @nrshapiro

**Comment by jwoosnam** [comment]
I think something similar is happening if I call the client with an IndividualIPAddress logged on session ID.  It appears that the client is doing an IP check because that gives a valid IP logon it is then ignoring the session Id passed in.

**Comment by bakerac4** [comment]
Fixed in master

**Comment by jwoosnam** [comment]
@bakerac4 Is this on stage?  If not then please close it when it gets to Stage.  There is no way for me to verify it until then.

**Comment by jwoosnam** [comment]
@bakerac4 Now working - thanks
