### ISSUE TITLE
Logon/Session suggestions

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#290]
These are for discussion at our next project meeting (I will keep adding until then)
- If IP Logged in - always show login button (The initial logon bar is good but this hides the top right logon info, so you have to cancel it to see it, and then you have to change preferences to see the logon button again)
- In "Man" menu instead of "Logged in via IP" always show the LoggegInMethod, or a user friendly translation, from user details, or if space is a problem then just show the LoggedInMethod in the user information dialogue.

I believe quite a few of these issues could be resolved if the client built, and re-built, the options in the "man" menu based on the LoggedInMethod returned in the user a call from pads.

**Comment by nrshapiro** [comment]
@jwoosnam James, I think this is done...I will close, but feel free to reopen if you disagree.
