### ISSUE TITLE
Conditional Display of Video Abstract (Preview) vs Full Video

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#295]
For videos with a separate preview/abstract video, it would be good to 

1) show the preview video along with the written abstract when the user is not logged in  (that could be done by alternating the video inclusion code using the XSL stylesheet/transform).  It may also be useful to show it when logged in as a link or smaller "abstract-ish" summary at the top of the document. (Rel. 1)
2) Be able to alternatively offer a preview in the Expert Pick of the day Graphic section (or possibly add a third section) (Rel.1.5)
3) For the Video Browse mode, optionally show the video preview under the bibliographic item (**Rel. 2, if at all**)

**Comment by nrshapiro** [comment]
@adistasio 

We discussed this the other day, but I later noted (remembered) that the previews are already linked in the artinfo, but we'll need to decide where to host them...can they run from S3 and be presented like any other graphic?  If not, we can host them at Wistia, which would make the presentation model the same.  Easy for me to set up either way.  I don't think we'll want to host from Facebook, but that's always still an option.

```
<artinfo arttype="VID" j="PEPTOPAUTHVS" preview="peptopauthvs.001.0032a.preview" vidcat="interviews">
        <artyear>2020</artyear>
        <artvol actual="1">1</artvol>
        <artiss>1</artiss>
        <artissinfo>
            <isstitle>Insights in Psychoanalysis</isstitle>
        </artissinfo>
        <artpgrg style="arabic">32</artpgrg>
        <arttitle>Giuseppe Civitarese on ‘“Caesura” as Bion’s Discourse on Method’ (IJP,
            2008)</arttitle>
        <artauth>
            <aut role="interviewee" listed="true">
                <nfirst>Giuseppe</nfirst>
                <nlast>Civitarese</nlast>
                <ndeg dgr="MD"/>
            </aut>
        </artauth>
        <artkwds>Descartes, Kant, doubt, caesura, unconscious field, reverie </artkwds>
    </artinfo>
<abs>
...
</abs>
```

**Comment by bakerac4** [comment]
Item 1 for beta 2. @nrshapiro needs to add preview into amazon bucket and give me address

**Comment by nrshapiro** [comment]
@bakerac4 

I spoke to David and Nadine today regarding our telecon, and we want captions.  That leaves two options.

Apparently, the HTML5 player can support captions, if we supply a VTT file and tracking code:
(reference: https://www.3playmedia.com/learn/how-to-guides/html5-video-captioning/)

<video  width="320" height="240">  
 
     <source type="video/mp4" src="/my_video_file.mp4" >   
     <track src="/captions_file.vtt" label="English" kind="captions" srclang="en-us" default >
     <track src="/French_captions_file.vtt" label="French" kind="subtitles" srclang="fr" >

</video>

So if we want to try that, I did create the S3 bucket: 

If we do it through wistia instead, I'd have to edit the XML to include the randomlike codes used to reference a Wistia video.  But that's not a big problem.

Still, if we can get the video previews with captions working from S3, that could be an advantage.  I don't have all the preview files yet, but I'll upload a sample or two, with VTT if you want to try.



Note to me: Many of the preview videos are being captioned automatically on Wistia rather than on 3Play.  But I have found a free site to convert from .SRT (all that Wistia provides) to VTT: https://www.happyscribe.com/subtitle-tools/subtitle-converter

**Comment by nrshapiro** [comment]
Note the change in the original issue above, from my call with DT: 

    3.  For the Video Browse mode, optionally show the video preview under the bibliographic item (Rel. 2, if at all)

**Comment by bakerac4** [comment]
@nrshapiro would it be possible for you to give me a `<videopreview>` element like you do the `<videoplayer>` so I don't have to do logic to figure out when and where to place the html video player in the xslt. It doesn't have to have anything inside of it, just an element that I can add a template for.

**Comment by nrshapiro** [comment]
I'm not sure I understand what you need....an empty tag where it's to be placed?  Why not just use the <body/> tag, since it will be empty when the user is not logged in or doesn't otherwise have access...and that's when the preview video should be shown.

Otherwise if I add a tag, I have to change the DTD which affects our keyboarders and our current system.  Not a terrible big deal, but I don't want to do it if it's not necessary.  (And as far as I recall, the server doesn't currently distinguish videos from other documents, so that's an issue as well.  Again, not insurmountable, just more code on the server side--and better to not if not "necessary".

**Comment by bakerac4** [comment]
Fixed the item for REL 1. Closing for now

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

I thought this was already in place, since closed, but apparently not.

I have about 20 video previews now set up on S3...some don't have .srt .vtt files but they all have the 30 second or so video preview and a jpg preview file.  It would be nice to have these showing rather than the big black blank video screen under the abstract when we go to Beta next week.

![image](https://user-images.githubusercontent.com/4837554/115752444-1938a100-a368-11eb-9dd0-3ee18f12e394.png)

The are all in s3s://s3.amazonaws.com/pep-web-video-previews:

![image](https://user-images.githubusercontent.com/4837554/115752874-8815fa00-a368-11eb-9164-3239d6aa5806.png)

**Comment by bakerac4** [comment]
@nrshapiro Im not sure how these got uppercased again, but when I was doing development I had @adistasio make everything lowercase. If you change the case they should work.

**Comment by nrshapiro** [comment]
Probably because that's our published naming standard!  The front part of the filename is the journal/video code which is usually an acronym, and thus  we've always capitalized them.  I have at least 200,000 XML files on my just system like that.  But that's fine.  I put a note in that folder that the files must be lower case, and my file manager can convert the lot of them in one click.  So we'll just do that.  

Thanks.

**Comment by bakerac4** [comment]
If thats the case @nrshapiro you would not have to do that if you sent the preview url back in that format. 

Currently its sent back as `preview="peptopauthvs.001.0009a.preview"`

**Comment by nrshapiro** [comment]
Great...as long as it will follow the case, rather than forcing it, I'm happy.
