### ISSUE TITLE
Identify User Initiated searches

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#297]
@adistasio 
For reporting I need to identify when a user has initiated a search, as opposed to the client doing a search for other purposes. This could be achieved by adding the parameter @user=true to the search query string.

**Comment by adistasio** [comment]
@jwoosnam @nrshapiro How should we handle the infinite scroll? If the user scrolls down the page we initiate another call to get more data. Should we send down user=true in these calls for more data even though the search params don't change?

**Comment by nrshapiro** [comment]
Since the stat doesn't care about the return data size (limit), I would say no, otherwise, the stat would be tilted for more searches with a smaller limit.  It should not depend on that.  So, it's just like getting a large binary object in chunks.

**Comment by jwoosnam** [comment]
I agree
