### ISSUE TITLE
Animation during screen updates

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#3]
One of the great things about an SPA is that the entire page stays constant, while new data is added/removed/updated.

The full screen animation during update delays really defeats that. 

(I recognize I'm looking at a very early version...but the point of writing these issues is to focus on getting some early "tuning".

**Comment by bakerac4** [comment]
@nrshapiro closing this - feel free to re-open I you have any issues with how it currently works
