### ISSUE TITLE
Admin Mode Settings, initial comments and issues v1

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#307]
@bakerac4 @adistasio 

I tested out the new admin mode...I understand you are working on it and I'm not sure what state you think it is in, but I'll report what I'm seeing on Stage.

Foremost 
- It's not saving correctly.  I make changes, sometimes I see some data being saved in the database, sometimes I see an empty {} being saved instead..not sure why and when.  For example, I've edited the French for the left top box.  I press save, looks like something is saved, but I can't see in the database (blob) well enough to check the data,  I edit again, press Save, and now there's just {} in the data for the record.
- Likewise for the queuing of the Expert Picks,  I created a queue, deleted the first record to see it.  At one point, I saw the graphic and not the article.  Tried again, seemed to revert to the default.  Still playing but it's not working as expected.

User Notes:
- Part of the expert pick problem above might have been case sensitivity.  I wasn't following any case rules.  You should be correcting that for the admin user in any case (ooh, pun).  
- I don't really understand the benefit/design of having a popup that's really no different than the fields you are editing.  Why not do this like the search area and the other form entries?  The way it's done has some disadvantages.  
   -  If you make a mistake, and notice it after you enter the row, you can't edit in place, so you have to delete the row and start over
   - Even if the mistake is for the graphic only, you still have to delete the row and reenter both the article and the graphic. 
   - This would be significantly better if it simply worked like the search form.. Plus to add a row.  trash to delete.  And let us edit in place.  That would also mean we could edit one side (graphic versus article) and leave the other as it is.
   - There should be some leadin instructions in each area.  Tell us what the current "cycle" is.  is it daily, weekly?  Give an example row showing what the data should look like.

If I edit this to add to it rather than starting another, I will update the v number in the title.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

I can replicate the save issue.

1) I did a refresh of the admin (F5).  It reset to the "original" (default) you must have set.
2) I did a save.  It saved data in the database.
3) It then leaves the interface ready to save again.  So I clicked Save again.
4) It saved an empty {} record.

**Comment by bakerac4** [comment]
@nrshapiro something to note - we are using the same DB, so we are both using this at the same time. My work might be messing with your results

**Comment by nrshapiro** [comment]
@bakerac4 - yes, I realize that.  But this also happened before, at least with the previous build, at night when I presume you weren't working.  And that's also why I'm only editing the French settings page.  If you stay off French, we won't bump.  (My previous experiments were also restricted to French.)

Lastly, how would us crossing settings end up with a completely empty data load?

![image](https://user-images.githubusercontent.com/4837554/110133368-3c989400-7d9a-11eb-8054-0757a228da16.png)

**Comment by bakerac4** [comment]
Unlikely it would, but we could certainly be overwriting each other at some point. That sounds good, I'll stay off of the French settings page!

**Comment by nrshapiro** [comment]
@bakerac4  The issue gives me an idea...it wouldn't hurt if the client were to save a backup of the old settings when saving a new one.  Then we _at least eventually_ could offer an undo option to the admin editor (perhaps a "previous version" button next to the larger form fields?

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

David's input this weekend into the Expert Picks setup, he does not want the two queues to be tied together.  In fact, that's true, they are really separate.

**Comment by nrshapiro** [comment]
@bakerac4  

Another comment: when using a lighter theme at least, the new striped background controls in the Admin settings for moving around infocards hurts my eyes...I can't speak for others, but this article does: https://www.optimax.co.uk/blog/patterns-stripes-hurt-eyes/

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

Per my note to Alan this morning (I've since talked to David about this and had this approved.)

As you know, David asked to separate the queues, but I may have a better idea.

What if the graphic value could be entered as * for some days (or just allowed to be empty), and the app would randomly pick a photo from a special folder we put on S3 where any photo can be used?  In fact, you would never have to retrieve the photo itself, just need the photo file name, minus the extension, which is in fact the ID in the database.  The purpose of using the folder is that it's easy for them to populate just by looking at thumbnails and dragging and dropping.  I could get you a list of all the filenames instead in a file, but then it wouldn't be as easily or automatically update able.

That way, they wouldn't have to set up a photo every day, but they could still choose to set one up associated with a specific expert pick document.  And you wouldn't have to change the current dialog, just deal with * as above for a random pick photo.

In fact, right now I'm working on creating a dropbox folder that they can preview and delete photos out of, to end up with the set.  There are about 18,000 photos/graphics, I've culled them based on size and aspect ratio down to 14000, and they will cull the ones they never want to show, leaving a "candiidate set".  I suspect you will have about 8000 in the final set...plus updates as new articles are added.

**Comment by adistasio** [comment]
From Neil:

Per our teleconference today, the API now allows * as the documents/image/imageID url parameter If you use *, the first time it will pick a graphic randomly from the designated bucket. But the first time, when the s3 bucket is large (up to 13000 images), it may take 5 or 6 seconds to pick one. But it keeps it for the entire day, so it's very quick on the rest of the calls, until the first call the next day.

There's a new query parameter seed which may avoid caching from day to day.

Also, if you restart the server, a new image will be selected for the day.

(This is still being tested on Stage.)

**Comment by bakerac4** [comment]
@nrshapiro after looking at this more in depth, what we currently have wont work. This is due to needing the article title for the text below, as well as a link to the article that the image is from. We really need the ID in order to do it correctly. 
![Screen Shot 2021-03-24 at 12 06 34 PM](https://user-images.githubusercontent.com/9952936/112343313-622e0480-8c99-11eb-82e0-4897c7d7f2c8.png)

**Comment by nrshapiro** [comment]
Ok,  I've changed the way /Documents/Image works.  It will return article ID if you use Download = 2

I removed the seed arg which was just to avoid caching yesterdays image.  You can just pass in an arbitrary argument to seed it in the arguments and the server will ignore it.

![image](https://user-images.githubusercontent.com/4837554/112397899-56fac900-8cd9-11eb-955e-601594d943ee.png)

Also, I added a reselect argument, which forces the image to change, even though it's the same day
