### ISSUE TITLE
Admin Mode - Add Login Dialog Text (but see Issue #312 which changes the login dialog)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#311]
![image](https://user-images.githubusercontent.com/4837554/110211157-4afeb280-7e63-11eb-8466-6dcad82e4774.png)

The message on the login dialog changes periodically by David and Athena, who is in charge of subscriptions.  I already had a message, this morning to change it, and I'd rather let them change it themselves directly, unless that presents a problem.

It may end up being larger as well.  I assume the dialog can resize dynamically.  As you can see, there's a lot of text in the current site message (not all of which applies, i.e., the second paragraph):

![image](https://user-images.githubusercontent.com/4837554/110211241-b3e62a80-7e63-11eb-84d6-702ded5c3b26.png)

The initial login change request for the text that came this morning:

> This is the Psychoanalytic Electronic Publishing Archive full text database. It is freely available for everyone to search, view tables of contents, and view summaries. However you will need a subscription in order to view full text, follow links, etc. Users with personal access codes can use all personalisation features immediately. Users accessing via a university or group without need to register (free) with PEP to use them.

_and included instructions for which text is not finalized (and neither may be the above):_

> Need a link to subscribe - http://support.pep-web.org/subscribe/ at present and also how to register. (Registration needs ref to privacy rules http://support.pep-web.org/subscribe/pads-and-its-data-protection-policy/ needs updating to cover data we are collecting.

The second part of the above will probably go below the two edit fields, so we need a template of sorts where the text can specify where to place those, or two fields (above/below).

If this presents a problem or too much work prior to Beta 1, let us know and we can try to work it out within the strings settings.  I guess we could alternatively work directly with the PEP-Web-User-Interface git branches and do the string settings there.  But there may not be two different settings currently as is anyway (above/below fields).

**Comment by nrshapiro** [comment]
See #312 which changes the login dialog to a infocard and could have implications for the way it's edited in admin

**Comment by nrshapiro** [comment]
@adistasio 

This is listed now, in case the dialog is to persist in addition to the infocard, and to keep note of the document text and link changes that had been requested.

**Comment by adistasio** [comment]
You can edit the dialog and side login via admin. Closing.
