### ISSUE TITLE
"In your face" request to login.

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#312]
The short login message at the top is supposed to be an in-your-face prompt to encourage logins, something PEP is very keen on.  However, I am not sure when the top login box comes up, since it mainly appears for me when I log out, or if I do a cookie clean, and then go through the intro mode dialogs.  Once you dismiss it, there's nothing that encourages you to log in.

But David is very keen on having the login prompt "in the user's face" until they log in.  So I came up with this solution.

We can instead use an Infocard for the login, rather than a popup dialog.  That way, it can stay loaded while the user is not logged in, as a reminder.  It may even be used in addition to the top prompt that comes up.

This Sign In infocard will always be visible at the top of related info UNLESS you are logged in.  That way, the incentive and information to log in is always there, until such time as you are logged in.  Once you log in, it will hide itself until you log out.  At that point, it will reappear.  It will not, of course, be an infocard that the user can turn off in preferences.  In fact, I think it should not be "foldable" like the other cards.  But like the other cards, Admin should be able to determine where it appears (left or right).

Here's a mockup which David has approved.  The actual text needs to be configurable in Admin:

![image](https://user-images.githubusercontent.com/4837554/110256984-c9de1300-7f69-11eb-9476-af26b5a5f325.png)

In addition, please add a message to the Preferences dialog warning the user that unless they are logged in, preferences will not be saved.

(Beta 1 if possilble...but I've listed this as Beta 2)

**Comment by nrshapiro** [comment]
See Also #311 which mainly concerns the editing of text.  This request supersedes it in some ways.

**Comment by bakerac4** [comment]
@nrshapiro can you send a screenshot of "The short login message at the top"?

**Comment by nrshapiro** [comment]
@bakerac4 

Not sure exactly what you mean...this? It's just starting boilerplate as an example.

![image](https://user-images.githubusercontent.com/4837554/110362258-0fa0e700-800f-11eb-9981-a7391a2d8ade.png)

Here's the text itself:

This is the Psychoanalytic Electronic Publishing Archive full text database. It is freely available for everyone to search, view tables of contents, and view abstracts and summaries.  However you will need a paid subscription in order to view the full text of articles.

All users can register to get a username and access password that will let you save your application preferences, customize the information displayed by the interface, and save bookmarks and favorites.  University, group, and federation users need to register to get an individual login to save their preferences as well.

**Comment by bakerac4** [comment]
"The short login message at the top is supposed to be an in-your-face prompt to encourage logins, something PEP is very keen on. However, I am not sure when the top login box comes up, since it mainly appears for me when I log out, or if I do a cookie clean, and then go through the intro mode dialogs. Once you dismiss it, there's nothing that encourages you to log in."

Unless Im misunderstanding - you'r talking about a login message/box that already exists that appears when you log out? Thats what I was asking for a picture of

**Comment by nrshapiro** [comment]
![image](https://user-images.githubusercontent.com/4837554/110363475-9dc99d00-8010-11eb-92be-97701532c532.png)

David did not think that was enough, or more likely, it just didn't appear "enough".  Once you cancel it, it doesn't come back, so there's no reminder.  At a minimum, I would expect it to come up when you select Preferences if you are not logged in.

If you want to try that and the existing login, you could make that change, and see how that sits with David.  Another alternative possibility is to put that up when not signed in and leave it up (below the menu bar, so it doesn't block anything)  Again, that may do it for him, I don't know.  If that's easier than the change I'm suggesting, then you could try it first, and we'll see.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 
(I should add that personally, I think the new way I specified works better, because it also can be used to explain registering etc.)

**Comment by bakerac4** [comment]
Yes ok, just wanted to confirm. That banner was only added as a way to tell the user if they need to make preference changes, they must login. And we wanted to do it in a way that didn't block them from actually using the site, which is why it's minimally intrusive. It does "come back" each time you make a preference change for what its worth.

**Comment by nrshapiro** [comment]
@bakerac4 

Yes, it's good for that--I wasn't sure it came up WHILE you made preference changes but I see it does.  Otherwise, the user would be upset to make changes and then not have them saved...so we're warning them DURING, which is good.

So that is fine, and fine how it comes up before you login.  But the new infocard should be added.

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 

Perhaps one of the problems DT was having with the not-in-your-face login (with the popup on top) is in part due to a bug.  

This does not work on Production, even though the stage/production versions are the same.

If I am not logged in, and I go to preferences on Production, and make changes, I never get told that my changes won't be saved.

The login prompts aren't behaving the same there, for whatever reason.

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 

Here's a demonstration of the above...I did it on Edge, but it behaves the same on Opera.  Also notice how when I click on a checkmark in preferences, sometimes other checkmarks change!  In the beginning I use About to show version info on production.

https://user-images.githubusercontent.com/4837554/110663012-1311ab00-8194-11eb-8b9d-96c981f1765c.mp4

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 

Just FYI, the new vers from today addresses the missing login menuitem issue on Stage, but ONLY AFTER I CLEARED COOKIES.  Loading the newest version with a refresh did not change menus etc. until after I went into devtools and cleared cookies.  Another good reason to get the clear cookie page done for Beta 1

**Comment by nrshapiro** [comment]
@adistasio Also, per our discussion today in #337, read the three notes above, and particularly watch the video, showing problems in the way Preferences works, at least on Production.  Pay attention as I click on infocard checkboxes and see how another one sometimes changes with it!
