### ISSUE TITLE
Admin vs Users - Defaults versus active preferences

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#321]
This is more a question and issue to be considered, which came about as a result of comments from DT regarding his user account.  

What happens to user preferences when we change general admin setttings?  These are meant mostly to be defaults.  

1) Suppose I rearrange the default order of infocards.  Does that change the user's order?  It should not.
2) Suppose I change which are open initially?  Again, this should not change user settings.  
3) What if I move if from the left side to the right?  That's needs discussion.  
    - If the user can also move from left to right side (etc.), then I think we leave their settings alone.
    - If not, we might want to change that.  Need to discuss.

On the other hand, if we completely turn off an infocard, so it's not available, that's not a default, it's more than that.  So IT SHOULD be removed from the user's visible set.  (Which I don't see the ability to do yet in admin, though I believe it's in requirements.)

**Comment by adistasio** [comment]
Closing. We're respecting users settings.
