### ISSUE TITLE
About menu item placement

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#322]
Now that we have a ? menu, it seems like it would make more sense to put "About" there.  And to distinguish it, and have it stand out, we might want to rename it "About PEP-Web" there. 

Marked as high priority, only because if we agree we should do this, it would be good to do it before the betas.

**Comment by adistasio** [comment]
@nrshapiro Are you saying there should be a new menu item under the ? menu item called About PEP-Web? And if so what should it do? Open a new link?

**Comment by nrshapiro** [comment]
@adistasio 
I'm saying the "About" menu item under the user menu should be moved to under the ? menu, and then the "About" menu item should be renamed to "About PEP-Web".  It should not change in function...just talking about moving it.
