### ISSUE TITLE
Logon Method – not showing for individuals

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#327]
The logon method is showing for primary Group logins, but not for individual logins either primary or secondary.  

This would be useful but not essential, and it may also help with what you show on the front-end.

**Comment by adistasio** [comment]
@jwoosnam I'm not sure what you're referring to. I logged in as a regular user (no IP/referral/federated) and the application indicates I am an Individual user. Can you screenshot the spot you are referring to?

**Comment by jwoosnam** [comment]
@adistasio 
<img width="181" alt="Screenshot 2021-03-11 at 14 12 10" src="https://user-images.githubusercontent.com/70103034/110800374-05cbed80-8274-11eb-8dd9-3c4e9d7b8aa7.png">
<img width="505" alt="Screenshot 2021-03-11 at 14 12 29" src="https://user-images.githubusercontent.com/70103034/110800381-06648400-8274-11eb-87c3-60070dc6f748.png">
