### ISSUE TITLE
Login Prompt at Top not showing up on Production

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#337]
Client: 2021.03.12-6760

See the video...no login prompt at top, despite me going to Preferences a number of times.

https://user-images.githubusercontent.com/4837554/111017954-5e8aab80-8384-11eb-83a2-83312d56d481.mp4

Works on Stage so must be misconfigured here.  Also, I note that production has a smaller EC2 machine than stage.  And it does seem slower.

**Comment by lhorne-gavant** [comment]
@nrshapiro I double checked that production EC2s are the same size as staging. Is there an action in particular that seems too slow?

**Comment by adistasio** [comment]
@nrshapiro I think there is some confusion here. Based on the video the application is working as it should. We only show the login prompt is you are logged in as a group user (ip/referral/federated) as a way to prompt you to login/create an account as an individual. If you are not authenticated at all we store the preferences in a cookie. Would you like us to change the behaviour?

**Comment by nrshapiro** [comment]
@adistasio - It's not behaving correctly per the video

1) If you are in preferences, you are making changes for nothing because they won't be saved if you are not logged in.  
2) As we went through a month or two ago, when at one point EVERYONE was going to be required to login, the fallback was o allow use without logging in, but to have login "in-your-face" as much as possible.  It's key for DT (and PEP) that users are encouraged to login as much as possible, and thus also encouraged to register.  We will take this up another level in Beta 2 with the sidebar login infocard, which also addresses the fact that we have to let them dismiss the top prompt box.

**Comment by nrshapiro** [comment]
This was marked high priority and not marked Beta 1, but it obviously was for that.  It may in fact be resolved, but leaving open for final Beta 1 review.

**Comment by bakerac4** [comment]
I believe this is working. Please re-open if thats not the case
