### ISSUE TITLE
Production Issues - Show Stoppers

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#341]
@adistasio 

I have a new one this morning, but first I want to emphasize that:

Login Prompt at Top not showing up on Production - High Priority bug - [#337](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/337)  is a **_significant_** show stopper for DT.   Oddly, this works on Stage but not on production.  See the issue database link above for details.

But this morning I note that the Production site is not following the preferences I set.  I've gone into Preferences several times this morning and it doesn't change the out-of sync settings for Infocards and what you're seeing on the right.

![image](https://user-images.githubusercontent.com/4837554/111158268-36f73700-856e-11eb-85a0-7aa802e0f1cc.png)

and I am logged in:

![image](https://user-images.githubusercontent.com/4837554/111158322-48d8da00-856e-11eb-9173-745cf0cf6460.png)

something is up on production!  Please handle today...Beta 1 starts tomorrow.

**Comment by nrshapiro** [comment]
@adistasio 

I pushed today's version to Prod to test.  Preferences now calls up the login dialog, but preferences (at least regarding infocard selection) are still not working, at all).  It does load my screen style settings though when I login.

https://user-images.githubusercontent.com/4837554/111186754-b6deca80-8589-11eb-9a05-a1e2c4e8624d.mp4

**Comment by bakerac4** [comment]
@nrshapiro Im not seeing this on dev or candidate. Could you provide me with your/a login for prod?

**Comment by nrshapiro** [comment]
@bakerac4  - Quickest way would be to use Alans.  He has one.
@jwoosnam Or James, if you wouldn't mind setting another up as a "tester" ID on production, since that's where we are having issues.

/cc @adistasio

**Comment by jwoosnam** [comment]
@nrshapiro @bakerac4 
User set up and activation email sent to Adam. Username is Adam's email address.
