### ISSUE TITLE
Bug in Infocards - Duplicates after changing preferences

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#353]
I went in to prefs on Stage and checkmarked Publisher Info, so I could test some newly added data to Admin settings.

Returned with two.  Went in again, unchecked a couple of checked items, returned with three publisher infocards.

![image](https://user-images.githubusercontent.com/4837554/111472297-35f60f00-8700-11eb-8f31-fd73f6f713e5.png)

**Comment by nrshapiro** [comment]
@adistasio After clearing cookies...I still have three publisher info cards!

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 Nothing I do gets rid of them.  I turn off the infocard.  Clear cookies.  It refreshes the window, and they're back.  

Note this is on stage where I have IP authentication turned on, but I'm not logged in.  Where would these preferences be coming from?

**Comment by nrshapiro** [comment]
I manually edited them out of the global JSON settings saved in the database on Stage, and they are still there. :(

**Comment by adistasio** [comment]
@nrshapiro you'll want to update the db to remove the dupe items. The UI bug that caused this is resolved.
![Screen Shot 2021-03-17 at 3 10 44 PM](https://user-images.githubusercontent.com/3603329/111524619-0c0a1000-8733-11eb-991f-ffda2a97567d.png)

**Comment by nrshapiro** [comment]
Done...and it worked.

------ Original Message ------
From: "adistasio" ***@***.***>
To: "Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface" 
***@***.***>
Cc: "Neil Shapiro" ***@***.***>; "Mention" 
***@***.***>
Sent: 3/17/2021 3:11:50 PM
Subject: Re: 
[Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface] Bug in 
Infocards - Duplicates after changing preferences (#353)

>
***@***.*** <https://github.com/nrshapiro> you'll want to update the db
