### ISSUE TITLE
Most Cited/Viewed Filter on the tabular views of data

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#36]
The most cited filter in the statistics (tabular) interface is not using the correct API parameters, and thus the filter is working incorrectly.  If you ask for 5 years in a period, you should not get back any papers before 2015 like this one:

![image](https://user-images.githubusercontent.com/4837554/93815279-b50ffc00-fc23-11ea-915b-452569de2db5.png)
 
Period is supposed to be the publication period, per spec section 10c (and particularly, see the example picture in the spec.

Request URL: https://stage-api.pep-web.rocks/v2/Database/MostCited/?author=Tuckett&limit=20&offset=0&period=5

The correct parameter is pubperiod for both MostViewed and MostCited stat.

Request URL: https://stage-api.pep-web.rocks/v2/Database/MostCited/?author=Tuckett&limit=20&offset=0&pubperiod=5

Please change to using Pubperiod.  I'm going to change the other parameters a bit for clarity, obviously a parameter just called Period is a bit confusing with pubperiod, so I am thinking to rename that to viewperiod and citeperiod, as it's already called on the search endpoint.

Also, your use of limit for terms and phrases on the search page is not per the spec.  In the current app, you can only filter by cited and viewed values (they only seem to work when you add other criteria).  However, these are independent search parameters in the spec (and on our current PEP-Web site: 

![image](https://user-images.githubusercontent.com/4837554/93818562-89dbdb80-fc28-11ea-836a-eeffcf94a325.png)

**Comment by billdami** [comment]
@nrshapiro regarding this part:

> Also, your use of limit for terms and phrases on the search page is not per the spec. In the current app, you can only filter by cited and viewed values (they only seem to work when you add other criteria). However, these are independent search parameters in the spec (and on our current PEP-Web site:

Do you mean the main document Search (if so, this should probably be a separate issue)?  And if so, do you mean that the user should be able to search when only supplying values for the # of views/cited fields? I think we made these function as fields that only furthered restrict/limit the other supplied search values due to the use of the "Limit to:" labeling that was mentioned in the requirements doc, rather than just fields the user could a search with on their own. But if thats not the case, this should be a fairly simple thing to fix.

**Comment by nrshapiro** [comment]
@billdami Yes, this should have been a separate issue...I am not "bugging" things per se (why I dont' mark them as bugs), just giving you early warning where I see things going off spec.  Bug reports come later in my book--you are still developing.  But yes, 
I did think about opening it as a separate issue report, and will do it that way in the future for tracking purposes :)

**Comment by bakerac4** [comment]
@nrshapiro @billdami was the main document search item that @nrshapiro brought up ever made into a different issue? Looking over this one and I don't want to close it out until that gets made (if it hasn't already)

**Comment by billdami** [comment]
@bakerac4 yes it was, and i believe I already fixed that issue too
