### ISSUE TITLE
Pop-Ups - Extend beyond the message area, losing initial chars to background text

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#364]
The pop-up design which has a shadow, loses the intial characters to the background because it extends beyond the box borders into the shaded area.  In this case the second paragraph illustrates how the initial chars are lost to background noise.  It would be better if the text stayed in the box and shading is for show.  If turning off shading fixes this, that's fine.  It doesn't add much.

![image](https://user-images.githubusercontent.com/4837554/111810284-38956780-88ac-11eb-8957-7a86d04e058e.png)

**Comment by bakerac4** [comment]
This was already fixed and is on stage
