### ISSUE TITLE
Style Sheet - Spacing Needed in References

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#370]
In the XML, a reference looks approximately like this :

`<be id="B001" rx="IJP.073.0467"><a><l>Amati Mehler</l>, J</a> (<y>1992</y>) <t>Love and male impotence</t> <j>Int. J. Psycho-Anal.</j> <v>73</v> <pp>467</pp></be>`

But when it's displayed in the app, and copied as text, it looks like this:
   `Amati Mehler, J ( 1992) Love and male impotence Int. J. Psycho-Anal.73467`

or from this article's (CJP.002.0135A) references captured, like this:

![image](https://user-images.githubusercontent.com/4837554/112023169-5e6b7800-8b09-11eb-8387-62698dea3e05.png)

Here you can see examples of the many places between fields where spaces need to be inserted in the style sheet in the reference sections.

**Comment by bakerac4** [comment]
@nrshapiro can you provide the ID for the document you are seeing this on?

**Comment by nrshapiro** [comment]
@bakerac4  I did above...CJP.002.0135A

**Comment by bakerac4** [comment]
Ha, wow Im sorry. missed that completely. Thanks!
