### ISSUE TITLE
Problems in the Update Notifications dialog

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#371]
This video illustrates several problem in the Update Notifications dialog: Client: 2021.03.19-6893

1) The email label overlays what the user types for email, making it look bad and difficult to go back and reread
2) It was telling me "No" by flashing the Update Notifications button, but not giving me a clue why (it may be my address is already in the database, but that shouldn't matter, perhaps I'm changing my interests?  And if it's in there, shouldn't it show me what my subscriptions were?  And it should use words to explain what's wrong.

Video:

https://user-images.githubusercontent.com/4837554/112030876-16505380-8b11-11eb-911b-e272285d8d66.mp4

**Comment by adistasio** [comment]
@bakerac4 For this dialog we will remove the email address field. There are then 2 fields SendJournalAlerts, SendVideoAlerts on the save user endpoint in pads. Can only access if logged in as an individual user (or admin). IE no group or unauthenticated users.
