### ISSUE TITLE
Video List in Left Sidebar of Read

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#381]
In my meeting with DT today, he mentioned that he felt the "videostream/journal" based listing of the related documents was confusing.  Unlike a journal, his argument is the videostreams (which in most cases is just the "source" or publisher), is not truly a related list of documents.

What he would prefer instead, is the complete list of videos.  However, during the call, we came up with more context sensitive possibilities.

Since that's just done via a search, we brainstormed other ideas.

1) More like this.  The problem here is that they would not all be videos (and the non-video specific feature is available in an infocard anyway.)

2) By Keyword or Category.  This seems like the most tenable alternative, but requires some backend work first.

All of the above, could easily be changed over by simply changing the query used to produce the list, as long as the results are what's need.

In the meantime, he would like the currently contextually sensitive list to simply revert to a complete list of the videos, in the same alphabetized bibliographic format.

I will work with him and assignees to add the necessary categorization/keywording to the XML and then the database itself, so it will be a simple query change.

**Comment by bakerac4** [comment]
I did the item that you wanted for the meantime. Closing for now

**Comment by nrshapiro** [comment]
In the meantime, he would like the currently contextually sensitive list to simply revert to a complete list of the videos, in the same **alphabetized bibliographic format**.

**Comment by nrshapiro** [comment]
It appears to be alphabetized in Read...it's Browse => Videos where it's not alphabetized

**Comment by bakerac4** [comment]
Added sort
