### ISSUE TITLE
Embed HTML in left and/or right home page cards?

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#391]
DT wanted the possibility of putting a video in the top right/left home page cards.  I was able to do it instead of the book icons by editing the HTML that the interactive editor produces on stage directly in the database.  But I don't see any way in the interactive editor to do it so it can be done through the normal means.

Is it possible?  Even in the general sense, embedding HTML might be useful (or having the ability to see/edit the HTML in the interactive editor as many visual HTML editors allow.

Example:
![image](https://user-images.githubusercontent.com/4837554/113055117-366abd00-9178-11eb-9cc9-948f63944250.png)

**Comment by bakerac4** [comment]
I believe this has already been added
