### ISSUE TITLE
About

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#4]
It would be helpful to prioritize the "About" functionality of the user menu so we can see what Client release is running on pep-web.rocks, as well as for tagging any issues as associated with a release.  Note that you can also easily get the other component versions via the API endpoint /v2/server/status which returns:
{
  "db_server_ok": true,
  "text_server_ok": true,
  "text_server_version": "8.4.1",
  "opas_version": "2020.0805.1.Alpha",
  "dataSource": "OPAS.AWSProd.2020-08-15",
  "timeStamp": "2020-08-26T20:14:35Z",
  "user_ip": "172.17.0.1"
}

As documented, it's also helpful to show those to understand what's running behind the client as well.

text_server_version is of course the Solr version.  dataSource helps me verify which config is being used, but that's not likely to be useful in your client.

**Comment by adistasio** [comment]
@nrshapiro Per the requirements doc, what is the "support info" that should be shown in the dialog?

**Comment by adistasio** [comment]
@nrshapiro Any thoughts on "support info". We have this items complete minus what should be considered support info you'd like in the dialog.

**Comment by nrshapiro** [comment]
@adistasio 

1) System status Perhaps take that information and say "All systems operational", and if one is down, say something different (e.g., database maintenance is in progress)...make it user friendly.  The admin interface should show the gory details instead.

2) Show the app client version, server version etc in a small insignificant area...this is something mainly for us, I don't see a lot of reasons for uses to care).  Personally, I like to see dates of the versions, which is why I integrate that in the server number.  (The server version is mainly for us...not something to make prominent).  

3) Something about this fancy new client and its features.  I am not sure whether the spec says so, but like all informational text in the client, it would be good for this to be configurable in Admin. so we can tweak it and update it when we need to.  
   - This new PEP-Web user interface has been designed to make it easier to search the PEP-Archive more efficiently and effectively, and to take advantage of the latest technology to personalize your user experience.  This is just phase 1 of an ongoing overhaul of the PEP-Web system...In the near future, we will use advanced AI techniques to help find information in the archive and take your research to new levels..
   - Something about the PEP-Web Archive itself.  Here's a little blurb I Modified from our [Wordpress Help Page](http://support.pep-web.org/about-the-pep-archive/).  

PEP Web has been designed to provide a powerful rapid search of the entire psychoanalytic literature in English, French, German, Greek, Italian, Romanian, Spanish and Turkish. It is the result of an innovative, high quality series of technical developments and a considerable financial and scholarly investment.  You can [read about the innovative developments required to produce and keep updating the PEP archive](http://support.pep-web.org/about-the-pep-archive/digitization-and-quality-control/) and read [about the history of the PEP Archive](http://support.pep-web.org/about-pep/history-of-pep/).  You can even [suggest new content](http://support.pep-web.org/about-the-pep-archive/suggest-new-content/) that you would like to see added to the PEP Archive.

For more information, see the [PEP-Web support pages](http://support.pep-web.org/)

Athena, one of our support staff who works with the institutional users might have more to say here.  I'll send her the info as well and ask for input.

**Comment by nrshapiro** [comment]
@adistasio Add to the above...something about striving for maximum accessibility and/or spell out the target compliance level.
