### ISSUE TITLE
Sign In Information Card Enhancements and Popups

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#415]
Per our Tech meeting today, PEP needs a way to add more text to the sign in card, without overcrowding or overflowing the right pane.

1. We'd like a general mechanism to add a popup from a link.  Perhaps adding a special field to the URL for any page could popup one of the special information boxes, without losing the underlying context.  Another key part of this, since the text will likely contain login and PaDS links, is a manner to author it on Stage, while having the links point to either stage or production. 
2. The mechanism should be of general use because I can foresee it being useful to add, say, some "Quick Help" popup boxes, which don't take you to another site.  For example, a quick help popup with keyboard shortcuts.  Hence the desire to be able to invoke the popup (without changing the current context).  
3. We need a means to edit/add text to the bottom of the login box, below the user sign in fields.

NOTE: #2 isn't key, but I thought if the popup mechanism was general, we could use it elsewhere from a link in the text.  We could also achieve this of course more specific to each purpose adding a menu item (for example in help).  But trying to solve the login information problem, it's worth considering general solutions, per our conference.   I'd be happy to further discuss via phone to discuss technical issues and potential workarounds if necessary.

(I did make a pass at reducing the text in the login area, but it's still better to give them a means to put what they want!)

**Comment by adistasio** [comment]
@napafundi Making the popup generic is going to be tricky. Can we just have a couple of endpoints like /login-help and /info that the user can put anywhere and can be edited in admin?

**Comment by nrshapiro** [comment]
@adistasio  

Adding to the URL is fine as long as it doesn't lose the original context, and it's truly just a popup.  Perhaps if you can make the relative URL or URL parameter be specified in admin, that makes it general on top of that, so we can use it for whatever we want and have it make sense to the user.  Otherwise, if necessary, you could genericize like more-info1, more-info2, etc. or similar ideas.
