### ISSUE TITLE
Home Page Videos Not Playing

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#419]
As I mentioned in one of the comments on #417, the home page video previews aren't playing anymore.

I have a meeting early this afternoon to discuss progress, and movement to release Beta 2--I need to see what's going on and predict when we might get these enabled again.  It looks like it may be a simple permission issue from S3, because:

I feel this is important enough since we have users on that I'm escalating it to a issue in itself.  Here's the text I added to #417 describing the issue.

```
... I have noted as of this morning the videos on the front page aren't working at all. Not only no thumbnail, as there was before...no video. Something has changed.
...
Also, I was just experimenting since the videos weren't working: is this case sensitive? They were uppercase as shown below, but the URL is of course lower case in the Admin:

https://pep-web-video-previews.s3.amazonaws.com/peptopauthvs.001.0029a.preview.mp4

So I tried making it lower case, but it's still not working. So obviously something else is wrong.
```

**Comment by adistasio** [comment]
@nrshapiro Looking at stage, the config is set to drop box not S3. There is then a CORS error coming out of dropbox. If the intention is to have them come out of dropbox you'll need to update the CORS policy (if you can). 

![Screen Shot 2021-04-12 at 9 26 13 AM](https://user-images.githubusercontent.com/3603329/114401752-3784ec80-9b71-11eb-9045-4da8daee6c70.png)
![Screen Shot 2021-04-12 at 9 26 21 AM](https://user-images.githubusercontent.com/3603329/114401755-3784ec80-9b71-11eb-8e4e-f2afc800c136.png)

**Comment by nrshapiro** [comment]
@adistasio  I changed the first one that way because it wasn't working from S3.  Note the second one doesn't work from S3, and on production, they are both as originally configured on S3 and neither works.  I don't care if they are hosted on s3 or dropbox, as long as they work!

Here's the config on production:

![image](https://user-images.githubusercontent.com/4837554/114403192-9139e680-9b72-11eb-8dac-f1b2e0376e47.png)

**Comment by adistasio** [comment]
Neil, can you set the video URL's on prod to "https://pep-web-video-previews.s3.amazonaws.com/peptopauthvs.001.0029A.preview.mp4" please. The video urls are case sensitive. This url works on stage.

**Comment by nrshapiro** [comment]
> Neil, can you set the video URL's on prod to "https://pep-web-video-previews.s3.amazonaws.com/peptopauthvs.001.0029A.preview.mp4" please. The video urls are case sensitive. This url works on stage.

Well there's something Wonky going on.  That's exactly the URL that IS ON PRODUCTION.

Look at my original post for this...the comment on #417 .  I guessed it might be case sensitive, so I lowered the case of it on S3.  And it didn't work.  (Which is why I also tried it from Dropbox.)

![image](https://user-images.githubusercontent.com/4837554/114409388-694d8180-9b78-11eb-92e2-a6609b9f05a0.png)


I suspect it's working this morning on Stage because I just upgraded to the latest version--which has another problem, which is why I unloaded it the other day.  I just loaded it again this morning to show Adam that the left pane wasn't working properly as before.

The exact same URL is not working on production, which has the older version of the client.

![image](https://user-images.githubusercontent.com/4837554/114408953-f04e2a00-9b77-11eb-8b3d-dd4c27ca954a.png)

![image](https://user-images.githubusercontent.com/4837554/114409276-47ec9580-9b78-11eb-8004-d6ed540440d7.png)




As you can see, the URL is the same.  Unless my reading glasses are blurred.

**Comment by adistasio** [comment]
@nrshapiro they aren't the same. The difference is in the "case". I put bold around the letter difference. S3 is case sensitive. Even one letter off will cause the file not to load. If you replace prod with the stage url it should load.

Stage
https://pep-web-video-previews.s3.amazonaws.com/peptopauthvs.001.0029**A**.preview.mp4

Prod
https://pep-web-video-previews.s3.amazonaws.com/peptopauthvs.001.0027**a**.preview.mp4

**Comment by nrshapiro** [comment]
@adistasio 

ok, sorry I missed that.  I reverted it to mostly upper case, which it was originally, per our standard naming, and tried again, and it's working.  Not sure why they weren't working on Friday, that started me there, but we're all good now.

For the record, here's what they are supposed to look like:

![image](https://user-images.githubusercontent.com/4837554/114448276-569b7280-9ba1-11eb-9f83-fdb5b58187b3.png)

And now stage:

![image](https://user-images.githubusercontent.com/4837554/114448233-48e5ed00-9ba1-11eb-8696-e232b201c9a1.png)
