### ISSUE TITLE
Feature Tour Default for non-logged in users

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#422]
Per my management review of the interface this morning:

1) Management wants the feature tour off by default.  I agree it's annoying when you go to the site not logged in, unless you're a newbie.
2) I presume we have a link to it somewhere, but if not, let's just put it on the help menu: feature tour
3) they see the "Search Help Video" (which isn't yet ready) as important enough to add another link on ? menu to that.  I'll let you know when it's ready...meanwhile, you can add it and put it to the same (wrong) link as the one in the left top intro box

    https://fb.watch/4634xBWSZF/

Likely this should be configurable somewhere easy.

**Comment by adistasio** [comment]
Also we'll remove the Intro Tour preference in the help -> preferences menu
