### ISSUE TITLE
500 when clicking on Image

### ISSUE THREAD

**Issue by adistasio** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#427]
On stage if you click the image in the screenshot below it first brings you to a 500 error page, then it reloads and shows the correct article.

![Screen Shot 2021-04-13 at 10 54 57 AM](https://user-images.githubusercontent.com/3603329/114573834-b9931500-9c46-11eb-822a-b8ebe1a9352a.png)

**Comment by bakerac4** [comment]
I just made the link relative and it seems to work correctly now. if it still doesn't work in prod, I would wait until beta2 gets pushed out to diagnose
