### ISSUE TITLE
notex Links not being implemented

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#443]
In working on the keyword issue, I noted that the link tag `<notex>` was not being formatted or linked.

Here's a good example:

  https://pep-web.rocks/search/document/IJAPS.006.0262A?page=P0262&q=IJAPS.006.0262A

There are 10 notes at the end (above the reference section) and notex links throughout the document, starting with one at the end of the title.

There's another obvious note link `<notex>` at the end of the last paragraph in my screen capture.

![image](https://user-images.githubusercontent.com/4837554/115327853-ac51bb00-a15d-11eb-8f76-b97be4d328c8.png)

![image](https://user-images.githubusercontent.com/4837554/115327991-e8851b80-a15d-11eb-87d7-85908e13c5dc.png)

**Comment by bakerac4** [comment]
@nrshapiro which user gives me access to that document?

**Comment by nrshapiro** [comment]
@abaker-gavant 

I think test1 has a PEPArchive subscription on stage.  What do you usually log in as...you don't get access?  It's an old document.  (Harder to get to PEPCurrent).  Alan can give you the password if you don't have it...I can't post it here.
