### ISSUE TITLE
Limit To - Should not be showing by default

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#449]
As discussed in our tech meeting, Limit To in the search form should not be displayed by default.  It wasn't before, but it seems to be now.

This of course overlaps completely with #442, but if that's done later, this one is a higher priority.

**Comment by bakerac4** [comment]
@nrshapiro `Limit fields shown` was on in the admin - general settings page. I turned that off and its back to not showing unless you have manually opened it before while logged in

**Comment by nrshapiro** [comment]
I don't recall clicking that...but that's great as long as the option defaults to "off" if settings are ever reinitialized (which they seem to have sometimes, at least in development).
