### ISSUE TITLE
Login Change

### ISSUE THREAD

**Issue by adistasio** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#458]
If we show the login on the right, hide the rest of the right side bar.
<img width="265" alt="image005" src="https://user-images.githubusercontent.com/3603329/115890534-0931c780-a423-11eb-85eb-2ca806f50dad.png">

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 

Loosely per a suggestion from DT regarding color drawing attention,  it might also be good to give it a light colored background, not sure what would be best though, which will also make it standout from the rest.

**Comment by bakerac4** [comment]
Fixed by PR above and `7905dd21..3a205c17` for changing the color

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

Under normal circumstances, I would say that's great and the color choice is fine.

However, we are dealing with the perception that people can't tell **_1) if they are logged in, and 2) where to log in._**

Now I can see that login plainly and it looks pretty.  Fits in with the theme.

I see I can't customize the color, so I'm asking you to try some other colors, one that doesn't offend your sensibilities, but stands out.

Example:  This one isn't bad, you may be able to come up with something better:

Note 1: I'm just pasting color in PS, this method makes the text less readable...even when this isn't the case via method you might want to use black text for maximum contrast

Note 2: Yes, this one may clash with the theme a bit.  But that's what makes it stand out, doesn't it?

![image](https://user-images.githubusercontent.com/4837554/115918654-c6cdb200-a445-11eb-9a1f-218c4cbee640.png)

![image](https://user-images.githubusercontent.com/4837554/115918822-f977aa80-a445-11eb-8d3d-5302ca3f7fca.png)

For reference, that color is: e0eff9

![image](https://user-images.githubusercontent.com/4837554/115918975-32b01a80-a446-11eb-8800-c1f9b72ffc64.png)
