### ISSUE TITLE
TOC Volume Listing (Section Heading Issue)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#460]
I thought I might have already submitted this, but I can't find it, so here it is (apologies if so):

The TOCS, especially for some volumes, don't look very nice compared to the old system, which combined articles from the same section into one section heading.  It would certainly be an improvement to do that in the new system as well.

Example:

Old System:

![image](https://user-images.githubusercontent.com/4837554/115907446-deea0500-a436-11eb-9683-0eed3af5c95d.png)

New System:

![image](https://user-images.githubusercontent.com/4837554/115907347-be21af80-a436-11eb-9a17-f6957be83fbc.png)

**Comment by nrshapiro** [comment]
I also note, looking at the examples above, that "Adoption", which is the issue title, is not identified as such in the new TOC.  The old TOC is correct.  This is especially important when showing multiple issues. Is that because there's only one issue for this journal per volume?  If so, it's ok.  I do note that "Issue 1", "Issue 2" etc.  are correctly labeled as such in IJP TOCs.

**Comment by nrshapiro** [comment]
This would be best addressed in the client, but for now, I have a workaround in the server.  It does carry a significant limitation: it's done during load time, but since removal of redundant section heads is dependent on the preceding article, it won't work for new data loading if you run half the build backwards, which is how we currently process PEPArchive articles.  Fortunately, this will still work if the articles are being reloaded, as they often are in a rebuild (as long as the section headings have not changed from the previous load).

I think that this should still be addressed in the client, though.  For discussion.

**Comment by nrshapiro** [comment]
@bakerac4  I see...that's not in the data, but the server adds it (obviously for a reason at some point (if I recall correctly, the issue number wasn't listed without it, but that may not be right, and I don't remember.  However, there's two cases of this:

```
            if issue is not None:
                if issue_title is None:
                    if issue_seqnbr is None:
                        issue_title = f"Issue {issue}"
                    else:
                        issue_title = f"No. {issue_seqnbr}"

```

So it looks like the client builds the issue number and I can remove that.  What about journals with a sequence number?  Perhaps that's already being handled, since below, it doesn't show with the "No." pattern (though perhaps it should, if possible, since these issues are often referred to as Number 65.)

e.g., 

<img width="497" alt="image" src="https://user-images.githubusercontent.com/4837554/170097548-c71263ea-d4bb-4204-9e48-2e5023bff2a1.png">

Just let me know what you want me to do.  If the client doesn't want issue number or sequence number as the issue_title, easy to remove.

**Comment by nrshapiro** [comment]
@bakerac4  I reading back on the bug report this time, here's the problem.

You get these from the server call:
         "issue": "2",
        "issueSeqNbr": null,
        "issueTitle": "Issue 2",

1) The server should not populate the title with the issue number or sequence number.  You already have it.  I will stop it from doing that.
2) The client should build the issue number heading with the info as I do above, and then add the title when there is one.

The heading with a title should be:

Issue 1 - Adoption    (as it was before at GVPi)
Issue 2

Perhaps underlined like GVPi

**Comment by bakerac4** [comment]
@nrshapiro that sounds like the right thing to do. Let me know when thats up!

**Comment by nrshapiro** [comment]
@bakerac4 - I'm in the process of updating some libraries as well, but the version on stage has the change you are looking for.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/4837554/170264441-533c75ef-f92e-4781-ac19-d155d0bb638d.png">

There is no longer an issue title in the TOC.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/4837554/170264332-35097eaa-81e5-4218-8f84-2560005fe9d1.png">

**Comment by bakerac4** [comment]
@nrshapiro what should happen if I receive a `null` issue. Found here `/browse/IJP/volumes/3`

**Comment by nrshapiro** [comment]
> what should happen if I receive a null issue. Found here /browse/IJP/volumes/3

@bakerac4 

Not all of our volumes are broken up into issues.  In this case, in the earlier years of IJP (multiple volumes), there were no issues.  So if you get a null, then don't put an issue title/number.  

See example from production:

https://pep-web.org/browse/IJP/volumes/3

**Comment by nrshapiro** [comment]
@bakerac4 

Also (continuing previous comment): 

1) I note the pages are not in order.  (I don't recall if that's a setting somewhere.)  But they used to be.  Here's a pic from an older client

2) Also, I liked the section titles at least somewhat smaller or lighter than the issue # and title.  The issue number and title is what supposed to be dark.  Here's an older client from before the fixes on my local machine (issue number is missing because my server no longer supplies it like it used to for that client, per our changes.)

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/4837554/173844095-e154608f-5621-44c8-b8e8-f296a3d5358f.png">

**Comment by bakerac4** [comment]
I think I know the issue with things being out of order. Im using `newSectionName` to group things into sections under an issue. But your only sending that for the first item. Would you be able to fill out  `newSectionName` if its in that section?

**Comment by nrshapiro** [comment]
@bakerac4 

That editorial is not in the "Articles" section.  According to the input XML, it's not in any section, though they show the article title as a section name in the contents.  But that's keyed as an article title (as it should), and a section name "Editorial" would look a bit silly and redundant.

You should be able to handle it either way, as some articles will be in sections, others not.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/4837554/174152585-50261a88-ff8b-4a61-8bfb-f066a36686ff.png">

**Comment by bakerac4** [comment]
@nrshapiro Im not sure I follow - but it would be easiest for me if you were able to "tag" the article with its section (or dont provide one with a section) and Ill group all the ones with a specific section together and the rest wont have a section.

But currently your just tagging the first article in the section with the section and the rest of the articles that should have a section do not

**Comment by nrshapiro** [comment]
@bakerac4 

It took me a while to figure out the disconnect.  The problem is that you are sorting the TOC by sections.  This is not correct.

The TOCs should be sorted by page number.  The sections are naturally sorted by page number.

And for what it's worth, that's why newsecnm works by introducing only a new section...with the main issue being what happens if a paper is not in a section, but is instead at the top level.  

Presuming you are working from the Metadata/metadata_contents_sourcecode_v2_Metadata_Contents__SourceCode endpoint, I'm working on a fix for that..  Stay tuned.  I will return a newsecnm of "TopLevel" for any paper which is not in a section.

**Comment by bakerac4** [comment]
@nrshapiro you mentioned stay tuned but I haven't heard anything back. Were you able to make the changes I mentioned?

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

Ok, I've put the latest PRE-RELEASE/Development version of the server on Stage.  As you can see, it labels toplevel items "TopLevel".  Obviously, that's not a real section heading and should not be shown.

Note again that the pages should appear in the TOC in order.   The only journal that will not work well in any current configuration is PSU, because they have multi-level TOC sections.  We'll have to deal with that later.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/4837554/176315730-25e5b1b4-e7ab-4013-82ac-1615df8e798b.png">

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4837554/176315998-7bf6a09a-a927-4d9d-9072-8c0d8c8b387d.png">

**Comment by bakerac4** [comment]
@nrshapiro after looking this all over it seems that even the current prod site is putting the roman numeral sections last https://pep-web.org/browse/CFP/volumes/12. That seems to be because you are sending it last. 

```
https://stage-api.pep-web.org/v2/Metadata/Contents/CFP/12/?limit=1000&moreinfo=2
```

**Comment by nrshapiro** [comment]
@bakerac4 - one point missed from above...I added TopLevel for you per earlier discussions (my June 20 message from above, quoted below).  Did you use this?  If not, I want to remove the return of that label because it should not show up in the TOCs.  If you are using it, we need to have the client drop it and not add it to the TOCs

> Presuming you are working from the Metadata/metadata_contents_sourcecode_v2_Metadata_Contents__SourceCode endpoint, I'm working on a fix for that.. Stay tuned. I will return a newsecnm of "TopLevel" for any paper which is not in a section.

@adistasio @davidtuckett

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio - See my message above from 15 days ago.  Response?
