### ISSUE TITLE
SmartSearch - Labeling

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#469]
In writing up help and other instructions to users, it's become a problem that the control we labeled SmartSearch in our designs is not marked in the app.

I am fine not wasting another line above the control, but I think it will fit in nicely in the control itself, along with the text you currently have:

![image](https://user-images.githubusercontent.com/4837554/116285518-2dabdd80-a75c-11eb-8dfc-c71b8738a33c.png)

I have also run this by DT, and he agrees.

**Comment by bakerac4** [comment]
@nrshapiro on my screen with the sidebar at the smallest measurement it _barely_ fits. I would probably just recommend moving it to above the field. That way at least it matches the "Find terms and phrases" title thats above the other fields

![Screen Shot 2021-04-29 at 10 43 43 AM](https://user-images.githubusercontent.com/9952936/116569848-c74bca00-a8d7-11eb-99d0-2aa1de2abb8f.png)

**Comment by nrshapiro** [comment]
@bakerac4 

I agree it's tight, but it fits.  Unless I'm missing something, we could try it and see if it flies like that.

Is it also just as easy to make the panel slightly wider?  That would help for searching in general, it's easy to overrun the space.

Some thoughts for later, or if for some reason I'm not seeing it doesn't work at all that way...

We did originally specify the label above and the text "Enter any type of search" which is a bit shorter.

Now: (to compare lengths)
SmartSearch: What are you looking for?
SmartSearch: Enter any type of search!

Other option:
SmartSearch: Any type of search!
SmartSearch: Find anything!

One other possible space saving workaround:   Could it be setup to show smartsearch as the "smaller label" like this?

![image](https://user-images.githubusercontent.com/4837554/116574599-e3ea0100-a8db-11eb-8630-611e4452a01f.png)

I'll run the various options by D & N.  And see if they think the way you show is too tight.

**Comment by nrshapiro** [comment]
@bakerac4 

In the meantime, please do this:

I agree it's tight, but it fits. Unless I'm missing something, we could try it and see if it flies like that.

Is it also just as easy to make the panel slightly wider? That would help for searching in general, it's easy to overrun the space

**Comment by nrshapiro** [comment]
The text is fine now until you start to type, then since it wraps in the miniature form, it blocks text entry.

![image](https://user-images.githubusercontent.com/4837554/116747197-88973c00-a9cb-11eb-9044-f7eb0a135508.png)

![image](https://user-images.githubusercontent.com/4837554/116747071-61d90580-a9cb-11eb-85d4-1e1887c7b108.png)

Do you have control over that?

What if you left off the ?

Otherwise, please try:

SmartSearch: Enter any search type

no exclamation.

or barring that, 

SmartSearch: Enter any search!

**Comment by bakerac4** [comment]
@nrshapiro I added a heading to the smart search text box. Due to the ability to change the font size, along with the large text that you wanted to go in there to solve the wrapping issue I think it had to be done. Give it a try and if you hate it let me know and we can try to come up with a different solution

**Comment by nrshapiro** [comment]
Adam, while it looks fine that way, the problem is that it wastes a bit more vertical space, and whiile we originally asked for that label, the way you originally implemented it did have that space saving advantage.   The text you are trying to preserve is cute and general, but doesn't in my opinion add context to make it worth giving up space and going through these iterations to preserve it.  The only thing that was important to me was to properly label it so we can directly refer to it in help as SmartSearch and not just "the top box".  (And to that point, this achieves that.)

This though has secondary implications in that we are planning to go live with this on Wednesday.  David and his UK team have been making videos for the last week or so to teach users, and he is very firm that we should not change the look of the front end at this point.  

He wasn't happy even with the more minor in-control change, but I think it's important enough that I pressed it.  This approach, while wasting the vertical space more has the advantage that the line in the control is constant, so l say we can leave it for now.

**Comment by nrshapiro** [comment]
@abaker-gavant 

Another issue with this: The label uses the two word version from the original spec: Smart Search

We have since agreed (and I used it that way above) that SmartSearch is a coined "feature name" in the trademark sense (though I doubt it's available as a trademark).  Which is how I used it above.  Given my above comments about UI stability, I would leave it this way for now, it will not be "hair raising" hopefully to modify the interface slightly later and try it as one word.

**Comment by nrshapiro** [comment]
@abaker-gavant 

Actually, weighing all the factors above, FOR NOW, please IMMEDIATELY switch it back to the original, unlabeled way it looks in our help files (the way you originally had it before this issue was raised.  Then I'm going to do a push to production.

We will save this for another day.  But it's important to revert it immediately--I don't know what the team in the UK is doing, if they're redoing anything etc.

**Comment by bakerac4** [comment]
Just to be clear, can you give me the text you want in the box?

**Comment by nrshapiro** [comment]
I am "resetting this" to defer any changes, so just as you had it (and 
how it is in their videos):

Exactly as it looks currently on production.

------ Original Message ------
From: "Adam Baker" ***@***.***>
To: "Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface" 
***@***.***>
Cc: "Neil Shapiro" ***@***.***>; "State change" 
***@***.***>
Sent: 5/3/2021 11:35:54 AM
Subject: Re: 
[Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface] 
SmartSearch - Labeling (#469)
