### ISSUE TITLE
Webx links not able to call server for PDF download

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#499]
We need to be able to implement a download link from the server, and webx should work for that.

![image](https://user-images.githubusercontent.com/4837554/118131563-af427300-b3cc-11eb-977e-e7251ceece4a.png)

In the new system, I've tried variations of webx to accomplish the same, but it's not working.  

Either:
`<webx target="https://stage-api.pep-web.rocks/v2/Documents/Downloads/PDFORIG/ANIJP-CHI.001.0018A/">Click here to open the PDF in another tab or window</webx>`

or the latest style, suggested by Alan (leaving off the domain):

`<webx target="/v2/Documents/Downloads/PDFORIG/ANIJP-CHI.001.0003A/">Click here to open the PDF in another tab or window</webx>`

Produces the same result I see in inspect:

`<a class="webx" data-type="web-link" data-url="" target="_blank" href="">Click here to open the PDF in another tab or window</a>
`

**Comment by bakerac4** [comment]
@nrshapiro I can fix this on my side by looking for the target property on a webx item. Or you can just add the url property that other webx items have and it should work?

Thoughts?

**Comment by nrshapiro** [comment]
@bakerac4  Nope, my stupid mistake...doing too many things, too quickly didn't even see the URL attribute.  I'll switch that and make sure it works before closing, but all should be good.

**Comment by nrshapiro** [comment]
@bakerac4 Ok, now that I'm past the silly error, I am back to my original problem...

How can I trigger a download from a link, similar to the download menu item?

I was thinking I could embed the URL: e.g., using

/v2/Documents/Downloads/PDFORIG/ANIJP-CHI.001.0101A/

But the current permissions aren't added, as you must automatically do if I use the download menu.  Is there a way to trigger the download original PDF button in a link?

If there's no easy way, I can just change the instructions to use the download button.  it's just that we did this with a button in the document last time (not the text link I'm using now, but rather we used a button picture). 

There's not a lot of these, so it's not worth any real trouble.

**Comment by bakerac4** [comment]
@nrshapiro I believe if you add the client ID and the sessionID to the url it would work. You also should use the full path.

i.e.
https://stage-api.pep-web.rocks/v2/Documents/Downloads/PDF/ANIJP-CHI.001.0002A/?client-id=2&client-session=42166250-34d2-4a3f-93db-bb7b21607d75

**Comment by nrshapiro** [comment]
@bakerac4 This is a link, virtually exactly like the download button, for an end user, at their permission level and with their session.  I can't preembed that in the XML.

If there's no easy/straightforward way to do it, that's fine, I will just change the message to read "To read the full-document, download the original PDF from the menu above" or something like that.

**Comment by bakerac4** [comment]
Yea I figured since you had the users session you could append it to the url when you send it down? If thats not the case, your probably better of changing the message to what you mention above
