### ISSUE TITLE
SmartSearch is available in the Server

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#5]
The top/main search entry edit field does not do pararagraph level search, as it should.  Moreover, this main edit field is slated to implement SmartSearch per the spec.  The smarttext field of v2/search will handle this for you.

Although originally assumed the smart text recognition would be done by the client, while we were waiting to go to contract, I went ahead and implemented a SmartSearch feature is in the OPAS Server -- as of the 2020-08-05 build.

SmartSearch has it's own endpoint (mainly to present it with a smaller set of additional parameters, but the exact same functionality appears in the v2/Search endpoint via the smarttext query parameter.

smarttext/smartsearch automatically detects the input per the client spec section 2.3.1.2, e.g.,

1) it does paragraph level search for terms, booleans, and phrases
2) it recognizes a standard bibliographic citation, e.g., Lewin (1952)  - with a fair amount of non-standard variants of this
3) it recognizes a DOI, e.g. 10.1111/j.1745-8315.2012.00606.x
4) it recognizes a direct PEP reference, e.g., PPERSP.002A.0005A
5) it recognizes simple Solr field:value syntax (assuming correct field names, etc.): e.g., 
      - caption_text_xml:freud
      - reference_count:[* TO 20] 
      - NOTE: it does not currently allow boolean combinations of these
6) it recognizes an APA style bibliographic reference: LEWIN, B. 1952 'Phobic Symptoms and Dream Interpretation.' Psychoanal. Q. 21

If it doesn't understand the input, it does a text search for it.  Not always what the user wants, but overall, "pretty smart", and it can grow from there (not self-learning unfortunately :) )  

Caveats:
1. smarttext should generally not be used with other full-text search fields in the search...some other field combinations, depending on the smartext search, may end up contradicting each other and resulting in 0 hits.  Generally, depending on the smartsearch input, smarttext ends up in the q or fq parameter.  Other input fields, which end up in the "other" of these two should work in combination.  In other words, a smartsearch which ends up in the query field, works with other parameters which end up in the filter query (fq) parameter of the Solr search.  However, in cases where smartsearch ends up in fq, then it may also work with other fqs via automatic boolean combinations.
2.  It is possible, when using Solr syntax as input with incorrect field names etc (or if the user tricks it by similar syntax) for the server to return a Solr search error to the client, so be sure and error trap when reviewing the server responses.

With feedback and usage, I will continue to try to improve this feature.

**Comment by billdami** [comment]
@nrshapiro I've started working on implementing SmarthSearch and more of the other functional requirements of the main Search form panel, and had a few questions. Note that all of this is assuming we are using the `GET /v2/Database/Search/` endpoint for all search requests from this form:

 > The top/main search entry edit field does not do paragraph level search, as it should  

What do we need to do to enable paragraph search on `/v2/Database/Search/` requests, or will switching this to use the new `smartsearch` param take care of this for us?

- **2.3.1.2. #1 "Word Wheel"** - this sounds like a type-ahead type control for search fields, but not 100% sure, so need a bit more guidance on what the expected user experience/UI for that. (any example in the current PEP app, or other web sites/apps would be helpful too)
  1. Also, if it is a type-ahead, does it need to match only the currently "active" word, or the entire field value (i.e. input value is "red blu", does the search send just "blu", or "red blu"?) 
  2. Need more specifics on exactly what `field` param the requests should be searching on (or is this something the user should be able to control?). 
  3. Finally, exactly what fields/inputs should this functionality be present on?
- **2.3.1.2 #4d. "Direct Reference"** - While it sounds like the API will handle the majority of the logic for SmartSearch, do you still want the frontend to handle this functionality of jumping to an exact article? And if so, do you have a more exact pattern/regex that we can use to check for these PEP locator values?
- **2.3.1.2. #5d ("Fielded search" controls)** - Can you give some example search request urls/query strings (on the /v2/Database/Search endpoint) for searches using these fields (fields **i.-vi.**). Examples with multiple/dupe fields would be very helpful.
- **2.3.1.2. #5g (full-text fielded​ search params)** - Are the currently in use params for these fields (`?title=` and `?author=`) the correct ones to use for the full-text fielded searches required here? Is there any complications to having these fields in a search along with the **#5d** "paragraph level" search fields (i.e. dreams, quotes, etc) in the same request?
- **2.3.1.2. #6d.ii. ("Viewed at least X times" field)** - how should the `<select>{week, month, six months, year}</select>` value translate into the api request param value, i.e. there is a `viewcount` param for the actual number, but what param is used for the time range part?

**Comment by billdami** [comment]
Additional questions (I'm just logging these here as I come across them, but if you'd prefer a separate issue for general search related stuff, let me  know):

- **2.3.1.2. 5i Year field** - What param does this map to? I only see `startyear` and `endyear` params, which we already have implemented in the UI as  separate options, is this sufficient? 
- **2.3.1.2. 5d** - What `parascope` value is used for vi. "Everywhere"? And is the parascope value for  iii. "References" 'biblios'?

**Comment by billdami** [comment]
Leaving some more follow up questions here (@nrshapiro saw your email, I think Alan is working on your answer for that, so you can just add these to your example requests as you can, thanks!)

* What query params/fields should returned facet field values be used in when refining searches for the following facet types: "art_kwds", "glossary_terms", "glossary_group_terms", "art_cited_all"? When multiple values of those facet types are selected, how should they be joined in the request?
*  How should multiple value selections of the "art_sourcetitleabbr" facet type be joined together in the "sourcename" query param?

**Comment by nrshapiro** [comment]
@billdami 

Since the response required is is long, and I have a busy day, let me answer in parts, which will get you some answers more quickly.

> @nrshapiro I've started working on implementing SmarthSearch and more of the other functional requirements of the main Search form panel, and had a few questions. Note that all of this is assuming we are using the `GET /v2/Database/Search/` endpoint for all search requests from this form:
> 
> > The top/main search entry edit field does not do paragraph level search, as it should
> 
> What do we need to do to enable paragraph search on `/v2/Database/Search/` requests, or will switching this to use the new `smartsearch` param take care of this for us?

Two answers. 1) Yes, smartsearch will take care of that for the edit we specified to be generic 2) to do regular paragraph search, simply use the paratext parameter rather than the fulltext parameter in the search call.  

However, the method we use to do **true** paragraph searching produces a complicated solr syntax.  This makes it somewhat difficult to combine with other word search conditions if specific field conditions are specified (the additional fields).  

The server tries to handle that as best it can with the offered parameters.  And it shows you what it sends to Solr in the responseinfo field, for development/debugging purposes.  (You can see this easily on the /docs interactive page.) 

The general way to understand how things work (and what might now work as expected)

There are two Solr areas offered: q (query) and fq (filterquery).  And there are two levels of data in the solr schema, art_level:1 (document) and art_level:2 (paragraphs)

True within paragraph searching is done at art_level:2, but then in a complicated Solr syntax, it needs to get the parent information from Level1. An example of this:

Search for: 
   - level headed in paragraphs AND
   - family man in paragraphs

I don't recall right now if we asked you to add "OR" logic between fields, so lets' assume not for now,  

So this is equivalent to:

  - level headed in paragraphs AND family man in paragraphs

which is the same as 

  - level headed family man in paragraphs

since by default, we have Solr set to AND connections (there are ways to change this in the client).

What you'll see in the scopeQuery in response info if you submit this is:

     "scopeQuery": [
             [
               "{!parent which='art_level:1'} art_level:2 && ((parent_tag:(p_body || p_summaries || p_appxs) && para:(level headed family man)))",
               "*:*"
             ]

that field is there to help developers using the API to understand what the server did to their parameters for Solr.  The first item in the list is q and the second is fq (a filter, for which you won't see hitmarkers).  If you also specified a journal source, it would look like this:

      "scopeQuery": [
        [
          "{!parent which='art_level:1'} art_level:2 && ((parent_tag:(p_body || p_summaries || p_appxs) && para:(level headed || family man)))",
          "art_sourcecode:(IJP)"
        ]
      ],

add an author name?  This results:

      "scopeQuery": [
        [
          "{!parent which='art_level:1'} art_level:2 && ((parent_tag:(p_body || p_summaries || p_appxs) && para:(level headed || family man)))",
          "art_sourcecode:(IJP) && (art_authors_text:(Katz) || art_authors_citation:(Katz))"
        ]
      ],

Now if you wanted paragraphs with 

   - level headed in paragraphs OR family man in paragraphs

you would submit, in the paratext field:

```
level headed OR family man
```
and the resulting scopQuery: 

    "scopeQuery": [
        [
          "{!parent which='art_level:1'} art_level:2 && ((parent_tag:(p_body || p_summaries || p_appxs) && para:(level headed || family man)))",
          "art_sourcecode:(IJP) && (art_authors_text:(Katz) || art_authors_citation:(Katz))"
        ]
      ],

Results in  15 hits

Depending on the parameters you pick, OPAS will try to come up with the best legal way to submit the query to Solr, even moving some text search areas to the filter area.   But since there's no way to enter two different scopes for the paratext parameter, they both have to be in the same one.  So you can't combine a paragraph search for a phrase in Dreams with one in Quotes.  

For more complicated queries, involving multiple paragraph level searches, the Termlist was born.  But I'm going to leave that for later discussion.  

    Note: recently, this was renamed qtermlist (for query term list).  For discussion purposes, I'll probably use the generic version, termlist. One reason for the rename is that in another endpoint, there's a parameter which is actually a simple comma separated list of terms...that one is still called termlist.  qtermlist is defined as one of the data models SolrQueryTermList which you can see along with the other models in the bottom of the docs page, as well as in models.py in the source code.

But you can easily combine paratext search (or smarttext) with all fields, which as you might expect, are simply filters (the metadata fields).  There are a places where smarttext crosses boundaries there, and again, the server tries to be smart (heh) about it, and it should work fine, but it's pretty new, so we'll see what happens and tighten it up as we go along.

There's yet another option for complicated queries which is easy to explain...it's not a perfectly accurate paragraph search, but it's much less complicated to build from the main parameters (and in fact, it's what GVPi does).  Simply take anything that's a paragraph level phrase in your form, and send it to the server in the boolean combination as a proximity search with a distance of 25.

So if you wanted paragraphs with 

   - level headed in paragraphs OR family man in paragraphs

you would submit, in the fulltext1 field:

```
  "level headed"~25 OR "family man"~25
```
And this would produce:
```
  "scopeQuery": [
        [
          "text:(\"level headed\"~25 || \"family man\"~25)",
          "art_level:1"
        ]
      ],
```
again 15 hits

If you wanted paragraphs with 

   - level headed in paragraphs OR family man in quotes

You can put both in fulltext1 as follows:

and that will result in a scope query of:
```
      "scopeQuery": [
        [
          "text:\"level headed\"~25 || quotes_xml:\"family man\"~25",
          "art_level:1"
        ]
      ],
```

again 15 hits

Summary: The server offers quite a few ways to send in the search, from a simple parameter approach, to a termlist approach, to an advanced solr syntax based search (AdvancedSearch) where you supply the query, all of which produce the exact same response format, to make life easier, despite the decisions.

termlist is worthy of a separate explanation and discussion.  Soon, and I will do that with examples in PostMan.

Fields that you can use for level 1 search in fulltext1 specs:
```
Full document - text
Tagged as Quotes: quotes_xml
Tagged as speaker dialogs: dialogs_xml
Tagged as notes: notes_xml
Tagged as Panel Discussions: panels_xml  
Tagged as Dreams: dreams_xml
Tagged as Poems: poems_xml
Data in an XML tagged Table: tables_xml
In the bibliography section: references_xml
```
You can see all of these text_general fields in masterPEPWebDocsSchema.xml, the Solr schema for the pepwebdocs Solr core.

Note: Any field in the schema which does not have a _syn suffix equivalent is NOT synonym enabled.  We can add them, but right now, the main one is the text field.  A few others: title/title_syn, para (level:2) and para_syn (level:2).

> * **2.3.1.2. #1 "Word Wheel"** - this sounds like a type-ahead type control for search fields, but not 100% sure, so need a bit more guidance on what the expected user experience/UI for that. (any example in the current PEP app, or other web sites/apps would be helpful too)
>   
>   1. Also, if it is a type-ahead, does it need to match only the currently "active" word, or the entire field value (i.e. input value is "red blu", does the search send just "blu", or "red blu"?)

Yes, it's for type ahead, but since it uses Solr's term index, it is only for a word at a time. blu only shows full expansion of blue.  I don't see a facility within Solr to do full strings that way, at least to date.  It would likely need to be a string field. 

>   2. Need more specifics on exactly what `field` param the requests should be searching on (or is this something the user should be able to control?).

It depends on what field you need the terms list for.  By default, it's the full-text field, aka "text".  But it can also be used for author fields, any full-text field in the schema, for example, all the ones listed above, any text_general or string_ci field (string_ci was meant to be just string, not full-text, but Solr doesn't offer a case insensitive option on real strings (which if you just convert them on loading, doesn't help, because then the return value is no longer in the original case).

All for now...stay tuned for a termlist discussion, which may in fact be your best option for combining lots of fields.

**Comment by nrshapiro** [comment]
> Additional questions (I'm just logging these here as I come across them, but if you'd prefer a separate issue for general search related stuff, let me know):
> 
> * **2.3.1.2. 5i Year field** - What param does this map to? I only see `startyear` and `endyear` params, which we already have implemented in the UI as  separate options, is this sufficient?
> * **2.3.1.2. 5d** - What `parascope` values are used for ii. "Quotes" and  vi. "Everywhere" (currently "Everywhere" is just mapped directly to the `fulltext1` param, let me know if thats incorrect)? And is the parascope value for  iii. "References" 'biblios'?

You can use both startyear and endyear for a range, but I hate that in our current GVPI system from a users point of view.  So you can just use start with some qualifiers. as it says on the Docs page, start can be a single year, a range, < or > (e.g, 1999, Between range: 1999-2010. After: >1999 Before: <1999)

Personally, I think that's easier for users!  And saves having them separate.  But if you want to also offer and End field, as an option, that's exactly what the API does.  You can use either or both (but I think if you use one of the special forms in the start field, it will ignore the end field.

See my last note...it gives the various scopes.

**Comment by nrshapiro** [comment]
> * **2.3.1.2 #4d. "Direct Reference"** - While it sounds like the API will handle the majority of the logic for SmartSearch, do you still want the frontend to handle this functionality of jumping to an exact article? And if so, do you have a more exact pattern/regex that we can use to check for these PEP locator values?

Smarttext handles that without you doing anything else.

**Comment by nrshapiro** [comment]
> * **2.3.1.2. #5d ("Fielded search" controls)** - Can you give some example search request urls/query strings (on the /v2/Database/Search endpoint) for searches using these fields (fields **i.-vi.**). Examples with multiple/dupe fields would be very helpful.
> * **2.3.1.2. #5g (full-text fielded​ search params)** - Are the currently in use params for these fields (`?title=` and `?author=`) the correct ones to use for the full-text fielded searches required here? Is there any complications to having these fields in a search along with the **#5d** "paragraph level" search fields (i.e. dreams, quotes, etc) in the same request?

@billdami  This is a perfect place to talk about termlist (qtermlist).  But later!  [PLACEHOLDER] [TODO]

**Comment by nrshapiro** [comment]
> * **2.3.1.2. #6d.ii. ("Viewed at least X times" field)** - how should the `<select>{week, month, six months, year}</select>` value translate into the api request param value, i.e. there is a `viewcount` param for the actual number, but what param is used for the time range part?

@billdami This is a perfect place to talk about termlist (qtermlist). But later! [PLACEHOLDER] [TODO]

**Comment by billdami** [comment]
> > * **2.3.1.2 #4d. "Direct Reference"** - While it sounds like the API will handle the majority of the logic for SmartSearch, do you still want the frontend to handle this functionality of jumping to an exact article? And if so, do you have a more exact pattern/regex that we can use to check for these PEP locator values?
> 
> @billdami
> Smarttext handles that without you doing anything else.

@nrshapiro I'm assuming you mean Smarttext handles recognizing the PEP locator string and returns the exact article match in the response? I guess what my question was more about was this part:
> the APP shall recognize it and jump to that article

Which sounds like a client/UI controlled behavior, where in the case a single exact match for a given locator ID is returned, the client should immediately redirect the user to the Read (or Preview pane) view for that article instead of display the results list (of 1 item)? If thats the case, should the client also know what the PEP locator pattern is, so that it can correctly redirect in only these cases (instead of anytime only 1 result is returned), or will the API response contain some sort of flag/field indicating it is a "Direct Reference" match?

**Comment by nrshapiro** [comment]
@billdami 

> 2.3.1.2. #5d ("Fielded search" controls) - Can you give some example search request urls/query strings (on the /v2/Database/Search endpoint) for searches using these fields (fields i.-vi.). Examples with multiple/dupe fields would be very helpful.

There's yet another option for complicated queries which is easy to explain...it's not a perfectly accurate paragraph search, but it's much less complicated to build from the main parameters (and in fact, it's what GVPi does). Simply take anything that's a paragraph level phrase in your form, and send it to the server in the boolean combination as a proximity search with a distance of 25.

For this release, as I've been thinking about it, I think it is best for you to use this approach.  
Also, in thinking about the multifielded interface we specified, I realize we need to use a syntax which is currently a limitation of Solr: as far as I've been able to tell, you can't use multiple fields in an ANDed fashion using Solr child documents as we are doing for paragraph searching (OR works fine, and if you use multiple paragraph level fields, the server OR's them...but that's not what we want here).  In comparison, if you use `simulated paragraph searching` as I described before, you can easily represent the searches you need.  It's not as accurate as the other approach, since it's an approximation of a paragraph, but it's what GVPi is doing with the current PEP-Web system anyway, so for this alpha at the very least, it should be fine.

Here's an example of a multifield, paragraph level search.  Suppose your user selects dreams in one field, everywhere in another, and dialogs in the third.  Just map it to the following fulltext1 query:

   `dreams_xml:(mother) AND text:("little girl"~25) AND dialogs_xml:(feeling)`

1) Each field goes in one boolean clause
2) You can repeat the same field more than once if they specify two dreams fields, for example
3) In any field where they supply more than one word, use `""~25` around it. 
4) In any field where they use quotes, for a phrase, leave off the ~25 (which is a proximity operator)
5) You can still use any of the filter query (metadata) type fields separately, and they combined and automatically placed in the fq portion of the query to Solr.  There's no reason to need multiple fields there, since each of those maps to a specific field, and you can use boolean logic within those fields.
6) Smartsearch may not always combine well with the above...but it might...I will have to do some testing (see example below).

The current fulltext1 parameter will take and process this query as above, just fine.  The URL it generates:

https://stage-api.pep-web.rocks/v2/Database/Search/?fulltext1=dreams_xml%3A%28mother%29%20AND%20text%3A%28%22little%20girl%22~25%29%20AND%20dialogs_xml%3A%28feeling%29&viewperiod=4&formatrequested=HTML&facetmincount=1&facetlimit=15&sort=score%20desc&limit=15

Here's a similar example with two dialog fields:

`dreams_xml:(mother) AND text:("little girl"~25) AND dialogs_xml:(feeling) and dialogs_xml:(well)`

https://stage-api.pep-web.rocks/v2/Database/Search/?fulltext1=dreams_xml%3A%28mother%29%20AND%20text%3A%28%22little%20girl%22~25%29%20AND%20dialogs_xml%3A%28feeling%29%20and%20dialogs_xml%3A%28well%29&viewperiod=4&formatrequested=HTML&facetmincount=1&facetlimit=15&sort=score%20desc&limit=15

So this is very easy and straightforward.  Not perfect, but sometimes straightforward is best.

I just did one smarttext test with it, adding `Berent, I. (1973)` to the smarttext field.  I knew that that author and year was in the result set, and indeed, the result is one document if you combine smarttext with the fields.  However, remember, they will be ANDed together, so it's easy to end up with 0!  (And smarttext in combination does not make a lot of sense to me...that's not the purpose of it.)

http://development.org:9100/v2/Database/Search/?fulltext1=dreams_xml%3A%28mother%29%20AND%20text%3A%28%22little%20girl%22~25%29%20AND%20dialogs_xml%3A%28feeling%29&smarttext=Berent%2C%20I.%20%281973%29&viewperiod=4&formatrequested=HTML&facetfields=dreams_xml&facetmincount=1&facetlimit=15&sort=score%20desc&limit=15

This can still be done very easily and straightforward with qtermlists instead of fulltext1.  But until I can write up the examples, you might want to do it this way.   The advantage of the qtermlists is a bit more flexibility, for example selecting individual clauses for synonyms. 

There's only one (temporary) problem with the above queries for our needs.  I wasn't expecting we'd need to do this, so I removed one of the fields from the schema that you'd need at least in the longer term.  It was called art_body_xml, and it represented the body of the document, without the references or abstract, which is what we search currently as "everywhere" for paragraph searches.  For now, just use text, as shown above.  In the next schema build, the missing field for "doc" will be back (though I've renamed it body_xml, to match the other fields for paragraph searching).  (As a reference, just fyi, all of these fields at the document level were removed a few versions ago, but I put them back as an alternative when I realized the AND problem.  I just thought it was more temporary, since I thought I could find a way to make Solr work for ANDing the subdocument queries.)

**Comment by nrshapiro** [comment]
@billdami 
In the current schema development build, I've added _syn fields for all the other fields (search zones).  I'll see during the Tuesday meeting about getting your copy of the Solr database updated.

**Comment by nrshapiro** [comment]
@billdami  

Probably better to do fewer questions (or 1) per issue...I'm sure trying to read the above is more difficult.

**Comment by billdami** [comment]
> * How should multiple value selections of the "art_sourcetitleabbr" facet type be joined together in the "sourcename" query param?
> 
> I think you should keep a source code lookup table of the source titles and use the sourcecodes behind the scenes. You can get that information from the server, of course. There aren't many sources. You could just use the art_sourcetitleabbr, but if you aren't using qtermlists, you'd have to put it as a field: request in smarttext or add it to the fulltext1 parameter as a field: request, but that will look messier. There's no source title abbr query parameter, since I didn't see a real big need to search for this...I expected that would be good for a user, but any program would generally use the more compact sourcecode.

@nrshapiro what would the `field:` value/syntax be for this exactly if we were to use the source abbreviation value directly in the `fulltext1` or `smarttext` param? And would there be any other downsides to doing it this way, besides being a bit messier?

We can fetch the full list of sourcecodes from the server beforehand to create a lookup table if we needed, though we try to keep the number of network requests/chatter down when we can. However, if we had to do this, whats the best way to fetch all sources in a single request? I see there is a `/v2/Metadata/{SourceType}/{SourceCode}/` endpoint in the docs, but looks like for that you need to filter the returned sources by type and code?

**Comment by nrshapiro** [comment]
You can use the Metadata call with wild cards:

Get all the sources:  [https://stage-api.pep-web.rocks/v2/Metadata/%2A/%2A/?limit=300](https://stage-api.pep-web.rocks/v2/Metadata/%2A/%2A/?limit=300)

But generally, you are going to want to separate out books, journals and videos (depends on what you are doing).   In the search panel, we generally list the journals, and then books as one item, and videos as one item.  There are 235 returns to the above call, since that includes books.  If you call [http://stage-api.pep-web.rocks/v2/Metadata/Journals/?sourcecode=%2A&limit=200](http://stage-api.pep-web.rocks/v2/Metadata/Journals/?sourcecode=%2A&limit=200), then you get 78 journals.  Note, you can't do a word wheel exactly like this, but if you include a string in the sourcename parameter, it will return matching journals, so you can do "sort of a word wheel" (though I don't know if it's truly fast enough to be used that way): [](https://stage-api.pep-web.rocks/v2/Metadata/Journals/?sourcecode=%2A&sourcename=international&limit=200).  Though I think we need a bigger faster install of solr which would speed it up.

Those calls will get you all the abbreviations.  I can think about how to do a word wheel for "full strings" like that in a future release.

As to your first question, you can query ANY schema field in the Smarttext or Fulltext1 parameter by the simple syntax fieldname:(search term or phrase).  Use quotes for an exact phrase, as always.

But while you can do that, what I wrote was misleading...that notation is used for searching the _documents_ by field, not the _metadata_ (in other words, it returns a `documentList`, which are all documents from the matching journal, for example.  The Metadata calls on the other hand, return a `sourceinfolist`, which is what you are looking for here.  Different calls for different reasons based on what you want back (my mistake in not redirecting you to metadata calls.)

@adistasio On a side note, the server at stage-api.pep-web.rocks seems especially laggy this morning, at least running through the docs interface.  Even to do simple UI things like open or fold the calls in the Docs page.  Not doing that on api.psybrarian.com or (of course) my local development.org address.  Perhaps a bigger better memory/processor based EC2 should be used?  Definitely need a better one for Solr as well.  I updated all the Psybrarian last night, and Solr ran out of memory there.  Probably the JVM, since it's 512M still.  Should be 1G for starters.  Certainly want better performance for test runs by board members.
