### ISSUE TITLE
Login Prompt Text

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#500]
The text for the various logins which is currently

![image](https://user-images.githubusercontent.com/4837554/118151431-9d1eff80-b3e1-11eb-8c54-1d9386858057.png)

Should urgently be changed, per D. Tuckett, to:

`You have been granted full archive access to PEP because your institution has a valid subscription based on what is called a “Referral/Federated-OpenAthens/IP Address” logon. But to be able to alter the look and feel of the site, save papers, searches and favorites and many other things, you need to become a registered user (which is free). You do that once, then access this site direct using the personal login you create. (Every 90 days you need to come in via your university/institute to re-validate). If you already have a log-in on the PaDS system, use that.  Click here for more details.
`

The link at the end will be to a help page...  @PEPWebAdmin (Angela) please supply here.  Since DT says this is urgent, you can implement and add the link when Angela supplies it.

@adistasio I will submit a separate, in limbo, request, to add this (or these, if they should be kept separate) as an editable feature of Admin per DT's wishes.

cc: @AthenaPEP

**Comment by PEPWebAdmin** [comment]
I've created the help page: http://support.pep-web.org/login-help/ 

Will add further info soon on David's instructions.

**Comment by nrshapiro** [comment]
Labeled it bug so that it can be "urgently implemented"

**Comment by nrshapiro** [comment]
@adistasio, was this done?

**Comment by bakerac4** [comment]
@nrshapiro do you want the item in quotes to be exactly that "Referral/Federated-OpenAthens/IP Address" or what the user is actually signed in through "Referral URL"

**Comment by nrshapiro** [comment]
`...do you want the item in quotes to be exactly that "Referral/Federated-OpenAthens/IP Address" or what the user is actually signed in through "Referral URL"`

I would suspect the more specific one is better if you have it available.  But I'll let @davidtuckett chime in since these are his words.

**Comment by davidtuckett** [comment]
Thanks.

Please use "based on what is called a" and then "Federated" "Referral" or "IP address" as appropriate if that can be specified accurately..

**Comment by nrshapiro** [comment]
@AthenaPEP - Please reply to this issue and let Gavant know exactly what you see is the problem, and what you would like it to say.

The bug report I placed based on David's email is reproduced above.

**Comment by nrshapiro** [comment]
@bakerac4 I assume Athena is talking about the substitution errors in the text.  Since she's on a different time zone, here's a screen shot she emailed me:  

![image](https://user-images.githubusercontent.com/4837554/118552227-a3d4ac00-b72c-11eb-93d4-e52a43b7c689.png)

I don't know how she was logging in.

**Comment by nrshapiro** [comment]
@PEPWebAdmin 

> I've created the help page: http://support.pep-web.org/login-help/
> 
> Will add further info soon on David's instructions.

FYI - Still says information to be provided soon...from your note 12 days ago.  Just a reminder you were you going to update that web page with the info from David?

**Comment by PEPWebAdmin** [comment]
I didn't receive any further information from David on this, unless I have missed it?

**Comment by nrshapiro** [comment]
@davidtuckett @AthenaPEP @PEPWebAdmin 

It looks like they implemented what you said at the top of this issue when Gavant closed the issue (closing an issue means they confirm it's been done).  You should have received an email notification when they closed it, since you are listed on the issue.  Let me know if you didn't, because I assume all assignees receive emails (though I think those emails aren't very clear unless you click on the issue number to see the issue.)

![image](https://user-images.githubusercontent.com/4837554/119734356-df682800-be48-11eb-87ef-88d35edbb080.png)

But to verify what it says so everyone can see more easily than can be done if you are not in an institution (as I am not), I used PaDS to spoof an institutional user and this is what it showed:

<img width="269" alt="2021-05-26_17h00_46" src="https://user-images.githubusercontent.com/4837554/119733721-eb9fb580-be47-11eb-8788-8d7787131ed8.png">

Then I went and changed one of my accounts and enabled IP access (not normally active for me), and the message appeared to be the same, and seems to be what you asked for in this issue.

<img width="1233" alt="Referral Logni Cambridge" src="https://user-images.githubusercontent.com/4837554/119734186-96b06f00-be48-11eb-84de-7945550f7198.png">

You can verify the text yourself, but again, a quick comparison looks right.  

As a final check, the text itself copied from the IP login page, and then below that from the issue above.  They seem to be identical:

From the IP based login
`
You have been granted full archive access to PEP because your institution has a valid subscription based on what is called a “Referral/Federated-OpenAthens/IP Address” logon. But to be able to alter the look and feel of the site, save papers, searches and favorites and many other things, you need to become a registered user (which is free). You do that once, then access this site direct using the personal login you create. (Every 90 days you need to come in via your university/institute to re-validate). If you already have a log-in on the PaDS system, use that. Click here for more details.
`
From the issue above:
`
You have been granted full archive access to PEP because your institution has a valid subscription based on what is called a “Referral/Federated-OpenAthens/IP Address” logon. But to be able to alter the look and feel of the site, save papers, searches and favorites and many other things, you need to become a registered user (which is free). You do that once, then access this site direct using the personal login you create. (Every 90 days you need to come in via your university/institute to re-validate). If you already have a log-in on the PaDS system, use that.  Click here for more details.
`

Also above is a full screen shot if you need it for help pages.

Here's one where I've edited out the default login user id and password text and lastpass icons.  You should be able to right click and save to use it elsewhere,

<img width="1233" alt="Referral Logni Cambridge" src="https://user-images.githubusercontent.com/4837554/119735767-ce201b00-be4a-11eb-807d-0bf7699d3852.png">

See Issue #508 Admin Control of Login Text for the request to be able to edit this other text directly.   (It currently does not show in the control, but I may experiment with it on stage to see why, since they have not answered my query yet.

I've left this issue closed because it appears to have been done properly.

**Comment by AthenaPEP** [comment]
@nrshapiro @davidtuckett @nadinelevinson @PEPWebAdmin 

I don't think this issue has been fully addressed:
1. I actually logged in as an SPI user (PaDS ID 9494) they access via Referrer URL
On the right, the Sign in box, only says Sign in - none of the text appears there.

(I tried to include an screenshot here but only code appears, not the image. For ex. <img width="1130" alt="Screen Shot 2021-05-27 at 8 56 08 PM" src="https://user-images.githubusercontent.com/83027893/119874589-735fef80-bf2e-11eb-9c6b-d5e082ad5ec1.png">)

If you want to test SPI yourself, here is the log in info:
username: athenatsiokris
password: NB!NvO0!UdW2nch)AjI!lvxE
https://www.spiweb.it/area-privata/

2. Can someone test this at UCL both remote access and onsite (if possible)?

3. David advised that in the text 'Referral/Federated-OpenAthens/IP address' should appear as relevant (see notes above).

**Comment by AthenaPEP** [comment]
@nrshapiro @davidtuckett @nadinelevinson @PEPWebAdmin 

I tested by logging in via UCL OpenAthens, again the text does not appear:

<img width="1440" alt="Screen Shot 2021-05-28 at 12 34 22 PM" src="https://user-images.githubusercontent.com/83027893/119963667-0a6d8b80-bfb1-11eb-829f-2f63aca0d497.png">

**Comment by jwoosnam** [comment]
I have also tried this for both a referral and a Federated login.  The user is logged in as a GroupUser but does not see the additional text.  It is working correctly on stage.  

Could it be something someone has changed in the admin/translation settings?

**Comment by nrshapiro** [comment]
> I have also tried this for both a referral and a Federated login. The user is logged in as a GroupUser but does not see the additional text. It is working correctly on stage.
> 
> Could it be something someone has changed in the admin/translation settings?

Good thought...but the strings on Stage and Production are identical.

**Comment by bakerac4** [comment]
What is being sent back as the userType in the request? I suspect its not `Group`. 

In the template where we show the text we have 

```
{{#if this.currentUser.user.isGroup}}
    <div class="mb-2">
        {{html-safe this.cardInfo.groupInformation}}
    </div>
{{/if}}
```

And all that does is check if the userType === 'Group'

```
    /**
     * Is the user part of a group (IP, federated, or referral)
     *
     * @readonly
     * @type {boolean}
     * @memberof User
     */
    get isGroup(): boolean {
        return this.userType === UserType.GROUP;
    }
```

**Comment by bakerac4** [comment]
@nrshapiro I have confirmed two things. 

1.  the userType of group is being returned correctly using Athenas credentials.
2. Your missing the correct item from the admin config. Can you log in as an admin and confirm that the english page has something in that box for Group Information?

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio Sorry Adam, you've lost me there.  There's nothing I see about Group information on the language/English page, at least that I know about.  Just the two areas for login information text.  You can give me a call if you like - 644-4164 as a quicker way to work this out -- we seem to be out of sync!

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

(I was thinking in terms of conditionals--unless you just mean the text here:)

![image](https://user-images.githubusercontent.com/4837554/120017427-de073e80-bfb3-11eb-9b67-bbc2adedb27c.png)

**Comment by nrshapiro** [comment]
@bakerac4 The reason I was thinking conditionals, is that it works under some circumstances, but not others.  Or maybe, as James said, it only works on Stage, because when I use PaDS to feign a federation login, I believe that's on Stage.  But when I use Athena's login credentials (I sent by email), like her, I see nothing.  But that's on Production.

**Comment by bakerac4** [comment]
@nrshapiro what Im saying is that https://pep-web.rocks/ does not have the Sign in card "Group Information Header" being returned. So if you log into prod and go to the admin english page is there anything in the Group Information Header box?

**Comment by nrshapiro** [comment]
Yes, that's a screen capture of it I posted.

**Comment by bakerac4** [comment]
Interesting, can you check the database?

To see how I know it's not being returned just take a look at the source. 

Just put the following in your URL bar and search for `groupInformation`

view-source:https://pep-web.rocks/
view-source:https://stage.pep-web.rocks/

stage has 1 occurence found and prod does not

**Comment by nrshapiro** [comment]
Yes, I just thought of that and checked--and oddly, it's not there.  That would be easy to fix, but now I want to check if there are other differences, since I sent that to translation yesterday.  How could it show up in the Prod admin if it's not in the database?

**Comment by bakerac4** [comment]
Im not quite sure. I could take a look if you want me to dive in deeper. But for now I think if you just go and add it to each language (probably just even hitting the save button) it should work again

**Comment by nrshapiro** [comment]
Ok, I deleted the adminSpecifiedInformationItems test there, and saved to verify it's saving correctly to the right database (I was wondering if it could have been reading the stage database.)  But it works.  So that item should now be there.

No need to deep dive.  Can you tell me though what adminSpecifiedInformationItems is for?

**Comment by bakerac4** [comment]
@nrshapiro its for https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/415.

You can add the ID, i.e. 'login' and the value of whatever text you want to show. Then when you go to PEP with a query param of `?information=login` a modal will open with the text.

**Comment by nrshapiro** [comment]
@AthenaPEP @davidtuckett 

After fixing the database for production (explains why it was working on Staging but not Production) the SPI link correctly shows the text.  You can retest UCL, but it should be the same.

![image](https://user-images.githubusercontent.com/4837554/120021873-9f748280-bfb9-11eb-9b9e-d774a7664a30.png)

**Comment by AthenaPEP** [comment]
@nrshapiro @davidtuckett @nadinelevinson 
Tested UCL and everything is working fine.
