### ISSUE TITLE
Admin Control of Login Text

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#508]
All the variations of login messages (see #500) should be editable in Admin.

**Comment by nrshapiro** [comment]
@adistasio   Just opening it to make sure--the text the app was displaying for the various "other" logins that this now controls needs to be placed in the admin panel area...it just says "test" now.  Since I don't have that text handy, can you please place it there so users don't see text?  Was there only one area of the "other" login text?  I though there were two?

I wanted to get the facet fixes out there and I've pushed everything to production.

**Comment by nrshapiro** [comment]
@adistasio I looked at the login text on the various pages, and it does not appear to have changed to "test".  I'm going to experiment a bit with stage to confirm that this new area controls the text.

**Comment by bakerac4** [comment]
@nrshapiro I believe that was just a test of my work that ended up on stage. You should be able to delete that item
