### ISSUE TITLE
glossary infocard implementation

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#51]
How does the glossary infocard get its data?  It looks like the same terms are being used over and over, just the size of them is varying.  I would expect to see markedly different documents use different terms.

**Comment by bakerac4** [comment]
We are using the `facetCounts.facet_fields.glossary_group_terms` to populate the glossary terms. I just double checked again and it seems to be working well on my end.

**Comment by nrshapiro** [comment]
Yes, I see...it was staying constant as I walked through search records.  But that may have been before the last client update, or some other fluke.  Towards improved issues, I will try to include client version with reports.
