### ISSUE TITLE
Publisher Infocard information flow not done in a useful manner.

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#52]
First, I understand that the publisher info itself is not yet available to you.

But the design of the information flow for the card is not right.  It's not worth the space to just have a link in the card to more information.  That can be done more efficiently and easily by just putting a link on the journal information in the article header.

What it needs to finally do when implemented is to show the publisher information in the card, per the description in the spec.

**Comment by billdami** [comment]
@nrshapiro fwiw, I believe the card is already implemented to allow showing publisher info directly in the card itself. 

We have  an admin config field created for each publisher (that are not yet populated) to hold HTML to show directly in the card, as well as another field for "expanded info" to show in that dialog popup if needed.

**Comment by bakerac4** [comment]
@nrshapiro, @billdami is correct. I have implemented that to show a preview HTML and that link. I made that design choice after seeing the size of the publisher information. I would caution against putting that much info into a card (even if the pane is scrollable) as it becomes harder to read due to the constrained width and less useful the more you put in.

**Comment by nrshapiro** [comment]
@billdami 

We will make sure the publisher information fits and is readable.  Other than the page we have for IJPOpen, we have minimal information for each.  Here are a few examples.  Please put them in the corresponding areas so we can demonstrate the card.  

## American Imago `(PEPCode: AIM)`

American Imago was founded by Sigmund Freud and Hanns Sachs in the U.S. in 1939 as the successor to Imago, founded by Freud, Sachs, and Otto Rank in Vienna in 1912. Having celebrated its centenary anniversary in 2012, the journal retains its luster as the leading scholarly journal of psychoanalysis. Each issue features cutting-edge articles that explore the enduring relevance of Freud's legacy across the humanities, arts, and social sciences.

Editor
Murray M. Schwartz

Associate Editor for Film
Catherine Portuges

Associate Editors
Vera J. Camden

David Willbern

Managing Editor
Melissa Skepko


PUBLISHED BY Johns Hopkins University Press

## fort da `(PEPCode: FD)`

A Regional Affiliate of the Division of Psychoanalysis (39), American Psychological Association

fort da is a psychoanalytic journal that provides a forum for San Francisco Bay Area professionals as well as national and international thinkers and clinicians. fort da publishes work on psychoanalytic theory, practice, research, and applied psychoanalysis -- in the form of articles, reviews, interviews, essays, commentary, and poetry.

fort da encourages writers to present their ideas and views on psychoanalysis, both inside and outside the consulting room, giving voice to the multiple ways in which psychoanalytic thinking enriches life. We support creative, evocative, and associational styles rather than a strictly academic format, encouraging material that is at once accessible, lively and of a high intellectual standard.

## Revue française de psychanalyse: 1927-current  `(PEPCode: RFP)`

The leading French Journal since 1927 and a repository of many of the most important articles in our discipline. Check out the articles by Freud, Lacan, Green, Chasseguet-Smirgel, McDougall, Viderman and many many more. Thanks are due to Denys Ribas (Former editor and President SPP), the Paris Psychoanalytic Society and their library and librarians (SPP), Christine Mique-Bez and Charles Ruelle (Presses Universitaires de France).

## Psychoanalytic Psychology `(PEPCode: PPSY)`

Psychoanalytic Psychology serves as a resource for original contributions that reflect and broaden the interaction between psychoanalysis and psychology. Manuscripts that involve issues in psychology raised by psychoanalysis and issues in psychoanalysis raised by psychology are welcome.

The journal, a quarterly, publishes research papers, clinical papers, literature reviews, clinical notes, brief reports, commentary and book reviews. 

Editor: Elliot L. Jurist
Publisher: APA PsycNET

## Division Review `(PEPCode: DR)`

DIVISION/Review is a forum for review essays, commentary, interviews and discussion in the field of psychoanalysis. It is open to viewpoints from across the spectrum of psychoanalytic schools and disciplines. DIVISION/Review primarily addresses topics related to clinical psychoanalysis but also cultural and intellectual fields beyond that focus.

The full text of this journal is available up through the current issue for all PEP Archive subscribers.

## Chinese Annual of the International Journal of Psychoanalysis

The Chinese Annual carries a selection of papers from The International Journal of Psychoanalysis, chosen by the board of the Chinese Annual and translated each year. Articles are fully searchable, and available for download to subscribers as PDFs.

To read the full text of articles you need a current subscription to the journal. For more information on this new journal and how to subscribe, please visit the PEP-Web support pages.

2017年新品！中文版年刊是从《国际精神分析杂志》中精选的论文中文翻译版本。文章可完全搜索，并可以PDF格式下载到订阅者。

要阅读文章的全文，您需要当前订阅期刊。有关此新期刊和如何订阅的更多信息，请访问 PEP-Web支持页面。


## Psychoanalytic Books: 1990-1999 `(PEPCode: PB)`

Joseph Reppen’s journal, Psychoanalytic Books, is a compendium of reviews of the important books of its era, the 1990’s, written by many of the best scholars in our field.

## Psikanaliz Yazıları (Psychoanalytic Writings): 2000-current

Launched in 2000, Psychoanalytic Writings is the first Turkish-language periodical on psychoanalysis. It’s published biannually, in spring and autumn, by Istanbul Psychoanalytical Association, the first component society of IPA in Turkey and its region. Psychoanalytic Writings has played, and continues to play, an important role in promoting psychoanalysis in Turkey, and establishing ties between psychoanalysis and related disciplines. The Turkish-language journal publishes the articles of prominent psychoanalysts from Turkey and various other countries.

Psikanaliz Yazıları 2000 yılından bu yana Türkiye’de psikanaliz ile ilgili düzenli yayınlanan ilk süreli yayındır. İlkbahar ve sonbaharda olmak üzere yılda iki kez yayımlanmaktadır. Türkiye ve yakın coğrafyada,  IPA’ya doğrudan üye ilk dernek olan İstanbul Psikanaliz Derneği’nin psikanalizin tanınması, yayılması ve farklı disiplinlerle ilişkilenmesi çalışmalarında  önemli rol üstlenmiş olan Psikanaliz Yazıları, Türkiyeli yazarlar yanında  bir çok başka ülkeden değerli psikanalistlerin orijinal yazılarını da (Türkçe olarak) yayınlamış ve yayınlamaya devam etmektedir.
