### ISSUE TITLE
PEP-Web Support for Librarians and OpenURL

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#523]
The GVPi PEP-Web interface supports openURL syntax per this page:

    http://support.pep-web.org/further-support/for-librarians/

Basically, what this means is providing search parameters per OpenURL syntax, e.g.,

    http://www.pep-web.org/search.php?sid=PEP:PEPWeb&atitle=war&date=1997

This was not listed as a requirement for the current client.  If we want to continue to support it, it will have to be added.

However, the OPAS server does support this syntax (see the interactive Docs, illustrated below).  The only problem is that we still need to implement a front end through the client.

This is entered here as a future work item if continued OpenURL support is needed per our librarian base.

![image](https://user-images.githubusercontent.com/4837554/119674676-6518b300-be0a-11eb-926d-ccb6cce6e650.png)

**Comment by SophieMBennett** [comment]
@nadinelevinson @ocappello For reference re: openURL syntax

**Comment by bakerac4** [comment]
@nrshapiro I think we need more information here. What in specific are you asking the client to implement? Could you give a few examples of what should work?

**Comment by nrshapiro** [comment]
@bakerac4 the sid is not required in the 0.1 spec but is highly recommended.  It would be important if we had more than one database on our URL.  We can require it.  

FYI, the 0.1 spec (which is really old and outdated) is here: https://biblio.ugent.be/publication/760060/file/760063.pdf

But that's what was implemented before, and it's very straightforward.

**Comment by nrshapiro** [comment]
For the record, they're very quick response was:

**Comment by bakerac4** [comment]
Some questions to think about - what happens if someone copies a url with our search params and adds openUrl params too it. i.e. 

```
search?searchTerms=%5B%7B"type"%3A"title"%2C"term"%3A"test"%7D%5D&title=Gender+and+Psychoanalysis
```

**Comment by nrshapiro** [comment]
@bakerac4 

I guess that would depend on how you are handling incorrect parameters in general.  What do you do when someone makes a legal request but also enters a parameter from another system (not openURL) to the URL?  Or if someone adds an OpenURL >0.1 parameter we don't yet support?

I just tried that on Stage and the current system ignored it.  Here's what I tried:

https://stage.pep-web.org/search?searchTerms=%5B%7B%22type%22%3A%22article%22%2C%22term%22%3A%22gloat%22%7D%2C%7B%22type%22%3A%22title%22%2C%22term%22%3A%22child%22%7D%5D&title=goat

If you are requiring the sid for openURL, then that's the only time I would assume you would expect to get OpenURL parameters.  You can't mix and match especially if the parameters may not have the same meaning.

**Comment by nrshapiro** [comment]
@bakerac4 

To cover these just using v2/Database/Search you are going to have to use SmartText in a couple of places.

aulast/aufirst (both mapped to full author name) - api search author
issn/eissn - api search smartText param issn:
isbn: - api search smartText param  isbn:
title/stitle (journal or book title) api search param: sourcename
atitle (article title)  api search param: title
volume api search param: volume
issue   api search param: issue
pages: api search smartText param: either art_pgrg:{start}-{end}, or art_pgrg:{start}-*, or art_pgrg:*-{end}, or absolute, art_pgrg:5-10
date: we don't have real "dates" (mm/dd/yy) per se.  This is equivalent to year as the app uses it.  Use startyear, it has flexible syntax per the api doc.

**Comment by bakerac4** [comment]
@nrshapiro thanks. Just wanted to confirm you guys are happy with the proposed solution before I start though!

**Comment by nrshapiro** [comment]
@bakerac4 

Although I'm not sure what users coming from OpenURL links are expecting, I think it works because after the link, they may want to narrow the results using the search form and the refine area.  

I do worry that this solution may make it somewhat more difficult to upgrade to a newer version of OpenURL should that ever be required.  But I don't see that's required right now, and it likely could be handled at worst by upgrades to both server and client.  

What's important is the user experience, and I think this works for them.

**Comment by bakerac4** [comment]
@nrshapiro how do I combine smart searches again. I.e. if the user gave us an `issn` and the `pages`?

Also it doesn't seem like we currently have SearchTermId's for `ISSUE` or `SOURCE_NAME` so I wanted to make sure those were right.

```export enum SearchTermId {
    EVERYWHERE = 'everywhere',
    AUTHOR = 'author',
    TITLE = 'title',
    DREAM = 'dream',
    QUOTE = 'quote',
    REFERENCE = 'reference',
    DIALOG = 'dialog',
    ARTICLE = 'article',
    START_YEAR = 'startYear',
    END_YEAR = 'endYear',
    CITED = 'cited',
    VIEWED = 'viewed',
    VOLUME = 'volume',
    SOURCE_CODE = 'sourcecode'
}
```

**Comment by davidtuckett** [comment]
I just want to mention that I am not sufficiently clear to comment in all this so rely on you all.

**Comment by nrshapiro** [comment]
@bakerac4

1) Sorry, you will need to use the advanced form of smarttext if you want to use Boolean syntax (the only negative is the server leaves the names alone, so no alias names, you need to use Solr field names from our schema, but in this case we're only talking about three).  The syntax is simple, you just need to prefix the boolean search with adv::   E.g.,

adv::art_isbn:0415069939 AND art_pgrg:102-*

or 

adv::art_issn:0002-9548 AND art_pgrg:102-*

All the other schema fields are possible, but in this case you only need:

art_issn
art_isbn
art_pgrg

Sorry, while the server returns pgStart and pgEnd in the return model, we don't save start page and end page separately in the Solr schema, so you need to use art_pgrg even when you just have one of the values.

2) I gave the proper _Parameter_ names in my previous message.  See https://stage-api.pep-web.org/docs#/ for the friendlier version, or the function header code below 
```
async def database_search(response: Response, 
                              request: Request=Query(None, title=opasConfig.TITLE_REQUEST, description=opasConfig.DESCRIPTION_REQUEST),
                              #qtermlist only works with Post
                              qtermlist: models.SolrQueryTermList=Body(None, embed=True, title=opasConfig.TITLE_QTERMLIST, decription=opasConfig.DESCRIPTION_QTERMLIST), # allows full specification
                              fulltext1: str=Query(None, title=opasConfig.TITLE_FULLTEXT1, description=opasConfig.DESCRIPTION_FULLTEXT1),
                              smarttext: str=Query(None, title=opasConfig.TITLE_SMARTSEARCH, description=opasConfig.DESCRIPTION_SMARTSEARCH),
                              paratext: str=Query(None, title=opasConfig.TITLE_PARATEXT, description=opasConfig.DESCRIPTION_PARATEXT),
                              parascope: str=Query(None, title=opasConfig.TITLE_PARASCOPE, description=opasConfig.DESCRIPTION_PARASCOPE),
                              synonyms: bool=Query(False, title=opasConfig.TITLE_SYNONYMS_BOOLEAN, description=opasConfig.DESCRIPTION_SYNONYMS_BOOLEAN),
                              facetquery: str=Query(None, title=opasConfig.TITLE_FACETQUERY, description=opasConfig.DESCRIPTION_FACETQUERY),
                              # filters (Solr query filter)
                              sourcename: str=Query(None, title=opasConfig.TITLE_SOURCENAME, description=opasConfig.DESCRIPTION_SOURCENAME, min_length=2),  
                              sourcecode: str=Query(None, title=opasConfig.TITLE_SOURCECODE, description=opasConfig.DESCRIPTION_SOURCECODE, min_length=2), 
                              sourcetype: str=Query(None, title=opasConfig.TITLE_SOURCETYPE, description=opasConfig.DESCRIPTION_PARAM_SOURCETYPE), 
                              sourcelangcode: str=Query(None, min_length=2, title=opasConfig.TITLE_SOURCELANGCODE, description=opasConfig.DESCRIPTION_SOURCELANGCODE), 
                              volume: str=Query(None, title=opasConfig.TITLE_VOLUMENUMBER, description=opasConfig.DESCRIPTION_VOLUMENUMBER), 
                              issue: str=Query(None, title=opasConfig.TITLE_ISSUE, description=opasConfig.DESCRIPTION_ISSUE),
                              author: str=Query(None, title=opasConfig.TITLE_AUTHOR, description=opasConfig.DESCRIPTION_AUTHOR), 
                              title: str=Query(None, title=opasConfig.TITLE_TITLE, description=opasConfig.DESCRIPTION_TITLE),
                              articletype: str=Query(None, title=opasConfig.TITLE_ARTICLETYPE, description=opasConfig.DESCRIPTION_ARTICLETYPE),
                              startyear: str=Query(None, title=opasConfig.TITLE_STARTYEAR, description=opasConfig.DESCRIPTION_STARTYEAR), 
                              endyear: str=Query(None, title=opasConfig.TITLE_ENDYEAR, description=opasConfig.DESCRIPTION_ENDYEAR), 
                              citecount: str=Query(None, title=opasConfig.TITLE_CITECOUNT, description=opasConfig.DESCRIPTION_CITECOUNT),   
                              viewcount: str=Query(None, title=opasConfig.TITLE_VIEWCOUNT, description=opasConfig.DESCRIPTION_VIEWCOUNT),    
                              viewperiod: int=Query(4, title=opasConfig.TITLE_VIEWPERIOD, description=opasConfig.DESCRIPTION_VIEWPERIOD),     
                              # return set control (removed returnFields 2020-09-10)
                              #returnfields: str=Query(None, title="Fields to return (see limitations)", description="Comma separated list of field names"),
                              abstract:bool=Query(False, title="Return an abstract with each match", description="True to return an abstract"),
                              formatrequested: str=Query("HTML", title=opasConfig.TITLE_RETURNFORMATS, description=opasConfig.DESCRIPTION_RETURNFORMATS),
                              similarcount: int=Query(0, title=opasConfig.TITLE_SIMILARCOUNT, description=opasConfig.DESCRIPTION_SIMILARCOUNT),
                              highlightlimit: int=Query(opasConfig.DEFAULT_MAX_KWIC_RETURNS, title=opasConfig.TITLE_MAX_KWIC_COUNT, description=opasConfig.DESCRIPTION_MAX_KWIC_COUNT),
                              facetfields: str=Query(None, title=opasConfig.TITLE_FACETFIELDS, description=opasConfig.DESCRIPTION_FACETFIELDS), 
                              facetmincount: int=Query(1, description=opasConfig.DESCRIPTION_FACETMINCOUNT),
                              facetlimit: int=Query(15, description=opasConfig.DESCRIPTION_FACETLIMIT),
                              facetoffset: int=Query(0, description=opasConfig.DESCRIPTION_FACETOFFSET),
                              sort: str=Query("score desc", title=opasConfig.TITLE_SORT, description=opasConfig.DESCRIPTION_SORT),
                              limit: int=Query(opasConfig.DEFAULT_LIMIT_FOR_SOLR_RETURNS, title=opasConfig.TITLE_LIMIT, description=opasConfig.DESCRIPTION_LIMIT),
                              offset: int=Query(0, title=opasConfig.TITLE_OFFSET, description=opasConfig.DESCRIPTION_OFFSET), 
                              client_id:int=Depends(get_client_id), 
                              client_session:str= Depends(get_client_session),
                              override_endpoint_id=opasCentralDBLib.API_DATABASE_SEARCH
                             ):
```

**Comment by nrshapiro** [comment]
@bakerac4 

Also, for reference, I should have added these online pages which may help you:

http://support.pep-web.org/help-topics-and-video-tutorials/pep-web-2021-help-topics/advanced-search/
http://support.pep-web.org/help-topics-and-video-tutorials/pep-web-2021-help-topics/pep-web-2021-fielded-search/

**Comment by bakerac4** [comment]
@nrshapiro In going through and writing tests I noticed that `stitle` isn't actually implemented yet. Can you provide what I should use for `stitle`?

**Comment by nrshapiro** [comment]
@bakerac4 

Search endpoint parameter sourcename

**Comment by nrshapiro** [comment]
@bakerac4 

Is this available for testing on stage, and if so, what is the URL to test?

**Comment by bakerac4** [comment]
@nrshapiro @bakerac4 it has been tested on stage - there isn't really a specific url though as this is all about taking in URL params?

https://stage.pep-web.org/search?sid=PEP:PEPWeb&atitle=war&date=1997

**Comment by nrshapiro** [comment]
@bakerac4 

Problems with the OpenURL interface:

1) The artnum parameter does not work:

https://stage.pep-web.org/search?sid=PEP:PEPWeb&artnum=PI.014.0201A

It doesn't seem to pass anything to the forms.

Note to implement, you can pass this to smartsearch: 

art_id:PI.014.0201A

You could also just pass the ID, but it seems "safer" to make it specify the field "art_id".  If you want to use adv:: like for the other fields, that works too: 

adv::art_id:IJP.100.*

https://stage.pep-web.org/search?q=art_id%3API.014.0201A

Also, while a wildcard works with the regular PEP-Web URLs:

https://stage.pep-web.org/search?q=PI.014.*

It doesn't work for the openURL version:

https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child*

unless you url encode it:

https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child%2A

I don't think that should be necessary...especially if it's not necessary in the regular PEP-Web syntax.

**Comment by bakerac4** [comment]
@nrshapiro I fixed the art_Id issue. Also I might be losing it here, but 

`https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child*`

and 

`https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child%2A`

return the same two results?

**Comment by nrshapiro** [comment]
@bakerac4 

It's been a few weeks but when I tried it just now, I agree it works.

I also note that at least in my presentation, when I linked the URL's above, for some reason, the * is in the marked link area.

[link](https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child*)

But it appears to work so that is fine.  Sorry for the confusion.

Regards--Neil



> @nrshapiro I fixed the art_Id issue. Also I might be losing it here, but
> 
> `https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child*`
> 
> and
> 
> `https://stage.pep-web.org/search?sid=PEP:PEPWeb&aulast=Gilkey&atitle=child%2A`
> 
> return the same two results?

**Comment by SophieMBennett** [comment]
@bakerac4 @nrshapiro Please could you confirm what the artnum parameter has been replaced with? We need a working URL example for users.

**Comment by nrshapiro** [comment]
@bakerac4  @SophieMBennett @adistasio 

Last night I did more complete testing of the OpenURL interface based on queries I have in my test suite for the server's OpenURL function.  And I found a few issues

1) eissn is not supported.  You get a 500 error.  Per discussion above, eissn was to return the same as issn

https://pep-web.org/search?sid=PEP:PEPWeb&eissn=1018-2756 - This one doesn't work (generates a 500 error)

2) while the format of the pages parameter in openURL 0.1 says  "Pages covered by an individual item in a bundle. The format of this field is ' spage-epage'"

I would expect to be robust enough to accept variations of this, especially a single page number.  But when you use a single page number it shows, in the interface, that it maps to advanced query  _adv::art_pgrg:217-undefined_

Besides not working, it looks bad.  I would like to see that fixed (as well as the 500 error above.)

Test Query:
     https://pep-web.org/search?sid=PEP:PEPWeb&pages=217


**This is the full set of queries I tried.  All worked except as noted (and that's repetitive from above)**
https://pep-web.org/search?sid=PEP:PEPWeb&issn=1018-2756
https://pep-web.org/search?sid=PEP:PEPWeb&eissn=1018-2756 - This one doesn't work (generates a 500 error)
https://pep-web.org/search?sid=PEP:PEPWeb&isbn=0422725501
https://pep-web.org/search?sid=PEP:PEPWeb&title=*ego*
[https://pep-web.org/search?sid=PEP:PEPWeb&stitle="International*"](https://pep-web.org/search?sid=PEP:PEPWeb&stitle=%22International*%22)
https://pep-web.org/search?sid=PEP:PEPWeb&aufirst=David
https://pep-web.org/search?sid=PEP:PEPWeb&aulast=Tuckett
https://pep-web.org/search?sid=PEP:PEPWeb&volume=101
https://pep-web.org/search?sid=PEP:PEPWeb&issue=4
https://pep-web.org/search?sid=PEP:PEPWeb&spage=5
https://pep-web.org/search?sid=PEP:PEPWeb&epage=49
https://pep-web.org/search?sid=PEP:PEPWeb&pages=31-*
https://pep-web.org/search?sid=PEP:PEPWeb&pages=22-49
https://pep-web.org/search?sid=PEP:PEPWeb&pages=79-*
https://pep-web.org/search?sid=PEP:PEPWeb&pages=*-49
https://pep-web.org/search?sid=PEP:PEPWeb&date=2021
https://pep-web.org/search?sid=PEP:PEPWeb&artnum=IJP.100.*
https://pep-web.org/search?sid=PEP:PEPWeb&artnum=PB.010.*&sort=author
https://pep-web.org/search?sid=PEP:PEPWeb&date=1999&sort=author
https://pep-web.org/search?sid=PEP:PEPWeb&pages=217 - doesn't work, maps to adv::art_pgrg:217-undefined

**Comment by bakerac4** [comment]
@nrshapiro you probably want to fix the 500 error either way(I assume ideally you never should be sending me a 500 error). 

This is what Im sending `adv::art_eissn:NUMBER_HERE`. Is this incorrect?

**Comment by nrshapiro** [comment]
https://pep-web.org/search?sid=PEP:PEPWeb&eissn=1018-2756
https://pep-web.org/search?sid=PEP:PEPWeb&pages=217

Now work on production.
