### ISSUE TITLE
Author Index listed in Report a Data Error doesn't exist any more

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#534]
There's no longer an author index on PEP-Web, so the link to help that says "Author Index Correction" in the in Report a Data Error form is not applicable.  It should be removed.

![image](https://user-images.githubusercontent.com/4837554/122054317-8fc8ac80-cdb5-11eb-9283-6112c7933fb8.png)

**Comment by nrshapiro** [comment]
@SophieMBennett Note that the author index correction on this box goes to the support site where there is a form.

Since we have no author index, once we remove this from the popup form, the wordpress topic can be removed.

Meanwhile, you may just want to edit it to say that there isn't an author index anymore so corrections are not needed.

**Comment by SophieMBennett** [comment]
@nrshapiro I've updated the linked support page.
