### ISSUE TITLE
"Search Help Video" takes you to the Facebook page placeholder not the PEP Support video help

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#538]
The Help option "Search Help Video" takes you to the Facebook page you had them link as a placeholder before, and was not updated to point to the new search help video.   That video isn't relevant.    

For the record, it would be better to change the menu option to two options:
 - Help Topics
 - Help Tutorials (Videos)

(I don't even think "Search Help Video" has a clear meaning since Search is also a verb--are we searching the help video).

But that would also require changes to the various language files etc.  

In any case, to keep it simple for now, since this is authorized, I want to just change the link behind it to:

http://support.pep-web.org/the-new-pep-web/pep-web-2021-video-tutorials/pep-web-2021-video-tutorial-search/

**Comment by bakerac4** [comment]
@nrshapiro You should be able to edit that url in the Admin -> General section unless Im missing something?

**Comment by nrshapiro** [comment]
Wow--I didn't know that was there!  I wasn't expect that, since it's the only menu action I can change, but I guess we must have asked for it?  In any case, great.
