### ISSUE TITLE
Glossary Popup Resets the article position to the top

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#539]
As reported by a user, when you click on a glossary entry for the definition, the article position is reset to the top of the article.  

I've replicated it below, as can be seen in a short video.

https://user-images.githubusercontent.com/4837554/125096591-4b25ed80-e0a3-11eb-8aa3-3f886fc58b7d.mp4

Thus the user loses their place in the article.  In a multipage article this is a fairly big issue.

**Comment by bakerac4** [comment]
Fixed by #545
