### ISSUE TITLE
Periodic Internal Server Error

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#54]
I know you know about this error, but I've just hit it again, and I thought it would be good to register it here, so we can track it.

Is it a general Ember issue?  

As you also know, clearing cookies fixes it.  For me, I can just do that in the inspect panel, but when we give it to the board, I think that means clearing cookies from all their sites at once, which is going to be somewhat inconvenient for them.  (Actually, some browsers like Chrome seem to support site-by-site cookie clearing, but Opera does not, I can't speak for Safari and others.)

**Comment by nrshapiro** [comment]
Just for your information--I don't know if anything needs to be done about this because it could just be a development transition issue-- Last night I ran into this again and several "scary" variants, which perhaps have to do with updating and caching.  For one thing, while I could see the new client when I first started looking at it, it would not let me log in.  It kept telling me the test1 and test4 account with password were no good.  Nothing I could do would let me log in.  I eventually cleared this up by clearing all the cookies it had saved.  It was also showing me a number of errors relating to session ids on screen.  Perhaps just a transitional issue for now.  I wish I had done some screen captures, but alas not.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio @bakerac4 

I assume this is part of the same problem, which happens to me sometimes when logging in/out of client 4208, but I don't know yet how to predict when it will happen so I can't give you a way to reproduce.  But it's happened to me at least a half a dozen times.

The interesting thing, given the message, is that it happens when logging out (perhaps more than logging in).  I can't upload the video, but it keeps adding more of the messages and eventually ends in a 500 Error being displayed.

![2020-10-12_14h43_19](https://user-images.githubusercontent.com/4837554/95882249-76afbd80-0d47-11eb-9130-9bf33518b9ce.png)

**Comment by nrshapiro** [comment]
@billdami @bakerac4 @adistasio 

This has been happening to me with great consistency this afternoon and so far this evening in client ver. Client: 4584

**Comment by bakerac4** [comment]
@nrshapiro have you seen this lately? If not, can we close this issue?
