### ISSUE TITLE
GW/SE Concordance popup does not work on Production or Stage

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#541]
The hover based popup feature, which works when I run locally with the client with SSL off, is not working online for Stage or Production.  When you hover, it says loading, but never loads.

It appears to be a CORS issue, debug shows blocked for mixed content?  This is on production:

![image](https://user-images.githubusercontent.com/4837554/125380494-4346a180-e360-11eb-87ae-37776c76d264.png)

Here it is running in non-SSL mode on my PC:

<img width="1678" alt="2021-07-12_22h22_31" src="https://user-images.githubusercontent.com/4837554/125380678-96205900-e360-11eb-9940-a5645b4ba1e4.png">

**Comment by bakerac4** [comment]
Fixed by #542
