### ISSUE TITLE
👋 Hi there! Setting up locally? (Font awesome issue)

### ISSUE THREAD

**Issue by tony** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#551]
Hi!

I'm studying psychology and I run into PEPWeb links all the time. I am super impressed by this interface for pep-web.rocks. This looks like the ultimate psychoanalytic search engine.

Is the idea of the project to be open to contributors from the public?  Is this the place an outsider could get started if they wanted to contribute?

I am trying to get a minimal example of the pep-web stack setup on my local computer. I bumped into an issue:

```
PEP-Web-User-Interface on  master ❯ cd pep
PEP-Web-User-Interface/pep on  master ❯ yarn
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-light-svg-icons/-/5.13.0/pro-light-svg-icons-5.13.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/x/work/pepweb/PEP-Web-User-Interface/pep/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PEP-Web-User-Interface/pep on  master ❯
```

(I anticipate this is simply the frontend and a backend repo, [OpenPubArchive-Content-Server](https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server), would also need to be working)

Is it the long term plan to require contributors have a FontAwesome Pro license?  Is that something set in stone?

P.S. I also don't want to intrude as its easy to see a very talented team has things handled! I'm happy enough just to watch pep-web.rocks grow.

**Comment by nrshapiro** [comment]
@tony - thanks for your comment.  It is still early in the project and we have many things on the horizon--the source is open but not all source licenses are required to be free (the PEP Board can certainly discuss that though). We welcome comments, issue reports, and ideas and will at some later point welcome independent contributors.  

FWIW, there are three separate parts here...this front end, the back-end database server as you noted, and the permission server (PaDS).  It's not a small project!

**Comment by tony** [comment]
@nrshapiro Thank you for your response. I will take another peek during this weekend!

**Comment by tony** [comment]
This does seem like a complex project indeed!

Is it realistic at this point and time to get bootstrapped w/ the project locally (e.g. without needing AWS)?  Is [PaDS](https://github.com/Psychoanalytic-Electronic-Publishing/PaDS) required to be running to make changes to the frontend project?

# re: Commercial dependences

## Impact?

On paper:
I think that _if_ building / changing a project _requires someone to purchase a commercial license_, it sends a mixed signal. But there's many ways around it, e.g. making commercial dependencies optional, filling in commercial alternative libraries that are readily available, etc.

In practice:
I don't see a negative impact to volunteer contributions.  It won't necessarily hinder contributions, nor will the effort involved ensure a proportional reciprocation of commitment from outside volunteers.

As an example, a very crucial and popular developer website: [python's package index](https://pypi.org/) (gh:  [pypa/warehouse](https://github.com/pypa/warehouse), [contributor list](https://github.com/pypa/warehouse/graphs/contributors)).

That said, any effort to simplify bootstrapping makes things more sustainable, having dependencies ready to grab at the outset helps.

## Licenses to build project?

A stab at listing dependencies that an outside contributor would need a commercial license to build

### [OpenPubArchive-Content-Server](https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server)
- No commercial dependencies?

### [PEP-Web-User-Interface](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface)
- FontAwesome Pro (https://fontawesome.com/pro)

### [PaDS](https://github.com/Psychoanalytic-Electronic-Publishing/PaDS)

Side note: According to the manual, first release in July 2002! This is a gem!

 - DevExpress v19.2 ASP.NET Subscription (with DevExtreme) package. (https://www.devexpress.com/)
 - Ionic Zip v4.0.30319 a library for handling zip archives. http://www.codeplex.com/DotNetZip (Flavor=Retail)
 - Spreadsheetgear2017 a library for handling spreadsheets. https://www.spreadsheetgear.com

I'm not familiar enough with .NET ecosystem to know if high quality alternatives exist for the above. I don't know what the normal open source best practices would be for this - that said Microsoft bought out GitHub and there's more .NET projects on GH nowadays.

**Comment by tony** [comment]
Thank you for the project!

This is fine to close (to clear up any stale issues). If you find this issue applies to you find to create a new one and cite this one.

**Comment by tony** [comment]
@Psychoanalytic-Electronic-Publishing The PEP site is beautifully executed - your organization was incredibly fortunate to assemble such a talented team of engineers. It clearly required significant experience and expertise to achieve this level of quality.

The user experience, thoughtfully selected colors (both in contrast and aesthetic harmony), overall design, and sophisticated yet intuitive search functionality demonstrate remarkable balance, especially given the data-rich context. There are numerous elegant touches that strike precisely the right note; for example, I appreciate how easily the sidebars collapse and the immediate availability of the query builder right on the homepage's left panel, letting users dive directly in.

(It’s genuinely surprising how many digital libraries overlook this critical detail, burying their search functions rather than making them the focal point they deserve to be.)
