### ISSUE TITLE
Browser based search (Ctrl-F) highlights but cannot jump beyond first page

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#557]
Several bug reports from users have been submitted noting that they cannot use Ctrl-F (find) to jump to matches in an article.  I tested this and in fact, while the hits are highlighted and counted, the front end won't jump ahead beyond the first page.  Pages on other sites work normally.

I presume there is a way in Ember to implement this.  Please let us know and the approximate effort to implement.  If it helps, I see there's a way in Ember to jump to anchors per https://ember-twiddle.com/21bb3d46c665718d8b78b5c036ad6529

**Comment by bakerac4** [comment]
@nrshapiro its due to a shortcoming with a library we use for scrolling https://perfectscrollbar.com/. We have budgeted enough time where we should be able to remove it, however it might slightly change the look and feel of the scrollbars in the app. Just wanted to confirm before we move forward.

**Comment by nrshapiro** [comment]
Not sure what the changed scrollbars would be like, but there's a parallel issue on them anyway where it was pointed out they are too small to see and use in some cases.

The look isn't as important as being able to use Ctrl-F as you would in a word processor for a document to find strings.  (I note that the verbiage above seems like it's referring to search hits, but it's referring to searching in a document via simple find.)
