### ISSUE TITLE
New Download/Printing Restriction Feature

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#561]
DT wanted to completely restrict downloads or printing of books (in any format).  (Downloading/Printing go hand in hand, since you can easily print what you download in PDF and for that matter ePub, though less easily.)

To give us more selective and fine grained control of that, I've added an attribute to element _artinfo_ to give us selective control of that:
```
               download        (true | false)                              "true"
               downoverride    (true | false)                              "false"

```
1) If the "download" attribute is set to "false", the server will not provide the file to the client app.  
2) **But the client app should not even request it, nor enable the download/print features when the attribute is set so to clearly communicate to the user that the instance is not downloadable. [Action Item]**

download - this can be set to "false" to prohibit downloading of any instance.  Books will have this set by the processing software automatically.

downloadoverride is of no consequence to the client.  I've added that to allow instances to overrule the normal document processing, so you could enable downloading of a specific instance within a split book (for example the TOC).  When downloadoverride is true, the download attribute is not changed by the processing engine.

**Comment by bakerac4** [comment]
@nrshapiro can you provide an article ID that has download false to test this?

**Comment by nrshapiro** [comment]
> @nrshapiro can you provide an article ID that has download false to test this?

@bakerac4 

Here's an example: SE.001.0073A

<artinfo arttype="ART" j="SE" ISBN="0099296225" download="false" downoverride="false" embargo="false" origrx="GW.018S.0107A" id="SE.001.0073A">

All the books should already be set that way.  I checked the XML on a few:  
   All of SE seems to be set
   All of GW as well.  Example: GW.001.0252A
   All of IPL   - Example: IPL.084.0009A
   ...

**Comment by bakerac4** [comment]
@nrshapiro Ok Im seeing it. Would it be possible to provide that as an attribute to the document instead? Much like `accessLimited` is - parsing the entire document/abstract xml to try and get that one attribute out would not be great

**Comment by nrshapiro** [comment]
Sure, I can do that.  It's up on stage.

But since I was doing that, it only seemed right that I actually prevent the API from downloading such files.  So the download endpoint now throws an HTTPException if you try to download a file that's not permitted.  Which brings me to a question: since that's the kind of errors I see the client not displaying in the interface, is that a problem to trap in the client?  What the user sees then is the text of the exception:

{"detail":"[v2/Documents/Downloads]: The requested document SE.002.0000A could not be returned (in PDF). "}

Here's the document class in part:

```
class DocumentListItem(BaseModel):
    coreName: str = Field(None, title="Core", description="Core from which the item was retrieved")
    documentID: str = Field(None, title="Document ID/Locator", description="The multiple-section document ID, e.g., CPS.007B.0021A.B0012 in a biblio, or CPS.007B.0021A as a document ID.")
    docType:  str = Field(None, title="Document Type (Classification)", description="e.g., ART(article), ABS(abstract), ANN(announcement), COM(commentary), ERR(errata), PRO(profile), (REP)report, or (REV)review")
    documentRef: str = Field(None, title="Document Ref (bibliographic)", description="The bibliographic form presentation of the information about the document, as in the 'citeas' area or reference sections (text-only).")
    documentRefHTML: str = Field(None, title="Same as documentRef but in HTML.")
    documentMetaXML: str = Field(None, title="Metadata content in XML, , e.g., element meta")
    documentInfoXML: str = Field(None, title="The document meta information in XML, e.g., element artinfo")
    title: str = Field(None, title="Document Title")

    ...

    pdfOriginalAvailable: bool = Field(False, title="", description="")
    embargo: str = Field(False, title="Article Embargoed", description="Article level embargo mechanism") 
    embargotype: str = Field(None, title="Article Embargo Reason", description="Article level embargo reason")
    downloads: bool = Field(True, title="Allow print/downloadng", description="If False, downloads and printing of this document are not allowed.")
    # these are not all currently used
    accessClassification: str = Field(None, title="Document classification, e.g., Archive, Current, Free, OffSite, Special")
    accessChecked: bool = Field(False, title="Access was checked. If false, accessLimited value is just defaulted to False")
    accessLimited: bool = Field(None, title="Access is limited, preventing full-text return.  Only valid when accessChecked is True.")
    accessLimitedCode: int = Field(None, title="If an error code is returned from the server, pass it back here for ease of client processing")
    accessLimitedReason: str = Field(None, title="Explanation of user's access to this")
    accessLimitedDebugMsg: str = Field(None, title="Developer level info for tracing access issues")
    accessLimitedDescription: str = Field(None, title="Description of the access limitation applied")
    accessLimitedClassifiedAsCurrentContent: bool = Field(None, title="Access is limited by embargo to this specific content")
    accessLimitedPubLink: str = Field(None, title="Link to the document or publisher in some cases where doc's not readable on PEP")

```
![image](https://user-images.githubusercontent.com/4837554/143066926-8068999e-1d31-4171-9328-62ca77784eb7.png)

**Comment by nrshapiro** [comment]
@bakerac4 (See above...forgot to reference you in the response.)

**Comment by nrshapiro** [comment]
@bakerac4 @rickardnyman @davidtuckett 

Per a clarification about what books should be prohibited from downloads/printing, I'm in the process of  changing the instances that are marked non-download.  Now, only full books will be marked downloads=False.  Thus, of the examples above, once the database rebuilds (by tomorrow), none of those will be set.  For testing, pick a book that's full size instead.

Examples:

IPL.064.0001A
IPL.100.0001A
ZBK.020.0001A
ZBK.003.0001A

Note markup of the download attribute is done by rules during build time (instances that are books and are marked an extract) rather than manually.  This means that none of the SE/GW instances are single instance per volume, so all the instances of SE/GW will be downloadable, including volume 4, which is "mostly", but not all, in one instance.  (We could, however, adjust that by also restricting by instances with a large number of pages.)

**Comment by bakerac4** [comment]
> 

@nrshapiro that wont be an issue as the user wont ever see those errors. We completely remove the download buttons if they dont have access now, so they can't even try download it to see that

**Comment by nrshapiro** [comment]
The current message system seems to have a flaw: if I post a message, it doesn't show up on anyone's system until they do a refresh.  Selecting Search, Read, Browse, Home, or one of the menu options doesn't affect display.  

So warning users of an impending "issue", slowdown, update etc. isn't seen by users who "stay on".  A user who logs out or logs in would see it, but no one else.

**Comment by bakerac4** [comment]
Hey Neil,

1. I think you have the wrong issue - this is for new download/printing restrictions.
2. We have confirmed it's working on stage. The way it works is by polling every 5 minutes for a message. So as long as you add the message, then wait 5 minutes before you do any maintenance work  the user should see the message. We did it that way so that multiple calls were not being made each time the user pressed a button. 

Let me know if this is sufficient,
Adam

**Comment by nrshapiro** [comment]
@bakerac4 

Yes, you are correct 1) I reopened the wrong issue and 2) I tested a message, waited about 5 minutes, and there it popped up on my "idle" screen.  That's fine.  I didn't know it was timed.  I posted a note in the correct thread.

**Comment by nrshapiro** [comment]
Reopening.  DT was not happy with the way this works.  He feels it leaves the user wondering where the print icon/download menus have gone--they will seem to be missing without explanation.  

The alternative is to leave the icons in place, but to disable them, but support a hover message on them which provides a message explaining that printing/download is not available for the current document due to copyright security (configurable with the other hover messages).

**Comment by nrshapiro** [comment]
Carried forward as #591
