### ISSUE TITLE
Authentication Changes--Problem with Related Documents

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#563]
As noted in https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server/issues/134, the client has a problem with the new protocol when there are related documents.

As part of this change, the server doesn't return access data except for a single abstract request or document request.  So what's happening here:

1. The client asks for the document selected:
http://development.org:9100/v2/Documents/Document/IJP.083.1133A/?return_format=XML&search=%27%3Ffacetlimit%3D15%26facetmincount%3D1%26smarttext%3Dsuicidal%2Bthoughts%26highlightlimit%3D6%26synonyms%3Dfalse%27

The server responds, and provides correct accessLimited: false information. So the document or abstract can be displayed.

2.  The then client asks for the related document information. The server returns a documentList with three records, WITHOUT checking for access. There's a new flag for that: accessChecked is returned with False in that case.

So the client should now look for accessChecked before using the accessLimited value. However, I set the accessLimited value to None, now by default. It shouldn't be showing up as long as it's never set, just default...though I still see it in the debugger. But now, despite that, the client appears to be working!

**Comment by bakerac4** [comment]
@nrshapiro in the case that access is undetermined, what should happen in all the places we were using `accessLimited`?

**Comment by nrshapiro** [comment]
@bakerac4

This demonstrates the problem caused in the client by the server accessLimited change. Regular documents work. Documents with RelatedDocuments (see the icon) cause the problem:

https://user-images.githubusercontent.com/4837554/137528184-0eb192df-4872-4357-b47c-71d818444e9a.mp4

It looks like it should be a simple fix.

**Comment by nrshapiro** [comment]
@bakerac4 @rickardnyman @adistasio 

I went ahead and implemented #4, it was easier and a lot quicker than #3 figuring out why the NOT query wasn't working...will have to do that when I get back.

It's tested here, and I'm in the process of loading a new version to Stage.  The new endpoint is 

![2021-10-20_19h54_32](https://user-images.githubusercontent.com/4837554/138188102-c3f42a9c-67da-488b-948b-b851662c4aee.jpg)

Note that you just need to supply the MAIN ARTICLE ID (the one being viewed).  It looks up the data in the relatedrx field (for us art_qual, but that's configurable) that holds related IDs.

The other benefit of this approach is it's another case where you won't be calling the search endpoint, for what is a standard infocard everytime (or most of the time) when you look at an article.  That skews the user search data statistics.  This search isn't recorded there.
   https://stage-api.pep-web.org/docs#/Database/database_related_to_this_v2_Database_RelatedToThis__get

Data Example (results not formatted here though):
   https://stage-api.pep-web.org/v2/Database/RelatedToThis/?relatedToThis=IJP.078.0335A

This is up on stage.  Please go ahead and modify the client to fix it THIS WEEK and push it to stage so that when I return I can run all necessary testing and push to production within a day.  If I get a chance, I'll do some user testing while away if it's all on Stage.

**Comment by nrshapiro** [comment]
Latest client uses the new endpoint.  Closing.

**Comment by nrshapiro** [comment]
@adistasio @bakerac4 @bdami-gavant 

We have a problem here.  The "new" endpoint I added in November was designed to return a list of the related papers, but not the paper that the user is viewing (users complained about that before).

As you can see in the description above, 

relatedToThis - Enter a document ID to find all related documents per a common schema value

You **should** send it the document that the user is viewing in the relatedToThis field.  Not the art_qual value in the document.  The API considers that you are asking for documents related to the one the user is viewing.

So it works like this:

1) The server searches for the Solr document record that matches the ID.  The one the user is looking at.
2) The server then gets the art_qual id from that record.  
3) Then the server does a second search, for all documents that have a matching art_qual.  As part of this search, the server filters out the original art_id (the relatedToThis parameter), so the document the user is viewing is not in the list.

This works as I would expect if the user were calling the API directly.  The user would not know the art_qual value...they would only know the ID of the document they were interested in finding related documents.

Since the client does know what documents have an art_qual, though, you should continue to be "smart" and only call the API if you know the document has related documents via art_qual.  But you should send the viewed article id, not the value from art_qual.  Clear?

Can we please fix this for this release?  It shouldn't be much to do.  I'm going to mark it as such in the issues.
