### ISSUE TITLE
User Disruption Warning

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#564]
We need a way to warn users 10 minutes or so before we do something that may disrupt the server that we are loading or working on the site and there may be a disruption.  

A message area in the header that we can post to and tell it wen to remove it (noting we may post an update rather than removing it)

Examples: 
   - We will be working on the system in 10 minutes...expect some disruptions.
   - The system will still be maintenance for another 10 minutes
   - (remove message)

**Comment by rickardnyman** [comment]
We would like similar warning messages to appear when the system is unresponsive, for whatever reason.

**Comment by Mavann1988** [comment]
@rickardnyman In the admin section we can put the message either in the global area or the language specific one. The pros of global is that is makes it easier to do since you enter it once but the con is that it's only in English. If we put it in the language specific area then you have to add it multiple places but it's in the correct language for the user. Thoughts?

cc @bakerac4

**Comment by rickardnyman** [comment]
Is there any chance we can use a global variable by default (in the global area), but if a language specific message is specified it will display this instead? That way we may start with a simple English message but if users find it confusing can add language specific ones

**Comment by rickardnyman** [comment]
@bakerac4  @Mavann1988

**Comment by nrshapiro** [comment]
I tried the new client on Stage, which was moved to master.  Whatever I do, it looks like this.

Perhaps this is the default message that's in the admin mode, but I can't get to the admin menu, because there's no way to dismiss it and the menubar is not available.

![image](https://user-images.githubusercontent.com/4837554/144438428-d8012a4f-3bbb-4c2a-912c-d7abd93ac60c.png)

**Comment by nrshapiro** [comment]
@rickardnyman @bakerac4 -- it just changed, so perhaps someone is working on it.  Please be careful if that long message is the default upon loading though since it covers up everything!

![image](https://user-images.githubusercontent.com/4837554/144441479-5eb90236-83e3-460f-aac6-734602e54a23.png)

**Comment by nrshapiro** [comment]
@rickardnyman @bakerac4 
Also, we are warning the user about disruptions, not forcing the user off the system.  The message bar covers the menu bar. 
 Even while the cover on a one liner is not full, it makes it more difficult to continue using the system.  It's not a bad idea to leave the message up, but it should not get in the way of the system.  There's a ton of real-estate on that top menu bar in the center, or you could push everything down to accommodate the message.

**Comment by nrshapiro** [comment]
Note the message does not appear for 5 minutes on an already logged on screen.  This is fine.  (I posted a question about this in the wrong issue and Adam answered there...for reference: 

From @bakerac4 
```We have confirmed it's working on stage. The way it works is by polling every 5 minutes for a message. So as long as you add the message, then wait 5 minutes before you do any maintenance work the user should see the message. We did it that way so that multiple calls were not being made each time the user pressed a button.```

I've confirmed that as well.  All is good.
