### ISSUE TITLE
Concordance Links not Working

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#566]
I am currently testing the new version and while the use of the new Related Documents endpoint looks good, doing a full-feature test I've seen an new unrelated error in this version.  

![image](https://user-images.githubusercontent.com/4837554/139862230-2093ba5b-4f1d-4334-8e90-f092aa96e1dd.png)

The concordance links are not working.  When you click on one, you get an error from the client.

https://stage.pep-web.org/browse/document/SE.006.R0007A?page=P0138

![image](https://user-images.githubusercontent.com/4837554/139859916-e7e66ba6-4f11-4b4a-9ac4-56ba5eb938ef.png)

I ran this version locally against the same server, and traced the call to the concordance endpoint, which is returning data as before.  (There are no changes to that endpoint in this version.)

![image](https://user-images.githubusercontent.com/4837554/139861527-89d62e20-c184-4fe1-a4a3-763f7cc8f35b.png)

I can't push the new server and client until this is fixed, so it's also ultra-high-priority.

**Comment by bakerac4** [comment]
@nrshapiro I reverted my changes to see what is going on and Im still seeing this error. 

Looking into more, here is the line thats failing

```https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/blob/764e70ca51a245b81d292fbaa215cf3d998f4d3c/pep/app/pods/components/document/text/component.ts#L724```

which hasn't been modified in 10 months. Are you sure nothing changed with the data/server?

**Comment by bakerac4** [comment]
Looking into this a bit more, it seems like there used to be a property called `document` in a document.
<img width="1027" alt="Screen Shot 2021-11-02 at 10 45 38 AM" src="https://user-images.githubusercontent.com/9952936/139870255-c6948de2-33c5-40be-8b9d-b6716a3480ed.png">

Did that get taken out?
