### ISSUE TITLE
Mixed Content EZProxy setup            

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#568]
@adistasio @nrshapiro 
The University of Vienna were having a problem with EXProxy, Firefox wasn't working as it was complaining about "mixed content" which appears to mean http & https calls, Chrome was working but not showing some images:
<img width="1091" alt="Screenshot 2021-11-19 at 16 01 00" src="https://user-images.githubusercontent.com/70103034/142653424-53890b09-6382-46e0-8374-9a6cb66c21ab.png">

I suggested removing the following line from the stanza:
<img width="411" alt="Screenshot 2021-11-19 at 15 58 10" src="https://user-images.githubusercontent.com/70103034/142653705-ebbec978-df62-4f13-b69a-e5cfc9fe082d.png">

This appears to have worked although they are going to do more testing.

My question is why is the client doing HTTP calls and does it need to?
@AthenaPEP

**Comment by jwoosnam** [comment]
Since Vienna changed their stanza, this issue is no longer an issue for them, but  my question "Why is the client doing HTTP calls and does it need to?" still remains as it appears that this might be giving rise to the "mixed content" error in some browsers.

**Comment by nrshapiro** [comment]
closed via 592.
