### ISSUE TITLE
Where is the DataSource version from?

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#585]
I did a full-rebuild of stage last night.  I was thinking/wondering if the data update showed to the client/user.

Here's what stage shows:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/4837554/146379423-4eb039ae-52f1-4829-993f-fdb46b954c8d.png">

This date shows the 14th, not the 15th when I updated it.  

Here's production:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/4837554/146379197-e5f8f95c-3020-467f-9302-f851511e1aeb.png">

Why is production today's date?  It hasn't had data updated in quite a while.  

Can you explain where that comes from (and why these show as seen above)?

**Comment by lhorne-gavant** [comment]
Hi @nrshapiro, I took a look and it looks like that value is defined in your localsecrets as `OPAS.AWSProd.{SERVER_START_DATE}`. Production machines have been respinning weekly due to running out of space. This request was served by a machine that had restarted this morning.

**Comment by nrshapiro** [comment]
@lhorne-gavant 

This would be more useful if it contained the actual data update date which is what the label suggests.  Is there a way to carry that over instead?  (Server start date doesn't matter to users).  And it's likely something we can find on AWS directly, right?)

**Comment by nrshapiro** [comment]
@lhorne-gavant - Ah, when you said Localsecrets I assumed you meant something in your copy of localsecrets...not something I actually entered.  But I just noted it was something I supplied...so I should be able to fix that!  But since we have different localsecrets, I likely will move mine to opasConfig.   Let me have a look, if I need something changed in your localsecrets, I'll let you know.  :)

**Comment by nrshapiro** [comment]
this has been resolved via a change in the server.
