### ISSUE TITLE
HTTP Calls for Image loads?

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#592]
Per some user diagnostics, it seems the client may be calling the server image load API call using HTTP instead of HTTPS.

If that's true (confirm), why?  Can it be changed to HTTPS?

For more details see: #568 (which we are closing for now) in lieu of this more simple query.  

Also, see https://github.com/Psychoanalytic-Electronic-Publishing/Support/issues/190

**Comment by bakerac4** [comment]
![Screen Shot 2022-01-07 at 8 47 29 AM](https://user-images.githubusercontent.com/9952936/148552995-40563e13-c3cb-4ab0-881d-7679b02e193b.png)

@nrshapiro from what it looks like Im request HTTPS but getting redirected to HTTP?

**Comment by nrshapiro** [comment]
@bakerac4 

My code is not setting this...this looks like it's in the ASGI or Starlette response to the request.  Before I try to delve too deep into that and protocols, try this simple fix I found on [someone's related FastAPI question](https://coderedirect.com/questions/429035/fastapi-redirection-for-trailing-slash-returns-non-ssl-link): add a / after the image ID in the URL.  Otherwise, we're going to have @lhorne-gavant  mess with headers and options for gunicorn-uvicorn etc.
