### ISSUE TITLE
Results Description Field

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#60]
Missing from section 2.3.2 of the requirements, but shown in all the examples, is the description of the search results at the top of the Results pane.  For example, it says "Results 1-30 of 204 for your search on Tuckett and Fonagy".  My mistake in not listing it explicitly.

However, there's an even more important aspect of this descriptive line for the new PEP-Web.  That is, when a user enters a smartsearch, it's not always clear what it's doing.  This descriptive line is where we can explain.

I have taken steps to provide this information to the client in the next server update.  There's a new field in ResponseInfo called "description", where, currently, the server will provide information about the search.  I have added messages for smartsearch, but I have not added any for other searches.  I am still thinking about how to improve the informational value of that text, but I want to get the smartsearch part in as soon as possible, because it also helps as I test Smartsearch to see what the query interpretation actually was.  (Also, making this important, was the initial feedback from the board, that came up: the search is really "blind" without some interpretational feedback.)

Can you please provide a field like the one you see in the two figures in Section 2.3.2 and put whatever is in ResponseInfo["description"] there?  (If that field is missing or None, then just leave blank in those specific cases--the next push will only have them for smartsearches).  I will use the client to help develop these messages and make them consistent.)  

I would appreciate it if we could get this in before the pending client preview release (I will hold it till we can, or I will hold off any preview release until 10/19 when Preview Release 4 is ready).  I want to get search working "fully as expected" and producing similar results to the current PEP-Web) before we preview release to the board.

(@adistasio - Note I prefixed your Releases in the project plan with the word Preview so as not to overload the Release word which we use for product release requirements in the spec.)

Thanks.

**Comment by nrshapiro** [comment]
Smartsearch is done (but could be refined); I still need to add the message for other searches as of 11/11

**Comment by bakerac4** [comment]
@nrshapiro can this be closed?

**Comment by nrshapiro** [comment]
yes.
