### ISSUE TITLE
Citation Count facet intervals too broad

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#618]
As noted by @davidtuckett the intervals for the citation count facet is too broad, leading to most results falling in one interval.

For example, I've search for:

depression AND anxiety

<img width="187" alt="image" src="https://user-images.githubusercontent.com/4837554/151030019-148f6acb-f31e-4ff6-ba43-8bdf6d9a3af4.png">

==================
Original request with suggested intervals (Note: I am not sure if irregular intervals are possible in Solr, are currently supported in the server API, will look later)

From D. Tuckett:

I am not sure which number it is but I notice today we have done nothing about the citation count selector – see screen-print left. In psychoanalysis distributions are very skewed. **So we need something like (to discuss):

0
1-2
3-5
6-9
10-15
16-20
21-50
51 +**

**Comment by davidtuckett** [comment]
Thanks @nrshapiro Let me know before making a final decision on the intervals. Searches on <transference interpretation> <working through and interpretation> <Construct*and interpret*> <countertransference and interpretation> would be ones I might try.

**Comment by nrshapiro** [comment]
@davidtuckett 

If you want a more even distribution, your only choice may be a range of 1 or 2.  If you want to go as far as changes to both server and client you could potentially do uneven intervals (solr supports it).

e.g., 

1
2
3
4-5
6-10
10-15
15-20
20-30
30-50
50-100
100-*


Example:
http://development.org:8983/solr/pepwebdocs/select?fl=art_cited_5,art_cited_10,art_cited_20,art_cited_all&facet.field=art_cited_5&facet=on&q=text:countertransference%20AND%20mistake&rows=3&facet.range.gap=2&facet.range=art_cited_5&facet.range.start=1&facet.range.end=150&facet.mincount=1
{
  "responseHeader":{
    "status":0,
    "QTime":10,
    "params":{
      "facet.range":"art_cited_5",
      "q":"text:countertransference AND mistake",
      "facet.field":"art_cited_5",
      "facet.range.gap":"2",
      "fl":"art_cited_5,art_cited_10,art_cited_20,art_cited_all",
      "facet.mincount":"1",
      "rows":"3",
      "facet":"on",
      "facet.range.start":"1",
      "facet.range.end":"150"}},
  "response":{"numFound":2092,"start":0,"numFoundExact":true,"docs":[
      {
        "art_cited_5":3,
        "art_cited_20":12,
        "art_cited_10":7,
        "art_cited_all":27},
      {
        "art_cited_5":5,
        "art_cited_20":7,
        "art_cited_10":6,
        "art_cited_all":7},
      {
        "art_cited_5":0,
        "art_cited_20":0,
        "art_cited_10":0,
        "art_cited_all":0}]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{
      "art_cited_5":[
        "0",1323,
        "1",314,
        "2",154,
        "3",72,
        "4",51,
        "5",27,
        "6",20,
        "7",12,
        "10",12,
        "12",8,
        "8",7,
        "9",6,
        "11",6,
        "13",6,
        "18",3,
        "15",2,
        "16",2,
        "19",2,
        "23",2,
        "24",2,
        "26",2,
        "14",1,
        "17",1,
        "20",1,
        "21",1,
        "22",1,
        "25",1,
        "29",1,
        "35",1,
        "36",1,
        "38",1,
        "39",1,
        "41",1,
        "45",1,
        "50",1,
        "119",1,
        "148",1]},
    "facet_ranges":{
      "art_cited_5":{
        "counts":[
          "1",468,
          "3",123,
          "5",47,
          "7",19,
          "9",18,
          "11",14,
          "13",7,
          "15",4,
          "17",4,
          "19",3,
          "21",2,
          "23",4,
          "25",3,
          "29",1,
          "35",2,
          "37",1,
          "39",1,
          "41",1,
          "45",1,
          "49",1,
          "119",1,
          "147",1],
        "gap":2,
        "start":1,
        "end":151}},
    "facet_intervals":{},
    "facet_heatmaps":{}}}

**Comment by davidtuckett** [comment]
Neil, I dont want an uneven distribution. I want a heurisitically useful one and a distribution I can see fast and click on. Looking at above what would be useful would be 0, 1-5, 6-9, 10-25, 26+  The point is 26+ gives the ones really being cited and selects top 10 (I think). Ticking 10-25 as well gives you top 50.

**Comment by nrshapiro** [comment]
> Neil, I dont want an uneven distribution. I want a heuristically useful one and a distribution I can see fast and click on. Looking at above what would be useful would be 0, 1-5, 6-9, 10-25, 26+ The point is 26+ gives the ones really being cited and selects top 10 (I think). Ticking 10-25 as well gives you top 50.

That's fine.  By uneven I meant irregular size "buckets", and I was pointing out that if while Solr supports it, that will require more changes, since the server doesn't provide the parameter option to the client.  But it's also possible to take the distribution numbers you see in the first list and combine them into ranges--and for all I know they may be doing that in the client.  I did it that way below.

In the example above your "buckets" give:

0:1323
1-5: 464
6-9 :32
10-25: 23
26+: 18

Let me know when you make a final decision on the range intervals.  Note that I did this with art_cited_5, in other words, the last 5 years.  Without looking back at my notes, I'm not sure what they are using for the range (5, 10, 20, or all).  That's something you could decide on as well.

**Comment by davidtuckett** [comment]
@rickardnyman @ocappello for discussion with @nrshapiro in relation to how we take the client forward and which bit of the system does what.

**Comment by ocappello** [comment]
a small but important tweak to the range is to include the "0" in the first category:

0-5, 6-9, 10-25, 26+

let's go with this the above

**Comment by davidtuckett** [comment]
No, I don't agree with this please. The idea is (1) to separate out articles which have no citations (a lot), then (2) to dind a sensible way to get to the most cited. (These types of distributions are always strongly nonlinear). 
This is why above I picked 0, 1-5, 6-9, 10-25, 26+ - if it is achievable please do it. It will differ for different articles but this gives a chance to see how many have sunk more or less without trace and to find and track those which got lots of attention. Note this measure should be independent of the period over which citations counted. [When you use this you can further sub divide by year to see if articles gain or lose [popularity over time.]

**Comment by nrshapiro** [comment]
@bakerac4 - I'm not sure if you are done with the updates for r2urgent, but looking at this on stage, the interface is not showing the articles when using the 26+ category.  It looks like you may have the wrong Solr syntax for the facetquery field when the range is only restricted at the bottom:

It should be: 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/4837554/172962299-d8a8499d-0ff1-4cfd-88f4-bd780fba5e2c.png">

**Comment by nrshapiro** [comment]
Looks like this is working now..stage version 
```
Client: 2022.06.13-562714175
Server: 8.6.3/2022.0525/v2.1.158
DataSource: v2022r1a/2022-06-03T19:17:39
Session: 621760c6-6ad5-4985-8e74-3709152b6ab6
```
