### ISSUE TITLE
Refine category when there's nothing to Refine...

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#62]
When there's only 1 entry in a refine "category" (a specific refine field), it would be best to omit it.  There's no functional purpose to a single-entry refine category.  And that would let the other categories move up so they are prominent without scrolling.  It won't always be smaller, but there won't be categories which serve no purpose "in the way".  I already know that one of the key board members doesn't want refine taking up "so much space".  This will help avert that issue.  We could even use the extra space for an infocard, like the latest video infocard, which I'm sure will be on mark for him.

**Comment by bakerac4** [comment]
Fixed by #80
