### ISSUE TITLE
Word Wheel

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#63]
The word wheel works nicely if you type slowly enough.  However, when you know what you want to enter, and just type it at normal speed and press enter at the end, the wordwheel often pops up afterward and even stays up (most of the time?), so you have to go click to dismiss it.

Once the user presses Enter (or the search button if it's ever that slow), the word wheel event should be cancelled, and if already up, the word wheel itself dismissed.

**Comment by adistasio** [comment]
I believe this to be resolved.

**Comment by nrshapiro** [comment]
![2020-12-17_14h29_44](https://user-images.githubusercontent.com/4837554/102534574-fc682600-4074-11eb-8eda-b558e74f78f2.gif)

**Comment by bakerac4** [comment]
@nrshapiro I believe this is been fixed somewhere along the way. Can you confirm?

**Comment by nrshapiro** [comment]
Retested...popdown box now closes when you press enter.  That works.
