### ISSUE TITLE
Data Update Process Controller from the Client

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#637]
Buttons should be added to the Admin interface to allow an authorized admin user to control the data process.

An example of an independent program I wrote to do this, but instead I think it's better in the Admin interface.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/4837554/160469705-0946dbe3-524a-4b02-9b10-1012bf5764d4.png">

**Comment by nrshapiro** [comment]
Note: this should include revised buttons to allow even better control via the new "smartload" functionality in opasDataLoader, including the new distinction between reloading (just loading the preprocessed XML) and rebuilding (rebuilding the processed XML from the keyed/converted source XML).

The **Rebuild the Entire Data Set** button needs to be clarified and split into two separate functions which are used whenever we are in the process of new journal loading (i.e., in December and January):
- **Recompile and Load the Entire Data Set**: force rebuild of all the EXP_ARCH1 files targeted in the source folders and then load them to the databases
- **Reload the Entire Data Set**: use --smartload to build/rebuild only new/changed files, but force a reload of all files

**Comment by nrshapiro** [comment]
@jordanallen-dev - Per above, here's an example in the form of a very simple python program which basically creates the various .txt files required on Stage to start the processes.  The user must be logged in and then presses the corresponding button. that's used to start the desired process.  Of course, there are many more direct ways you can do this behind such a set of buttons either on the Admin screen or elsewhere.  

To summarize what's needed, there should be a manual way to start do each of these (along with the automatic way for the "Daily")

Daily (auto and Manual option): 
1. Update the Daily/Weekly Data Set, use --smartload

Weekly:
1. Push Stage Admin to Production if admin info updated on Stage
2. Push Stage Data to Production, assuming there was data added/updated that week

Based on Data Corrections/Updates/Other needs
1.  Do a update of the _Entire Data Set_, using --smartload
3.  Do a reload of the _Entire Data Set_:  use --smartload along with option --reload to rebuild new/changed files, and force a reload of all files
4.  Rebuild the _Entire Data Set_: use options --smartload along with option --rebuild to force rebuild the entire data set.

Where:
1. Entire Data Set - All PEP-Web-Live-Data subfolders: _PEPArchive, _PEPCurrent, _PEPFree, _PEPFuture, _PEPOffsite, _PEPSpecial
2. Daily/Weekly Data Set - _PEPCurrent, _PEPFree, _PEPFuture, _PEPOffsite, _PEPSpecial, _PEPArchive/Videostreams

**Comment by jordanallen-dev** [comment]
I see no reason a non-technical user can't upload some provided text files to S3 if given the text files, a link to the bucket, and an account with appropriate access scopes

It'll be as simple as:

1. Navigate to URL
2. Login (if not already logged in)
3. Drag and drop text file into interface
4. Press upload

The name of the text file corresponds to the job. In that way, it's not really any different than pressing a named button

I'll prepare a document with instructions and images for this and send it to @SophieMBennett and @ocappello 

No need to spend time implementing an admin dashboard now when the infrastructure around all this is set to be reworked this quarter
