### ISSUE TITLE
TOC to page links don't work -- in some cases...

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#643]
This seems to be isolated to within-document links.

I compared two documents -- Money-Kyrle (1978), which doesn't work (and there are a definitely others) and Glover (2009).  Looking at the HTML in the client, the difference appears to be that the data-page-start attribute at the beginning of pages is empty ("") in Money-Kyrle and not in Glover.  I confirmed this is their anchor point: When I edited the HTML, the link then worked (this doesn't fix it online, what I did was just temporary).  We need to have them look into why that attribute is not being populated.

**Money-Kyrle:**
![2022-04-08_09h49_37](https://user-images.githubusercontent.com/4837554/162450157-7e684a50-6a50-4f1e-bebe-8df63a13e4ad.jpg)

**Glover:**
![2022-04-08_09h50_48](https://user-images.githubusercontent.com/4837554/162450167-91629363-d669-4af5-88ab-6740bbef0a5a.jpg)

I don't know what they are using to trigger population of that attribute from the XML, but it may be "nextpgnm" which is in the page number element on the page before, just before the start of the new page.  But both Glover and Money-Kyrle have these populated correctly, so it must be a client issue.

**Money-Kyrle:**

![2022-04-08_10h00_27](https://user-images.githubusercontent.com/4837554/162452108-dd7116e4-972f-4fac-9587-998bca840f27.jpg)

**Glover:**

<img width="957" alt="image" src="https://user-images.githubusercontent.com/4837554/162452470-3aecc0d9-b789-46eb-9222-a48f2eff92f3.png">

(Related to a user report: https://github.com/Psychoanalytic-Electronic-Publishing/Support/issues/281)

**Comment by jordanallen-dev** [comment]
Fixed in #739
