### ISSUE TITLE
Volume navigation control error

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#644]
If you look at volume 101 of IJP, 

<img width="331" alt="image" src="https://user-images.githubusercontent.com/4837554/164003662-5818ee96-fbce-46b6-8767-c7dcd9fa1264.png">

and then use the left arrow to go to volume 100, there's no left arrow (carot) to go to volume 99, as if there were none (which there is)

<img width="382" alt="image" src="https://user-images.githubusercontent.com/4837554/164003766-611f3d54-014f-4035-b951-2f0d37b88d41.png">

Not sure why--and I suspect this is not isolated to IJP.

**Comment by ocappello** [comment]
we could add this to the April 2022 milestone

**Comment by ocappello** [comment]
apology--you've already added it.

**Comment by nrshapiro** [comment]
@bakerac4  

Set moreinfo to 2 to get that data.

The parameter documentation there is lacking (an understatement in that case); will update that in the next version.

**Comment by nrshapiro** [comment]
@bakerac4 

Ok, there was a problem in the server handling this particular case of Solr's return data; order of return facet data was consistent in the past, but when we hit 100, it changed and the server wasn't dealing with it properly.  I added an additional test for this volume.  Fixed in 2022.0518/v2.1.155 which will be on stage after the test suite runs successfully.
