### ISSUE TITLE
client-session in header should be in all calls

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#66]
Finally got my Internet back around 9pm tonight.  Phew.  Life is tough without internet.

I have been trying to trace why session id (client-session) is changing from the server perspective, and I believe I've found the source.  The server needs a session-id, and in case the caller doesn't supply one, it creates a new one and authenticates it with PaDS.

I put some code in to double check this on endpoints, and I identified at least one: 

2020-10-09 07:04:05 libs.opasAPISupportLib verify_header 202 - ERROR DocumentImage - No client-session (client-id) supplied in header

I suspect there may be more...can you check your endpoint calls please.  (It will ignore it if it's not needed by the call--I'm going to try and make sure they are necessary in each case.  I just put them in all calls for consistency when we added this.)

Definitely at least one other...possibly one of the Document fetches for Expert Pick

**Comment by nrshapiro** [comment]
Looks like these others for starters, probably as the app initializes--and it does it again if the user does a browser refresh.

http://stage-api.pep-web.rocks/v2/Documents/Abstracts/IJP.027.0099A/
http://stage-api.pep-web.rocks/v2/Documents/Document/IJP.027.0099A/?similarcount=5
http://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&fulltext1=art_id%3A(CJP.024A.0233A+OR+IJP.027.0099A)&synonyms=false

**Comment by billdami** [comment]
@nrshapiro did some testing of the calls for these and other endpoints from the app on both dev and stage, and it appears the `client-session` header is being sent with a value in all cases. I tested both an as unauthenticated user, and as a logged in user (via username/pw login), have not tested being on a whitelisted IP however. Also tested them when the app is already loaded, and on browser refresh too.

If you are still seeing this, can you just give some more info on your authentication state (logged in vs not, etc)? And it would also be helpful if when you load the app (for certain calls like the homepage expert pick, or Search, you'll need to navigate to the page from within the app, as on browser refresh the api call does not happen on the clientside, its cached), have the chrome dev tools Network tab open, and verify in the "Request Headers" section that the client-session header is indeed not being set.

**Comment by nrshapiro** [comment]
@billdami 

I set debug warnings on all the headers that come in without client-session, so I know they are (or were) there in stage.  The sample calls I listed were based on the logs from stage.  I can't run your app in dev...is there a url where I can run the latest dev?  The app on stage doesn't change too often.  

Anyway, I solved the problem by only looking at the header parameters for endpoints that REALLY need it.  (When we added it to the header, I decided to formally require it everywhere for completeness, but in fact, the session-id isn't needed by all the calls and when it isn't present, that was causing a new one to be generated, thus giving the client the "wrong session id".)

I've left in the debug logging code on all endpoints that need it, so I'll let you know if I see anything else.  Is there a newer client.  4208 is at least a week old.  (I still would love to see a version date added to the client release numbers or at least displayed next to them.) 

BTW - Congratulations--I heard you have a new addition to your family!

**Comment by billdami** [comment]
@nrshapiro thank you! It is definitely exciting. 🙂

By dev, I meant running the app from my local machine (which is more or less identical to whats running on stage right now). So if you were able to just test from the staging site and check the request headers in the network tab that would be enough. Also, do you know if all the requests missing the client-session header had a `client-id` header, set to `2`? Just making sure we can rule out that these requests are not coming from another source, like someone's Postman, or AWS health checks or something along those lines. Knowing how often they occur too would be helpful too, like is it constant and directly attributable to the staging site if you load the app, then look at the logs?

If you are getting the header on all the calls that need it though thats good, though still would be interested to see why this is happening, as if its coming from the web client, it would be a bug in our code. Also if you ever decided to have more fine-grained tracking on for ALL requests, would be nice to know its working as intended.

**Comment by nrshapiro** [comment]
I think this is ok now...in many endpoints, I've removed the requirement anyway.  I think the biggest offender was /Document/Image which is a graphic callout from inside the HTML and that's been addressed in the server so it doesn't require a session-id.   I have the endpoints logging this still at debug level, and I'm showing client/session id in the endpoint detail logs too, so we can always see if a new problem emerges.

**Comment by billdami** [comment]
@nrshapiro oh yeah, `/Document/Image` calls would have never had those headers, as they are requested directly by the browser via `<img src="....">` tags, which we don't have control over to add custom headers to.

In those cases having a cookie fallback _would_ make sense and be easiest to implement if they needed `client-session`/`client-id`, but i think we'd have to agree on a new cookie and value format separate from the frontend-only cookies we store now.

**Comment by nrshapiro** [comment]
@billdami 
It works without the cookies (not required), but it would be good to put them in anyway, so the endpoints can be logged and associated with the caller correctly.  Also should run a bit quicker.  The cookie names are the same as the header variable names.

**Comment by bakerac4** [comment]
We ended up adding a session ID to image calls, so I believe this should be all set to close. Please re-open if I missed something.
