### ISSUE TITLE
Video Preview in infocard does not provide a link

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#661]
There's no link or means in the video preview infocard to go to the actual article/video!

So you can watch the preview, enlarge it, but even if you are logged in, you can't go to the document with the video.

cc: @SophieMBennett

**Comment by SophieMBennett** [comment]
Update: the Info cards "Topical Video" and "Latest Video" have been removed from the Production homepage due to issues regarding AWS charges.
