### ISSUE TITLE
Add "Your Account" to User menu

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#67]
Alan/James and I had discussed whether reset your password should be from the UI/Client or whether users would know to go to PaDS.   Our subscription account manager has in fact just independently requested:

_"It would be a great feature if people could click on a button directly from www.pep-web.org and be taken to PaDS to renew their subscription, update details etc.  We get a lot of complaints from subscribers about having to remember that PaDS exists, its URL, etc"_

So instead of a link resetting their password on the user menu, we  should just add a link to "Your Account" on the user menu which opens a new tab at the appropriate place on PaDS.
 
James please chime in with the appropriate URL.

**Comment by jwoosnam** [comment]
To support the additional user details we were discussing on Tuesday, I propose adding the fields highlighted below to the user details end point.  If there are no additional comments/suggestions by close of play today Friday, I will update Swaggerhub and add the fields early next week:
<img width="666" alt="Screenshot 2020-10-16 at 11 20 53" src="https://user-images.githubusercontent.com/70103034/96248076-ec639580-0fa2-11eb-861e-d634cf33398a.png">

**Comment by jwoosnam** [comment]
The password reset URL will be available early next week and will be:
https://stage-pads.pep-web.rocks/pages/pg070Logon.aspx?Action=RequestPassword

**Comment by jwoosnam** [comment]
The fields described above have been added and implemented to stage as v06.04j.  A new test users "Test7" has been added which is within the 6 week renewal window.  See attached for all test users.
[PaDS Test Users.xlsx](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/files/5402390/PaDS.Test.Users.xlsx)
