### ISSUE TITLE
Keywords removed when converting from server returned XML to HTML

### ISSUE THREAD

**Issue by SophieMBennett** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#671]
The keywords are in the processed XML file and also in what the server returns to the client.  Inspecting the Stage presentation in a browser, the keywords seem to have been removed when converting from the server returned XML to HTML.

e.g., https://stage.pep-web.org/browse/document/PEPTOPAUTHVS.001.0045A
e.g., https://pep-web.org/browse/document/PEPTOPAUTHVS.001.0042A

This is true throughout the database, not just for videos, e.g., 
https://stage.pep-web.org/search/document/CJP.029.0073A?page=P0073&q=CJP.029.0073A

This appears to be a bug in the client.

**Comment by ocappello** [comment]
needs sorting, keywords are key to browsing and searching. @sophie can you link to neil and gavant to resolve?

**Comment by SophieMBennett** [comment]
@adistasio @bakerac4 Please could you look into this issue with the display of keywords in articles on PEP live and stage.
cc. @nrshapiro

**Comment by SophieMBennett** [comment]
@nrshapiro I noticed from the recent upload (re: list below) that the article keywords appeared to be displaying - at least in these recent issues. e.g., https://pep-web.org/browse/document/IFP.031.0201A 
Would this suggest that the keywords issue has been resolved?

Recent batch:
PD - PD_Sep-Oct_32_5_2022
PI - PI_Oct_42_7_2022
ANIJP-TR - anijp-tr_13_2021
IFP - IFP_31_4_2022
PAQ - PAQ_91_3_2022

**Comment by ocappello** [comment]
@SophieMBennett hiya, has this been resolved?

**Comment by nrshapiro** [comment]
Looks like it has.  Will verify with Jordan today (it was a client fix)

**Comment by nrshapiro** [comment]
@jordanallen-dev - Please resolve this issue if you've fixed in the client.  It at least appears that you have.
