### ISSUE TITLE
Webx Links in Figure Titles dropped by User Interface XML -> HTML conversion

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#678]
As exemplified here in what was supposed to be a link to Vimeo, there's a problem in the handling of the XML links in figure titles as reported by @davidtuckett 

URL: "https://pep-web.org/search/document/IJP.101.1106A?searchTerms=%5B%7B%22type%22%3A%22author%22%2C%22term%22%3A%22tuckett%2C%20david%22%7D%2C%7B%22type%22%3A%22title%22%2C%22term%22%3A%22training%22%7D%5D"

What is presented to the user:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/4837554/204324935-15c3911f-9ed4-4d0c-b657-c8ce2b074930.png">

Note the text of the figure title in the HTML in the browser:
                     **Video Abstract Read the transcriptWatch the video on Vimeo**

Here's the HTML generated by the client
<p class="figtitle caption">Video Abstract Read the transcriptWatch the video on Vimeo</p>

Here's what was provided by the server in the XML.  Note both the transcription and video links are provided there, but dropped in the XML->HTML conversion by the client (as well as the necessary spacing of the parts.)

<img width="863" alt="image" src="https://user-images.githubusercontent.com/4837554/204326039-f78224e1-0fbf-453c-bb5b-f4cc843751e8.png">

**Comment by jordanallen-dev** [comment]
Resolved in #738
