### ISSUE TITLE
session-id and other user information

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#69]
I've set up the server to be able to read the session-id, as backup to the one in headers, that you store in the pepweb_session cookie.

However, I noticed you are saving it to a domain name that includes the subdomain stage (stage.pep-web.rocks).  If you do that, the pepweb_session cookie will not be shared with the server, which is in another subdomain.  You should give the domain as ".pep-web.rocks" so it works for all subdomains on that domain.

(The server will look for a session-id here after first looking at the header, then the parameters, then the cookie.  But it may also come in handy in client/server communication at a later point, though per an early tech meeting, based on users potentially turning off cookies, I tried to avoid using them.  However, I don't think that's a problem for PEP, since our current system requires that cookies are enabled anyway!)

**Comment by billdami** [comment]
@nrshapiro limiting these frontend-only cookies to only the web app's domain was a conscious decision on our part, as we initially had the cookies scoped to be accessible on all subdomains, but it was causing issues with our cookie library's ability to access the cookies on both the client side and in the node server-side rendering environment (possibly related to recent browser security restrictions that browser vendors have begun to roll out). 

I think it should be possible to eventually fix this, but for the time being we'll probably need to leave those frontend-only cookies scoped to the web app's domain only, to be safe -- until we have more time to investigate it further.

**Comment by billdami** [comment]
also worth noting, we are currently storing session id's in two different cookies, depending on whether its an unauthenticated user, or a logged in user, and will clear the unauthenticated version as a user becomes authenticated. Just something to be aware of as well, as these cookies are a bit volatile, and how we store them (serializing in JSON, etc) could change, so I'd be wary of the API relying on a super stable format here.

**Comment by nrshapiro** [comment]
Change not needed at this point.
