### ISSUE TITLE
Replacement for hyperlinked Glossary entries

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#695]
The client has a feature to show a glossary "word cloud", which appears in one of the infocards, in addition to the popup glossary information.  The words in the word cloud are linked as well.

Given the many problems with the glossary links, I had discussed with DT the possibility of removing the links to glossary words in the document, and keeping only the glossary infocard, which he said would be a good idea.  Many of the matching terms that are marked up are "out of context", and shouldn't be linked anyway.  For that reason, the markup code does try to skip marking up terms which are also "commonly used".  But the code to do the linking does not consider context.

Unfortunately, after we discussed this, I realized the client provides the word cloud by tallying marked up words in the document.  That allows it to show the more frequent words bigger, and of course, only display glossary terms used in the document.  So for the current client as is, keeping the markup was necessary.  

However, I have been thinking of ways to do this easily, with simple changes to the client and server.

In November, I looked into providing term frequency directly to the client from the server, and came up with a way that could be done cleanly and easily.  This means that we could easily get rid of the markup altogether, and not have to work on ways to get around the links for users, such as fixes for the current click issues, and a switch to turn it off and on.

In fact, in testing my idea, it became a reality: the current server now appends a glossary word table in json format as a comment (for future use) at the end of each processed XML file, when it's regenerated by the new online XML converter.  There's a switch in the server settings now to turn off the word glossary markup, and one to turn on the generation of the table.  Since the table generation (as part of the test cases) is appended to the XML as a comment, it's simply ignored by the client, even when it's on and appended.  

All that would be needed in the client would be a small change to use the table generated by the server to build the infocard with the word cloud.

FYI: @SophieMBennett 

Glossary Terms Infocard:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/4837554/207934695-0c9ba5ee-104b-4a83-8764-cfe0c105d28b.png">

Note: The card is designed like a word cloud, but either is not working correctly, or I'm not able to find an example where it works correctly.  A word cloud shows the more frequent terms larger.

Definition from the web:
Word Clouds (also known as wordle, word collage, or tag cloud) are visual representations of words that give greater prominence to words that appear more frequently. When using the Mentimeter word cloud generator, the words that are added most frequently by audience members will increase in size dynamically. This type of visualization can help presenters quickly collect data from their audience, highlight the most common answers and present the data in a way that everyone can understand.

**Comment by davidtuckett** [comment]
I agree. Lets go with that. Good work.

**Comment by SophieMBennett** [comment]
@nrshapiro Re: the current notification on PEP-Web for the change to glossary function, I've now made a help page for the support site and posted links to it on social media. 

The list of glossary terms seems to be limited to 20 words max - just noting this in case it's possible to extend it in the future, perhaps with the scrolling function discussed for other Info cards. https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/635

**Comment by nrshapiro** [comment]
@SophieMBennett - The number can be easily tweaked--that's in the client.  

But when I can update the database and server in a week or so for the 2023 edition, the most frequent glossary words used in each article will be shown there.  That's not true at the moment. 

We can tweak it to eliminate any words hitting higher frequencies because of general use "common" language.

**Comment by nrshapiro** [comment]
This is now complete with the release of the 2023 data last week.

**Comment by ocappello** [comment]
OK, very sorry to re-open this issue. Sophie, Athena, and I are hearing more and more from users, formally (with 1 email) and informally from subs, that the old way of providing hyper-glossed words in the text was better. Working on my own research on PEP, I kinda have to agree. Not urgent, of course, given that we've just changed it and with good reason; but perhaps in the mid- to long-term we can revisit. This is a fantastic research tool that we're offering, unique and intuitive to use, I just want to make sure we're maximizing its value to our subs.

**Comment by ocappello** [comment]
very sensible, thanks @davidtuckett

we wanted to flag

**Comment by SophieMBennett** [comment]
@davidtuckett There is still glossary formatting in the glossary link pop-ups which can be turned on/off in the preference settings.

With glossary formatting:
![Glossary pop-up with glossary formatting](https://user-images.githubusercontent.com/83074920/223171353-4d172b62-f212-46b1-8ba7-40ea4261153a.PNG)

Without:
![Glossary pop-up without glossary formatting](https://user-images.githubusercontent.com/83074920/223171508-b30dfdb3-0c5d-479a-af9e-e3d02e68d586.PNG)
