### ISSUE TITLE
Client version numbers

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#722]
It doesn't look like client version numbers are being updated with changes

Or if they are, the date part doesn't look to be updated.

Stage: Client: 2022.12.23-731097003
Production: Client: 2022.12.23-731097003

**Comment by jordanallen-dev** [comment]
> It doesn't look like client version numbers are being updated with changes
> 
> Or if they are, the date part doesn't look to be updated.
> 
> Stage: Client: 2022.12.23-731097003 Production: Client: 2022.12.23-731097003

BUILD_VERSION is defined with an environment variable set in the .env file

This was previously updated via the GitLab scripts as the environment variables were dynamically generated

To simplify in the absence of any sensitive credentials, I've hard coded the environment files but didn't notice the BUILD_VERSION

I'll update the Terraform module that packages the client to generate and set this variable at build time with the same properties defined in the original CI script
