### ISSUE TITLE
TOC Internal Page Jumps (especially Roman) only work in some instances

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#734]
When checking the latest book TOC I noticed the internal (roman page) links don't work.  I thought Gavant had those working so I tried several different books.

Some of the links here work: https://stage.pep-web.org/browse/document/ZBK.033.0000A?index=28&page=PR0005
and you can see the link was added by the client:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4837554/228682823-48377fd9-0561-4659-9003-b409d9b724ef.png">

But the new book doesn't work.  Nor do several others I tried like this one:

https://stage.pep-web.org/browse/document/ZBK.048.0000A

**Comment by nrshapiro** [comment]
See also #643

**Comment by jordanallen-dev** [comment]
This seems to be an XML issue. When a user clicks on one of these links, the following code is triggered:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/79658146/233349758-7306a58a-3029-4026-82d8-e19bfb8813a1.png">

In the cases where the link doesn't work, the condition on line 477 is not met, meaning it can't find a matching `data-page-start` attribute within the DOM

The link is configured correctly, it's destination isn't

<img width="351" alt="image" src="https://user-images.githubusercontent.com/79658146/233350595-1bea5b38-9d1d-4fdb-b31c-dd9d9ad19fc3.png">

vs

<img width="361" alt="image" src="https://user-images.githubusercontent.com/79658146/233350816-a3d077e9-1bd3-47f3-ab74-e6b29be5e14d.png">

The first image is taken from ZBK.033.0000A where the XML contains the correct destination and the link works

The second image is taken from ZBK.048.0000A where the XML contains the attribute, but with no value and the link does not work

**Comment by jordanallen-dev** [comment]
@nrshapiro 

This seems to be an XML issue. When a user clicks on one of these links, the following code is triggered:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/79658146/233349758-7306a58a-3029-4026-82d8-e19bfb8813a1.png">

In the cases where the link doesn't work, the condition on line 477 is not met, meaning it can't find a matching `data-page-start` attribute within the DOM

The link is configured correctly, it's destination isn't

<img width="351" alt="image" src="https://user-images.githubusercontent.com/79658146/233350595-1bea5b38-9d1d-4fdb-b31c-dd9d9ad19fc3.png">

vs

<img width="361" alt="image" src="https://user-images.githubusercontent.com/79658146/233350816-a3d077e9-1bd3-47f3-ab74-e6b29be5e14d.png">

The first image is taken from ZBK.033.0000A where the XML contains the correct destination and the link works

The second image is taken from ZBK.048.0000A where the XML contains the attribute, but with no value and the link does not work

**Comment by jordanallen-dev** [comment]
@nrshapiro This is exactly what you identified in #643

**Comment by nrshapiro** [comment]
@jordanallen-dev @ocappello

Jordan, what you're looking at is not XML, it's HTML.  And the HTML is created by the client app.

A relevant quote from this issue:

"""
Some of the links here work: https://stage.pep-web.org/browse/document/ZBK.033.0000A?index=28&page=PR0005
and you can see the link was added by the client:"""

from the related issue you point to: https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/643

"""I don't know what they are using to trigger population of that attribute from the XML, but it may be "nextpgnm" which is in the page number element on the page before, just before the start of the new page. But both Glover and Money-Kyrle have these populated correctly, so it must be a client issue."""

**Comment by jordanallen-dev** [comment]
> @jordanallen-dev @ocappello
> 
> Jordan, what you're looking at is not XML, it's HTML. And the HTML is created by the client app.
> 
> A relevant quote from this issue:
> 
> """ Some of the links here work: https://stage.pep-web.org/browse/document/ZBK.033.0000A?index=28&page=PR0005 and you can see the link was added by the client:"""
> 
> from the related issue you point to: #643
> 
> """I don't know what they are using to trigger population of that attribute from the XML, but it may be "nextpgnm" which is in the page number element on the page before, just before the start of the new page. But both Glover and Money-Kyrle have these populated correctly, so it must be a client issue.""" 

I'm aware it's not the XML in the screenshots

I was assuming the HTML renderer was taking this attribute directly from the XML and that it was missing from the source as an initial search didn't show up any results in the renderer

I'll dig a little deeper and see what the client uses to generate it

**Comment by jordanallen-dev** [comment]
@nrshapiro 

Found it. I did a text search for `data-page-start=` instead of `data-page-start` which is why it never showed up

<img width="992" alt="image" src="https://user-images.githubusercontent.com/79658146/233355049-1294067f-9342-4141-83d8-881f79d3ad26.png">

Uses nextpgnm as you thought

**Comment by jordanallen-dev** [comment]
> @nrshapiro
> 
> Found it. I did a text search for `data-page-start=` instead of `data-page-start` which is why it never showed up
> 
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/79658146/233355049-1294067f-9342-4141-83d8-881f79d3ad26.png">
> 
> Uses nextpgnm as you thought

This was an XML consistency issue

When there is no preceding page break siblings, the renderer finds looks for the next page break _within the parent block__ - one level higher

In the one where the links work, the XML looks like this:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/79658146/233385723-24f0e152-05dc-4215-a183-02f34224056e.png">

Notice how the `<pb>` is not inside the `<unit>` block. When the `<h1>` is rendered, it checks for the next `<pb>` one level up

If we look at the XML where the look does not work:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/79658146/233386034-5d33b80f-1926-4c9a-855c-d34bd7cf7d62.png">

We can see it is inside the `<unit>` block.

Instead of having to introduce better consistency retroactively, I've implemented a fix that checks for the next `<pb>` both in the parent and current block and I'm currently deploying it to stage

cc @ocappello @nrshapiro

**Comment by jordanallen-dev** [comment]
@nrshapiro @ocappello 

Now working as expected:

https://stage.pep-web.org/browse/document/ZBK.033.0000A
https://stage.pep-web.org/browse/document/ZBK.048.0000A
