### ISSUE TITLE
Placement of final footnote in article

### ISSUE THREAD

**Issue by SophieMBennett** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#755]
JOAP - JOAP_68_2_April_2023 
https://pep-web.org/browse/JOAP/volumes/68

The final footnote in an article gets placed in the reference list. Ideally it should be placed above references. 

![footnote1](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/assets/83074920/560821bb-7c00-4b25-88dd-7e9039c16f29)
![footnote2](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/assets/83074920/a987a4d5-546b-4df2-9e39-bad94b1b5b30)

**Comment by ocappello** [comment]
ideally!! possibly one of the finest GitHub moments. 

the footnote needs to be with the footnotes, separate from the references. let's please address asap.

**Comment by SophieMBennett** [comment]
I managed to fix this - discovered it is a keying issue in the XML (not platform related). 

![footnotes](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/assets/83074920/aa24cd27-0e0d-461e-befc-521c0fbd2602)

Resolved: Closing.
