### ISSUE TITLE
Mouse Swiping, Dialogs, and Boundaries, Oh My.

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#77]
I hope there's something that can be done about this...it happens to me ALL THE TIME.  It could just be the way I mouse, but I suspect others will experience it too.

Reproduction Example:
1) Go to preferences
2) I want to change the Hits in Context Limit. 
3) I click in the edit field and swipe my mouse to the left.  I do this pretty quickly, so I'm not being careful to stay "within" the box.    But I'm also not trying to go outside the box.
4) Invariably, my mouse goes over the edge of the dialog, and it automatically closes.

It's pretty frustrating.  Happens to me in the login box and now here.  All the time.  No other app I use does this.

I hope this can be addressed.

**Comment by bakerac4** [comment]
Clicking outside the modal has been removed in another release, therefor this should no longer happen
