### ISSUE TITLE
Yellow Access Box appears momentarily at the top (below title) of documents

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#85]
Client: 4584

Yellow Access Box appears momentarily at the top (below title) of documents in Read mode then disappears

![image](https://user-images.githubusercontent.com/4837554/96637235-691ca980-12ec-11eb-82d0-98bb364a8831.png)

**Comment by bakerac4** [comment]
@nrshapiro I looked into this.

It seems that sometimes the API returns accessLimited = true, and others access limited = false.

I believe if you go here https://stage.pep-web.rocks/read/IJP.027.0099A and check the responses you will see that

when well call `/search` access limited is `true`, and when we call `/documents/ID` access limited is `false`

**Comment by nrshapiro** [comment]
@bakerac4 

This bug is talking about a box that shows, correctly that this document is available for viewing, which really has no place anyway in read--unless the document isn't available.

Here's a good test example to show the error you mention: 
  - I logged in as Test1, which has access to PEP-Archive but not PEP-Current.  
  - I searched for year: 2015-2017, which gives you an assortment of items available and not available to read.  
  - Then I clicked on Abbasi, A. 2015. and selected read in the abstract.
  - Click on various entries on the left, and the right should vary between Abstracts for 2017 articles, and full-text for 2015 articles.  Note that a few German journals like Psyche have 5 year embargos, so these are all going to be abstracts.  

Click on 
- Abbasi (2015)
then
- Abassi (2016) right below it.  You'll see yellow boxes appear.

Now I'm looking at the Network tab in inspect, and I see these calls:

- https://stage-api.pep-web.rocks/v2/Documents/Document/PAQ.085.0851A/?similarcount=5&return_format=XML
    - accessLimited=False

In the call just before that, I see:
-  https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&fulltext1=art_qual%3A(%22PAQ.085.0885A%22)&synonyms=false
  - I do see it has the wrong permissions.

I wrote a unit test case using exactly this scenario, and it passes completely.  So something else is happening in the live server with whatever else is happening before it, or other specific conditions.  The only way my code could produce the wrong permissions, given the simplicity of the docPermissions code, is if a weird runtime exception is occurring on AWS, in which case, yes, the fallback default is going to tell you that the documents don't have permission.  Otherwise, it would have to be PaDS.

But while doing that, I note that you are using the prior call to get related documents; why are you looking at permissions at all in that set for the center panel?  That set has nothing to do with the center panel document being shown.  In fact, there's no reason whatsoever to look at read permissions for releated documents ever--they could potentially be not allowed, if one of the related documents is embargoed.  But you aren't actually going to do anything about it, are you?  You don't have to show a Read button for those, and I suspect if you are directly going to Read mode from the Search view for those, it would just bring up an abstract for those, as that's what the server would give you, which is fine (and you would get permissions during that Document call).  The only reason we get permissions for listings during a search is to let you show a Read button for it, for clients who want to get the abstract during search, and need to show the read button for the results/abstracts they collected.  

When you are jumping from a bibliographic entry to Read without an abstract, you don't need to show a read button...just go to read view and depend on the server to return either the full-text (if allowed) or an abstract.  Which is, I'm sure, what you're doing now.  So in any case like that, you don't need to look at permissions when loading them into the infocard.

So, at least for immediate resolution, and better performance, you should not be looking at permissions when populating for related documents, or similar documents for infocards.

And perhaps the fact that you are calling endpoints over and over to get components of the response is an argument for me to add "infocard-centric" endpoints, which address only one component of a document list, and then you'd turn off the feature in the calls you are using now (e.g., setting similarcount to 0.  The server not checking permissions on those based on a more specific call would provide a speed boost and especially since we could turn off permission checking for those.

**Comment by nrshapiro** [comment]
Followed formula above to replicate--fixed.
