### ISSUE TITLE
Some/Many Documents not loading now

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#86]
Many documents are now simply not loading in read mode.  I'm sure it's just a temporary issue you are working on, but just in case you don't know...just in case it was the server, I've tested.

As to the long document, ZBK.153.0001A, that one loads from the server in about 5 or so seconds (estimated).  (The next server update I will load will provide endpoint timings for the /v2/Documents/Document endpoint.  This wasn't done before, but it's something we need to watch).  I tried it both in XML and HTML from the /docs interface and I also added a new test which loads it just to watch for big document issues.

**Comment by nrshapiro** [comment]
I've been setting up more logging code to verify if the problem was in the client and the server.

Here's a document that didn't show up:

![image](https://user-images.githubusercontent.com/4837554/96680050-c7747700-1342-11eb-8ef1-2b132b3bcf78.png)

Here you see that the server delivered 48,619 bytes in the document field.  Oddly, note that the request for the document is sent twice (and delivered correctly twice):

![image](https://user-images.githubusercontent.com/4837554/96679997-add32f80-1342-11eb-97e8-75730aae072a.png)

**Comment by nrshapiro** [comment]
The very next document I tried, a two-three page document:
![image](https://user-images.githubusercontent.com/4837554/96680390-6a2cf580-1343-11eb-8065-c807dd56785f.png)

![image](https://user-images.githubusercontent.com/4837554/96680340-508bae00-1343-11eb-9238-efd6f88d6093.png)

I walked through documents in the read list, and none showed, until the last one you see here in the log, which did:

![image](https://user-images.githubusercontent.com/4837554/96680625-dad41200-1343-11eb-9f92-87499c9ba2f2.png)

Lastly, I walked through some more and found two Archive ones, one which showed, one which didn't, and I went from one to the other and back and forward to see if the missing document persisted...and it did.  One kept showing, the other did not.

![image](https://user-images.githubusercontent.com/4837554/96680887-5635c380-1344-11eb-98f1-1f27a0fb0ed3.png)

**Comment by bakerac4** [comment]
Fixed from previous release
