### ISSUE TITLE
Client: 4692: Can't log in on any ID

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#95]
I thought this was working last night, but today I can't log in with the stage client on any ID.  

![image](https://user-images.githubusercontent.com/4837554/97186278-77991400-1777-11eb-886b-dbc63ce1f7e9.png)

Yet I know the IDs are working, because the server based /Docs login successfully authenticates me with them, eg. Test4.

As does Postman calling Authenticate.

Return:
{
    "SessionId": "9541E4B4-FB4B-414C-8194-64F9E514CC2E",
    "SessionExpires": 604797,
    "IsValidUserName": true,
    "IsValidLogon": true,
    "HasSubscription": true,
    "ReasonId": 200,
    "ReasonStr": null
}

Please fix asap.

**Comment by bakerac4** [comment]
@nrshapiro can you try clearing your cookies? We know about a bug that exists where if you are unable to login when you have an expired anonymous session id. Im wondering if this is that issue and/or related

**Comment by nrshapiro** [comment]
Thanks, yes, that was it.  That needs to be addressed soon though before others run into it.
